// 导入常量
import { ALBUM_COVER_BASE, AUDIO_BASE, AUDIO_BASE_ALL, AUDIO_BASE_GROUP } from '../工具/constants';

export interface Song {
  id: number;
  title: string;
  artist: string; // 角色名
  voiceActor?: string; // 声优名
  album?: string;
  releaseDate?: string;
  type?: string;
  lyrics?: string;
  music?: string;
  arrangement?: string; // 已废弃，将逐步移除
  audioUrl?: string;
  albumCover?: string;
  unit?: string;
  notes?: string;
}

// 根据CSV自动生成，按类型排序：个人曲 -> 组合曲 -> 全体曲
export const songs: Song[] = [
  // ==================== 个人曲 (30首) ====================
  {
    id: 1,
    title: 'ありったけの輝きで',
    artist: '櫻木真乃',
    voiceActor: '関根瞳',
    unit: 'Illumination STARS',
    album: 'COLORFUL FE@THERS -Stella-',
    releaseDate: '2021/1/20',
    type: '个人曲',
    lyrics: 'こだまさおり',
    music: '羊',
    audioUrl: `${AUDIO_BASE}/Arittake.no.Kagayaki.de.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Stella-.jpg`,
  },
  {
    id: 2,
    title: '星をめざして',
    artist: '芹沢あさひ',
    voiceActor: '田中有紀',
    unit: 'Straylight',
    album: 'COLORFUL FE@THERS -Stella-',
    releaseDate: '2021/1/20',
    type: '个人曲',
    lyrics: '下地悠',
    music: '三好啓太',
    audioUrl: `${AUDIO_BASE}/Hoshi.wo.Mezashite.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Stella-.jpg`,
  },
  {
    id: 3,
    title: '夢見鳥',
    artist: '樋口円香',
    voiceActor: '土屋李央',
    unit: 'noctchill',
    album: 'COLORFUL FE@THERS -Stella-',
    releaseDate: '2021/1/20',
    type: '个人曲',
    lyrics: '秋浦智裕(onetrap)',
    music: '家原正樹、Jam9',
    audioUrl: `${AUDIO_BASE}/Yumemi.Dori.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Stella-.jpg`,
  },
  {
    id: 4,
    title: 'アポイント・シグナル',
    artist: '月岡恋鐘',
    voiceActor: '礒部花凜',
    unit: "L'Antica",
    album: 'COLORFUL FE@THERS -Stella-',
    releaseDate: '2021/1/20',
    type: '个人曲',
    lyrics: '真崎エリカ',
    music: '本田正樹(Dream Monster)',
    audioUrl: `${AUDIO_BASE}/Appointment.Signal.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Stella-.jpg`,
  },
  {
    id: 5,
    title: 'チョコデート・サンデー',
    artist: '園田智代子',
    voiceActor: '白石晴香',
    unit: '放課後クライマックスガールズ',
    album: 'COLORFUL FE@THERS -Stella-',
    releaseDate: '2021/1/20',
    type: '个人曲',
    lyrics: '児玉雨子',
    music: '中野領太',
    audioUrl: `${AUDIO_BASE}/Choco.Date.Sunday.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Stella-.jpg`,
  },
  {
    id: 6,
    title: 'Sweet Memories',
    artist: '大崎甘奈',
    voiceActor: '黒木ほの香',
    unit: 'Alstroemeria',
    album: 'COLORFUL FE@THERS -Stella-',
    releaseDate: '2021/1/20',
    type: '个人曲',
    lyrics: '鈴木静那',
    music: 'h-wonder',
    audioUrl: `${AUDIO_BASE}/Sweet.Memories.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Stella-.jpg`,
  },
  {
    id: 7,
    title: 'ハナマルバッジ',
    artist: '小宮果穂',
    voiceActor: '河野日和',
    unit: '放課後クライマックスガールズ',
    album: 'COLORFUL FE@THERS -Stella-',
    releaseDate: '2021/1/20',
    type: '个人曲',
    lyrics: '古屋真',
    music: '小久保祐希、YUU for YOU',
    audioUrl: `${AUDIO_BASE}/Hanamaru.Badge.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Stella-.jpg`,
  },
  {
    id: 8,
    title: '誰ソ彼アイデンティティー',
    artist: '田中摩美々',
    voiceActor: '菅沼千紗',
    unit: "L'Antica",
    album: 'COLORFUL FE@THERS -Luna-',
    releaseDate: '2021/2/17',
    type: '个人曲',
    lyrics: '松井洋平',
    music: '高尾奏之介',
    audioUrl: `${AUDIO_BASE}/Tasogare.Identity.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Luna-.jpg`,
  },
  {
    id: 9,
    title: 'わたしの主人公はわたしだから！',
    artist: '福丸小糸',
    voiceActor: '田嶌紗蘭',
    unit: 'noctchill',
    album: 'COLORFUL FE@THERS -Luna-',
    releaseDate: '2021/2/17',
    type: '个人曲',
    lyrics: '秋浦智裕(onetrap)',
    music: '本多友紀(Arte Refact)',
    audioUrl: `${AUDIO_BASE}/Watashi.no.Shujinkou.wa.Watashi.dakara.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Luna-.jpg`,
  },
  {
    id: 10,
    title: 'また明日',
    artist: '大崎甜花',
    voiceActor: '前川涼子',
    unit: 'Alstroemeria',
    album: 'COLORFUL FE@THERS -Luna-',
    releaseDate: '2021/2/17',
    type: '个人曲',
    lyrics: '鈴木静那',
    music: 'JUVENILE',
    audioUrl: `${AUDIO_BASE}/Mata.Ashita.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Luna-.jpg`,
  },
  {
    id: 11,
    title: '常咲の庭',
    artist: '杜野凛世',
    voiceActor: '丸岡和佳奈',
    unit: '放課後クライマックスガールズ',
    album: 'COLORFUL FE@THERS -Luna-',
    releaseDate: '2021/2/17',
    type: '个人曲',
    lyrics: '古屋真',
    music: '田熊知存(Dream Monster)',
    audioUrl: `${AUDIO_BASE}/Tokosaki.no.Niwa.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Luna-.jpg`,
  },
  {
    id: 12,
    title: 'プラスチック・アンブレラ',
    artist: '三峰結華',
    voiceActor: '成海瑠奈',
    unit: "L'Antica",
    album: 'COLORFUL FE@THERS -Luna-',
    releaseDate: '2021/2/17',
    type: '个人曲',
    lyrics: '児玉雨子',
    music: '矢吹香那',
    audioUrl: `${AUDIO_BASE}/Plastic.Umbrella.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Luna-.jpg`,
  },
  {
    id: 13,
    title: 'Going my way',
    artist: '和泉愛依',
    voiceActor: '北原沙弥香',
    unit: 'Straylight',
    album: 'COLORFUL FE@THERS -Luna-',
    releaseDate: '2021/2/17',
    type: '个人曲',
    lyrics: '下地悠',
    music: '渡辺徹',
    audioUrl: `${AUDIO_BASE}/Going.my.way.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Luna-.jpg`,
  },
  {
    id: 14,
    title: '雪・月・風・花',
    artist: '幽谷霧子',
    voiceActor: '結名美月',
    unit: "L'Antica",
    album: 'COLORFUL FE@THERS -Luna-',
    releaseDate: '2021/2/17',
    type: '个人曲',
    lyrics: '真崎エリカ',
    music: 'rionos',
    audioUrl: `${AUDIO_BASE}/Yuki.Tsuki.Kaze.Hana.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Luna-.jpg`,
  },
  {
    id: 15,
    title: 'スローモーション',
    artist: '風野灯織',
    voiceActor: '近藤玲奈',
    unit: 'Illumination STARS',
    album: 'COLORFUL FE@THERS -Sol-',
    releaseDate: '2021/3/10',
    type: '个人曲',
    lyrics: '中村彼方',
    music: '岩越涼大',
    audioUrl: `${AUDIO_BASE}/Slow.Motion.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Sol-.jpg`,
  },
  {
    id: 16,
    title: '千夜アリア',
    artist: '白瀬咲耶',
    voiceActor: '八巻アンナ',
    unit: "L'Antica",
    album: 'COLORFUL FE@THERS -Sol-',
    releaseDate: '2021/3/10',
    type: '个人曲',
    lyrics: '真崎エリカ',
    music: '藤井健太郎(HANO)、谷ナオキ(HANO)',
    audioUrl: `${AUDIO_BASE}/Senya.Aria.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Sol-.jpg`,
  },
  {
    id: 17,
    title: 'Damascus Cocktail',
    artist: '有栖川夏葉',
    voiceActor: '涼本あきほ',
    unit: '放課後クライマックスガールズ',
    album: 'COLORFUL FE@THERS -Sol-',
    releaseDate: '2021/3/10',
    type: '个人曲',
    lyrics: '古屋真',
    music: '陶山隼',
    audioUrl: `${AUDIO_BASE}/Damascus.Cocktail.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Sol-.jpg`,
  },
  {
    id: 18,
    title: 'Darling you!',
    artist: '桑山千雪',
    voiceActor: '芝崎典子',
    unit: 'Alstroemeria',
    album: 'COLORFUL FE@THERS -Sol-',
    releaseDate: '2021/3/10',
    type: '个人曲',
    lyrics: '鈴木静那',
    music: '南直博',
    audioUrl: `${AUDIO_BASE}/Darling.you.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Sol-.jpg`,
  },
  {
    id: 19,
    title: 'あおぞらサイダー',
    artist: '市川雛菜',
    voiceActor: '岡咲美保',
    unit: 'noctchill',
    album: 'COLORFUL FE@THERS -Sol-',
    releaseDate: '2021/3/10',
    type: '个人曲',
    lyrics: '秋浦智裕(onetrap)',
    music: '小久保祐希、YUU for YOU',
    audioUrl: `${AUDIO_BASE}/Aozora.Cider.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Sol-.jpg`,
  },
  {
    id: 20,
    title: 'SOS',
    artist: '黛冬優子',
    voiceActor: '幸村恵理',
    unit: 'Straylight',
    album: 'COLORFUL FE@THERS -Sol-',
    releaseDate: '2021/3/10',
    type: '个人曲',
    lyrics: '下地悠',
    music: '睦月周平',
    audioUrl: `${AUDIO_BASE}/SOS.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Sol-.jpg`,
  },
  {
    id: 21,
    title: '過純性ブリーチ',
    artist: '西城樹里',
    voiceActor: '永井真里子',
    unit: '放課後クライマックスガールズ',
    album: 'COLORFUL FE@THERS -Sol-',
    releaseDate: '2021/3/10',
    type: '个人曲',
    lyrics: '古屋真',
    music: '大西克巳',
    audioUrl: `${AUDIO_BASE}/Kajunsei.Bleach.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Sol-.jpg`,
  },
  {
    id: 22,
    title: 'HAREBARE!!',
    artist: '八宮めぐる',
    voiceActor: '峰田茉優',
    unit: 'Illumination STARS',
    album: 'COLORFUL FE@THERS -Sol-',
    releaseDate: '2021/3/10',
    type: '个人曲',
    lyrics: '渡邊亜希子',
    music: '大西克巳',
    audioUrl: `${AUDIO_BASE}/HAREBARE.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Sol-.jpg`,
  },
  {
    id: 23,
    title: 'statice',
    artist: '浅倉透',
    voiceActor: '和久井優',
    unit: 'noctchill',
    album: 'COLORFUL FE@THERS -Sol-',
    releaseDate: '2021/3/10',
    type: '个人曲',
    lyrics: '秋浦智裕(onetrap)',
    music: '家原正樹、Jam9',
    audioUrl: `${AUDIO_BASE}/statice.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-Sol-.jpg`,
  },
  {
    id: 24,
    title: 'フェアリー・ガール',
    artist: '七草にちか',
    voiceActor: '紫月杏朱彩',
    unit: 'SHHis',
    album: 'COLORFUL FE@THERS -SHHis-',
    releaseDate: '2023/7/26',
    type: '个人曲',
    lyrics: '深川琴美',
    music: '佐藤樹',
    audioUrl: `${AUDIO_BASE}/Fairy.Girl.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-SHHis-.jpg`,
  },
  {
    id: 25,
    title: 'Look up to the sky',
    artist: '緋田美琴',
    voiceActor: '山根綺',
    unit: 'SHHis',
    album: 'COLORFUL FE@THERS -SHHis-',
    releaseDate: '2023/7/26',
    type: '个人曲',
    lyrics: 'Co-sho',
    music: 'Stand Alone、小久保祐希、Karen Yamaguchi',
    audioUrl: `${AUDIO_BASE}/Look.up.to.the.sky.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-SHHis-.jpg`,
  },
  {
    id: 26,
    title: 'デビ太郎のうた',
    artist: '大崎甜花',
    voiceActor: '前川涼子',
    unit: 'Alstroemeria',
    album: 'デビ太郎 VS ジャスティスV',
    releaseDate: '2020/7/29',
    type: '个人曲',
    lyrics: '深川琴美',
    music: '宝野聡史',
    audioUrl: `${AUDIO_BASE}/Debi.Taro.no.Uta.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/Debi.Taro.VS.Justice.V.jpg`,
  },
  {
    id: 27,
    title: '絶対正義 EVERY DAY',
    artist: '小宮果穂',
    voiceActor: '河野日和',
    unit: '放課後クライマックスガールズ',
    album: 'デビ太郎 VS ジャスティスV',
    releaseDate: '2020/7/29',
    type: '个人曲',
    lyrics: '前田甘露',
    music: '景山将太',
    audioUrl: `${AUDIO_BASE}/Zettai.Seigi.EVERY.DAY.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/Debi.Taro.VS.Justice.V.jpg`,
  },
  {
    id: 28,
    title: '神様は死んだ、って',
    artist: '斑鳩ルカ',
    voiceActor: '川口莉奈',
    unit: 'CoMETIK',
    album: 'THE IDOLM@STER SHINY COLORS COLORFUL FE@THERS -CoMETIK-',
    releaseDate: '2024/12/4',
    type: '个人曲',
    lyrics: '烏屋茶房',
    music: '水野谷怜(Arte Refact)',
    audioUrl: `${AUDIO_BASE}/Kamisama.wa.Shinda.tte.2024.Remastering.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-CoMETIK-.jpg`,
  },
  {
    id: 29,
    title: '無垢',
    artist: '鈴木羽那',
    voiceActor: '三川華月',
    unit: 'CoMETIK',
    album: 'THE IDOLM@STER SHINY COLORS COLORFUL FE@THERS -CoMETIK-',
    releaseDate: '2024/12/5',
    type: '个人曲',
    lyrics: '園田健太郎',
    music: 'ねりきり',
    audioUrl: `${AUDIO_BASE}/Muku.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-CoMETIK-.jpg`,
  },
  {
    id: 30,
    title: '夢模様キャンバス',
    artist: '郁田はるき',
    voiceActor: '小澤麗那',
    unit: 'CoMETIK',
    album: 'THE IDOLM@STER SHINY COLORS COLORFUL FE@THERS -CoMETIK-',
    releaseDate: '2024/12/6',
    type: '个人曲',
    lyrics: '出口 遼',
    music: '出口 遼',
    audioUrl: `${AUDIO_BASE}/Yumemoyou.Canvas.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/COLORFUL.FE@THERS.-CoMETIK-.jpg`,
  },

  // ==================== 组合曲 (141首) ====================
  {
    id: 31,
    title: 'ヒカリのdestination',
    artist: 'illumination STARS',
    unit: 'illumination STARS',
    album: 'BRILLI@NT WING 02 ヒカリのdestination',
    releaseDate: '2018/7/4',
    type: '组合曲',
    lyrics: '中村彼方',
    audioUrl: `${AUDIO_BASE_GROUP}/Hikari.no.destination.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/BRILLI@NT.WING.02.jpg`,
  },
  {
    id: 32,
    title: '虹になれ',
    artist: 'illumination STARS',
    unit: 'illumination STARS',
    album: 'BRILLI@NT WING 02 ヒカリのdestination',
    releaseDate: '2018/7/4',
    type: '组合曲',
    lyrics: '藤末樹',
    audioUrl: `${AUDIO_BASE_GROUP}/Niji.ni.Nare.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/BRILLI@NT.WING.02.jpg`,
  },
  {
    id: 33,
    title: 'Spread the Wings!!(illumination STARS Ver.)',
    artist: 'illumination STARS',
    unit: 'illumination STARS',
    album: 'BRILLI@NT WING 02 ヒカリのdestination',
    releaseDate: '2018/7/4',
    type: '组合曲',
    lyrics: 'こだまさおり',
    audioUrl: `${AUDIO_BASE_GROUP}/Spread.the.Wings.Illumination.STARS.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/BRILLI@NT.WING.02.jpg`,
  },
  {
    id: 34,
    title: 'We can go now!',
    artist: 'illumination STARS',
    unit: 'illumination STARS',
    album: 'FR@GMENT WING 02',
    releaseDate: '2019/5/8',
    type: '组合曲',
    lyrics: '中村彼方',
    audioUrl: `${AUDIO_BASE_GROUP}/We.can.go.now.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/FR@GMENT.WING.02.jpg`,
  },
  {
    id: 35,
    title: 'トライアングル',
    artist: 'illumination STARS',
    unit: 'illumination STARS',
    album: 'FR@GMENT WING 02',
    releaseDate: '2019/5/8',
    type: '组合曲',
    lyrics: "Giz'Mo ArmySlick",
    audioUrl: `${AUDIO_BASE_GROUP}/Triangle.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/FR@GMENT.WING.02.jpg`,
  },
  {
    id: 36,
    title: 'Ambitious Eve(illumination STARS Ver.)',
    artist: 'illumination STARS',
    unit: 'illumination STARS',
    album: 'FR@GMENT WING 02',
    releaseDate: '2019/5/8',
    type: '组合曲',
    lyrics: '真崎エリカ',
    audioUrl: `${AUDIO_BASE_GROUP}/Ambitious.Eve.Illumination.STARS.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/FR@GMENT.WING.02.jpg`,
  },
  {
    id: 37,
    title: 'Twinkle way',
    artist: 'illumination STARS',
    unit: 'illumination STARS',
    album: 'GR@DATE WING 02',
    releaseDate: '2020/10/14',
    type: '组合曲',
    lyrics: '渡邊亜希子',
    audioUrl: `${AUDIO_BASE_GROUP}/Twinkle.way.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/GR@DATE.WING.02.jpg`,
  },
  {
    id: 38,
    title: 'Happy Funny Lucky',
    artist: 'illumination STARS',
    unit: 'illumination STARS',
    album: 'GR@DATE WING 02',
    releaseDate: '2020/10/14',
    type: '组合曲',
    lyrics: '中野領太',
    audioUrl: `${AUDIO_BASE_GROUP}/Happy.Funny.Lucky.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/GR@DATE.WING.02.jpg`,
  },
  {
    id: 39,
    title: 'シャイノグラフィ(illumination STARS Ver.)',
    artist: 'illumination STARS',
    unit: 'illumination STARS',
    album: 'GR@DATE WING 02',
    releaseDate: '2020/10/14',
    type: '组合曲',
    lyrics: '古屋 真',
    audioUrl: `${AUDIO_BASE_GROUP}/Shainography.Illumination.STARS.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/GR@DATE.WING.02.jpg`,
  },
  {
    id: 40,
    title: 'PRISISM',
    artist: 'illumination STARS',
    unit: 'illumination STARS',
    album: 'L@YERED WING 02',
    releaseDate: '2021/5/19',
    type: '组合曲',
    lyrics: '渡邊亜希子',
    audioUrl: `${AUDIO_BASE_GROUP}/PRISISM.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.02.jpg`,
  },
  {
    id: 41,
    title: 'スマイルシンフォニア',
    artist: 'illumination STARS',
    unit: 'illumination STARS',
    album: 'L@YERED WING 02',
    releaseDate: '2021/5/19',
    type: '组合曲',
    lyrics: '不详',
    audioUrl: `${AUDIO_BASE_GROUP}/Smile.Symphonia.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.02.jpg`,
  },
  {
    id: 42,
    title: 'Resonance+(illumination STARS Ver.)',
    artist: 'illumination STARS',
    unit: 'illumination STARS',
    album: 'L@YERED WING 02',
    releaseDate: '2021/5/19',
    type: '组合曲',
    lyrics: '園田健太郎',
    audioUrl: `${AUDIO_BASE_GROUP}/Resonance.Plus.Illumination.STARS.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.02.jpg`,
  },
  {
    id: 43,
    title: 'FELICE',
    artist: 'illumination STARS',
    unit: 'illumination STARS',
    album: 'PANOR@MA WING 02',
    releaseDate: '2022/5/11',
    type: '组合曲',
    lyrics: '渡邊亜希子',
    audioUrl: `${AUDIO_BASE_GROUP}/FELICE.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.02.jpg`,
  },
  {
    id: 44,
    title: 'イルミネイトコンサート',
    artist: 'illumination STARS',
    unit: 'illumination STARS',
    album: 'PANOR@MA WING 02',
    releaseDate: '2022/5/11',
    type: '组合曲',
    lyrics: '渡辺徹',
    audioUrl: `${AUDIO_BASE_GROUP}/Illuminate.Concert.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.02.jpg`,
  },
  {
    id: 45,
    title: '虹の行方(illumination STARS Ver.)',
    artist: 'illumination STARS',
    unit: 'illumination STARS',
    album: 'PANOR@MA WING 02',
    releaseDate: '2022/5/11',
    type: '组合曲',
    lyrics: '古屋真',
    audioUrl: `${AUDIO_BASE_GROUP}/Niji.no.Yukue.Illumination.STARS.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.02.jpg`,
  },
  {
    id: 46,
    title: 'Forward March！！！',
    artist: 'illumination STARS',
    unit: 'illumination STARS',
    album: 'CANVAS 01',
    releaseDate: '2023/4/12',
    type: '组合曲',
    lyrics: '渡邊亜希子',
    audioUrl: `${AUDIO_BASE_GROUP}/Forward.March.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.01.jpg`,
  },
  {
    id: 47,
    title: '星が流れて',
    artist: 'illumination STARS',
    unit: 'illumination STARS',
    album: 'CANVAS 01',
    releaseDate: '2023/4/12',
    type: '组合曲',
    lyrics: '山田智和',
    audioUrl: `${AUDIO_BASE_GROUP}/Hoshi.ga.Nagarete.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.01.jpg`,
  },
  {
    id: 48,
    title: 'BRIGHTEST WHITE',
    artist: 'illumination STARS',
    unit: 'illumination STARS',
    album: 'CANVAS 01',
    releaseDate: '2023/4/12',
    type: '组合曲',
    lyrics: '草野将史',
    audioUrl: `${AUDIO_BASE_GROUP}/BRIGHTEST.WHITE.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.01.jpg`,
  },
  {
    id: 49,
    title: '枕木の歌',
    artist: 'illumination STARS',
    unit: 'illumination STARS',
    album: 'Song for Prism Happier / 枕木の歌',
    releaseDate: '2024/5/22',
    type: '组合曲',
    lyrics: '渡邊亜希子',
    audioUrl: `${AUDIO_BASE_GROUP}/Makuragi.no.Uta.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/Makuragi.no.Uta.jpg`,
  },
  {
    id: 50,
    title: 'バベルシティ・グレイス',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'BRILLI@NT WING 03 バベルシティ・グレイス',
    releaseDate: '2018/8/1',
    type: '组合曲',
    lyrics: '真崎エリカ',
    audioUrl: `${AUDIO_BASE_GROUP}/Babel.City.Grace.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/BRILLI@NT.WING.03.jpg`,
  },
  {
    id: 51,
    title: '幻惑SILHOUETTE',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'BRILLI@NT WING 03 バベルシティ・グレイス',
    releaseDate: '2018/8/1',
    type: '组合曲',
    lyrics: 'no_my',
    audioUrl: `${AUDIO_BASE_GROUP}/Genwaku.SILHOUETTE.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/BRILLI@NT.WING.03.jpg`,
  },
  {
    id: 52,
    title: 'Spread the Wings!!(アンティーカ Ver.)',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'BRILLI@NT WING 03 バベルシティ・グレイス',
    releaseDate: '2018/8/1',
    type: '组合曲',
    lyrics: 'こだまさおり',
    audioUrl: `${AUDIO_BASE_GROUP}/Spread.the.Wings.LAntica.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/BRILLI@NT.WING.03.jpg`,
  },
  {
    id: 53,
    title: 'NEO THEORY FANTASY',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'FR@GMENT WING 03',
    releaseDate: '2019/6/12',
    type: '组合曲',
    lyrics: '真崎エリカ',
    audioUrl: `${AUDIO_BASE_GROUP}/NEO.THEORY.FANTASY.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/FR@GMENT.WING.03.jpg`,
  },
  {
    id: 54,
    title: 'ラビリンス・レジスタンス',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'FR@GMENT WING 03',
    releaseDate: '2019/6/12',
    type: '组合曲',
    lyrics: '家原正树 Lauren Kaori',
    audioUrl: `${AUDIO_BASE_GROUP}/Labyrinth.Resistance.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/FR@GMENT.WING.03.jpg`,
  },
  {
    id: 55,
    title: 'Ambitious Eve(アンティーカ Ver.)',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'FR@GMENT WING 03',
    releaseDate: '2019/6/12',
    type: '组合曲',
    lyrics: '真崎エリカ',
    audioUrl: `${AUDIO_BASE_GROUP}/Ambitious.Eve.LAntica.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/FR@GMENT.WING.03.jpg`,
  },
  {
    id: 56,
    title: 'Black Reverie',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'GR@DATE WING 03',
    releaseDate: '2020/11/4',
    type: '组合曲',
    lyrics: '真崎エリカ',
    audioUrl: `${AUDIO_BASE_GROUP}/Black.Reverie.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/GR@DATE.WING.03.jpg`,
  },
  {
    id: 57,
    title: '純白トロイメライ',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'GR@DATE WING 03',
    releaseDate: '2020/11/4',
    type: '组合曲',
    lyrics: '原田篤 (Arte Refact)',
    audioUrl: `${AUDIO_BASE_GROUP}/Junpaku.Traumerei.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/GR@DATE.WING.03.jpg`,
  },
  {
    id: 58,
    title: 'シャイノグラフィ(アンティーカ Ver.)',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'GR@DATE WING 03',
    releaseDate: '2020/11/4',
    type: '组合曲',
    lyrics: '古屋 真',
    audioUrl: `${AUDIO_BASE_GROUP}/Shainography.LAntica.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/GR@DATE.WING.03.jpg`,
  },
  {
    id: 59,
    title: 'abyss of conflict',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'L@YERED WING 03',
    releaseDate: '2021/6/9',
    type: '组合曲',
    lyrics: '真崎エリカ',
    audioUrl: `${AUDIO_BASE_GROUP}/abyss.of.conflict.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.03.jpg`,
  },
  {
    id: 60,
    title: '革命進化論',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'L@YERED WING 03',
    releaseDate: '2021/6/9',
    type: '组合曲',
    lyrics: '伊藤和馬(Arte Refact)',
    audioUrl: `${AUDIO_BASE_GROUP}/Kakumei.Shinkaron.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.03.jpg`,
  },
  {
    id: 61,
    title: 'Resonance+(アンティーカ Ver.)',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'L@YERED WING 03',
    releaseDate: '2021/6/9',
    type: '组合曲',
    lyrics: '園田健太郎',
    audioUrl: `${AUDIO_BASE_GROUP}/Resonance.Plus.LAntica.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.03.jpg`,
  },
  {
    id: 62,
    title: '浮動性イノセンス',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'PANOR@MA WING 03',
    releaseDate: '2022/6/15',
    type: '组合曲',
    lyrics: '真崎エリカ',
    audioUrl: `${AUDIO_BASE_GROUP}/Fudousei.Innocence.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.03.jpg`,
  },
  {
    id: 63,
    title: '愚者の独白',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'PANOR@MA WING 03',
    releaseDate: '2022/6/15',
    type: '组合曲',
    lyrics: 'ArmySlick、Lauren Kaori',
    audioUrl: `${AUDIO_BASE_GROUP}/Gusha.no.Dokuhaku.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.03.jpg`,
  },
  {
    id: 64,
    title: '虹の行方(アンティーカVer.)',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'PANOR@MA WING 03',
    releaseDate: '2022/6/15',
    type: '组合曲',
    lyrics: '古屋 真',
    audioUrl: `${AUDIO_BASE_GROUP}/Niji.no.Yukue.LAntica.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.03.jpg`,
  },
  {
    id: 65,
    title: 'とある英雄たちの物語',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'CANVAS 02',
    releaseDate: '2023/5/10',
    type: '组合曲',
    lyrics: '真崎エリカ',
    audioUrl: `${AUDIO_BASE_GROUP}/Toaru.Eiyuu.tachi.no.Monogatari.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.02.jpg`,
  },
  {
    id: 66,
    title: 'Unsung Heroes',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'CANVAS 02',
    releaseDate: '2023/5/10',
    type: '组合曲',
    lyrics: '原田 篤 (Arte Refact)',
    audioUrl: `${AUDIO_BASE_GROUP}/Unsung.Heroes.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.02.jpg`,
  },
  {
    id: 67,
    title: '有彩色ユリイカ',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'CANVAS 02',
    releaseDate: '2023/5/10',
    type: '组合曲',
    lyrics: '藤井健太郎 (HANO)',
    audioUrl: `${AUDIO_BASE_GROUP}/Yuusaishoku.Eureka.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.02.jpg`,
  },
  {
    id: 68,
    title: '文明開花輪舞 -シティ・ハレルヤ-',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'ECHOES 02',
    releaseDate: '2024/6/12',
    type: '组合曲',
    lyrics: '真崎エリカ',
    audioUrl: `${AUDIO_BASE_GROUP}/Bunmei.Kaika.Rinbu.City.Hallelujah.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/ECHOES.02.jpg`,
  },
  {
    id: 69,
    title: '秋の終わり、僕の記憶',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'ECHOES 02',
    releaseDate: '2024/6/12',
    type: '组合曲',
    lyrics: "ArmySlick、Giz'Mo(from Jam9)",
    audioUrl: `${AUDIO_BASE_GROUP}/Aki.no.Owari.Boku.no.Kioku.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/ECHOES.02.jpg`,
  },
  {
    id: 70,
    title: 'Migratory Echoes (アンティーカVer.)',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'ECHOES 02',
    releaseDate: '2024/6/12',
    type: '组合曲',
    lyrics: '松井洋平、真崎エリカ',
    audioUrl: `${AUDIO_BASE_GROUP}/Migratory.Echoes.LAntica.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/ECHOES.02.jpg`,
  },
  {
    id: 71,
    title: '時限式狂騒ワンダーランド',
    artist: "L'Antica",
    unit: "L'Antica",
    album: 'Song for Prism 時限式狂騒ワンダーランド / LINKs',
    releaseDate: '2024/7/24',
    type: '组合曲',
    lyrics: '真崎エリカ',
    audioUrl: `${AUDIO_BASE_GROUP}/JigenShiki.Kyousou.Wonderland.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/JigenShiki.Kyousou.Wonderland.jpg`,
  },
  {
    id: 72,
    title: '夢咲きAfter school',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'BRILLI@NT WING 04 夢咲きAfter school',
    releaseDate: '2018/9/5',
    type: '组合曲',
    lyrics: '古屋真',
    audioUrl: `${AUDIO_BASE_GROUP}/Yumesaki.After.school.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/BRILLI@NT.WING.04.jpg`,
  },
  {
    id: 73,
    title: '太陽キッス',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'BRILLI@NT WING 04 夢咲きAfter school',
    releaseDate: '2018/9/5',
    type: '组合曲',
    lyrics: 'no_my',
    audioUrl: `${AUDIO_BASE_GROUP}/Taiyou.Kiss.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/BRILLI@NT.WING.04.jpg`,
  },
  {
    id: 74,
    title: 'Spread the Wings!!(放課後CLIMAX GIRLS Ver.)',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'BRILLI@NT WING 04 夢咲きAfter school',
    releaseDate: '2018/9/5',
    type: '组合曲',
    lyrics: 'こだまさおり',
    audioUrl: `${AUDIO_BASE_GROUP}/Spread.the.Wings.Houkago.CLIMAX.GIRLS.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/BRILLI@NT.WING.04.jpg`,
  },
  {
    id: 75,
    title: 'ビーチブレイバー',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'FR@GMENT WING 04',
    releaseDate: '2019/7/10',
    type: '组合曲',
    lyrics: '古屋真',
    audioUrl: `${AUDIO_BASE_GROUP}/Beach.Braver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/FR@GMENT.WING.04.jpg`,
  },
  {
    id: 76,
    title: 'よりみちサンセット',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'FR@GMENT WING 04',
    releaseDate: '2019/7/10',
    type: '组合曲',
    lyrics: '小久保祐希 YUU for YOU',
    audioUrl: `${AUDIO_BASE_GROUP}/Yorimichi.Sunset.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/FR@GMENT.WING.04.jpg`,
  },
  {
    id: 77,
    title: 'Ambitious Eve(放課後CLIMAX GIRLS Ver.)',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'FR@GMENT WING 04',
    releaseDate: '2019/7/10',
    type: '组合曲',
    lyrics: '真崎エリカ',
    audioUrl: `${AUDIO_BASE_GROUP}/Ambitious.Eve.Houkago.CLIMAX.GIRLS.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/FR@GMENT.WING.04.jpg`,
  },
  {
    id: 78,
    title: '五ッ座流星群',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'GR@DATE WING 04',
    releaseDate: '2020/11/18',
    type: '组合曲',
    lyrics: '古屋真',
    audioUrl: `${AUDIO_BASE_GROUP}/Itsutsuza.Ryuuseigun.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/GR@DATE.WING.04.jpg`,
  },
  {
    id: 79,
    title: '学祭革命夜明け前',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'GR@DATE WING 04',
    releaseDate: '2020/11/18',
    type: '组合曲',
    lyrics: '佐々倉有吾',
    audioUrl: `${AUDIO_BASE_GROUP}/Gakusai.Kakumei.Yoake.Mae.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/GR@DATE.WING.04.jpg`,
  },
  {
    id: 80,
    title: 'シャイノグラフィ(放課後CLIMAX GIRLS Ver.)',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'GR@DATE WING 04',
    releaseDate: '2020/11/18',
    type: '组合曲',
    lyrics: '古屋真',
    audioUrl: `${AUDIO_BASE_GROUP}/Shainography.Houkago.CLIMAX.GIRLS.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/GR@DATE.WING.04.jpg`,
  },
  {
    id: 81,
    title: 'クライマックスアイランド',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'L@YERED WING 04',
    releaseDate: '2021/7/14',
    type: '组合曲',
    lyrics: '古屋真',
    audioUrl: `${AUDIO_BASE_GROUP}/Climax.Island.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.04.jpg`,
  },
  {
    id: 82,
    title: '拝啓タイムカプセル',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'L@YERED WING 04',
    releaseDate: '2021/7/14',
    type: '组合曲',
    lyrics: '小久保祐希、YUU for YOU',
    audioUrl: `${AUDIO_BASE_GROUP}/Haikei.Time.Capsule.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.04.jpg`,
  },
  {
    id: 83,
    title: 'Resonance+(放課後CLIMAX GIRLS Ver.)',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'L@YERED WING 04',
    releaseDate: '2021/7/14',
    type: '组合曲',
    lyrics: '園田健太郎',
    audioUrl: `${AUDIO_BASE_GROUP}/Resonance.Plus.Houkago.CLIMAX.GIRLS.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.04.jpg`,
  },
  {
    id: 84,
    title: '一閃は君が導く',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'PANOR@MA WING 04',
    releaseDate: '2022/7/13',
    type: '组合曲',
    lyrics: '古屋 真',
    audioUrl: `${AUDIO_BASE_GROUP}/Issen.wa.Kimi.ga.Michibiku.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.04.jpg`,
  },
  {
    id: 85,
    title: 'キャットスクワッド',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'PANOR@MA WING 04',
    releaseDate: '2022/7/13',
    type: '组合曲',
    lyrics: '小久保祐希、YUU for YOU',
    audioUrl: `${AUDIO_BASE_GROUP}/Cat.Squad.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.04.jpg`,
  },
  {
    id: 86,
    title: '虹の行方(放課後CLIMAX GIRLS Ver.)',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'PANOR@MA WING 04',
    releaseDate: '2022/7/13',
    type: '组合曲',
    lyrics: '古屋 真',
    audioUrl: `${AUDIO_BASE_GROUP}/Niji.no.Yukue.Houkago.CLIMAX.GIRLS.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.04.jpg`,
  },
  {
    id: 87,
    title: 'ハナサカサイサイ',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'CANVAS 03',
    releaseDate: '2023/6/14',
    type: '组合曲',
    lyrics: '古屋 真',
    audioUrl: `${AUDIO_BASE_GROUP}/Hanasaka.Saisai.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.03.jpg`,
  },
  {
    id: 88,
    title: '全力アンサー',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'CANVAS 03',
    releaseDate: '2023/6/14',
    type: '组合曲',
    lyrics: '藤井健太郎 (HANO)',
    audioUrl: `${AUDIO_BASE_GROUP}/Zenryoku.Answer.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.03.jpg`,
  },
  {
    id: 89,
    title: 'ひめくりモザイク',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'CANVAS 03',
    releaseDate: '2023/6/14',
    type: '组合曲',
    lyrics: '牧野太洋',
    audioUrl: `${AUDIO_BASE_GROUP}/Himekuri.Mosaic.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.03.jpg`,
  },
  {
    id: 90,
    title: '裸足じゃイラレナイ',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'Song for Prism 裸足じゃイラレナイ / 明日もBeautiful Day',
    releaseDate: '2024/1/24',
    type: '组合曲',
    lyrics: '古屋 真',
    audioUrl: `${AUDIO_BASE_GROUP}/Hadashi.ja.Irarenai.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/Hadashi.ja.Irarenai.jpg`,
  },
  {
    id: 91,
    title: '放課後マギア',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'ECHOES 03',
    releaseDate: '2024/7/10',
    type: '组合曲',
    lyrics: '古屋真',
    audioUrl: `${AUDIO_BASE_GROUP}/Houkago.Magia.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/ECHOES.03.jpg`,
  },
  {
    id: 92,
    title: 'パーティーマジックデザイナー',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'ECHOES 03',
    releaseDate: '2024/7/10',
    type: '组合曲',
    lyrics: '牧野太洋',
    audioUrl: `${AUDIO_BASE_GROUP}/Party.Magic.Designer.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/ECHOES.03.jpg`,
  },
  {
    id: 93,
    title: 'Migratory Echoes(放課後CLIMAX GIRLS Ver.)',
    artist: '放課後CLIMAX GIRLS',
    unit: '放課後CLIMAX GIRLS',
    album: 'ECHOES 03',
    releaseDate: '2024/7/10',
    type: '组合曲',
    lyrics: '松井洋平、真崎エリカ',
    audioUrl: `${AUDIO_BASE_GROUP}/Migratory.Echoes.Houkago.CLIMAX.GIRLS.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/ECHOES.03.jpg`,
  },
  {
    id: 94,
    title: 'アルストロメリア',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'BRILLI@NT WING 05 アルストロメリア',
    releaseDate: '2018/10/3',
    type: '组合曲',
    lyrics: '鈴木静那',
    audioUrl: `${AUDIO_BASE_GROUP}/Alstroemeria.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/BRILLI@NT.WING.05.jpg`,
  },
  {
    id: 95,
    title: 'ハピリリ',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'BRILLI@NT WING 05 アルストロメリア',
    releaseDate: '2018/10/3',
    type: '组合曲',
    lyrics: 'SHOW',
    audioUrl: `${AUDIO_BASE_GROUP}/Hapiriri.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/BRILLI@NT.WING.05.jpg`,
  },
  {
    id: 96,
    title: 'Spread the Wings!!(アルストロメリア Ver.)',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'BRILLI@NT WING 05 アルストロメリア',
    releaseDate: '2018/10/3',
    type: '组合曲',
    lyrics: 'こだまさおり',
    audioUrl: `${AUDIO_BASE_GROUP}/Spread.the.Wings.Alstroemeria.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/BRILLI@NT.WING.05.jpg`,
  },
  {
    id: 97,
    title: 'Bloomy!',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'FR@GMENT WING 05',
    releaseDate: '2019/8/21',
    type: '组合曲',
    lyrics: '鈴木静那',
    audioUrl: `${AUDIO_BASE_GROUP}/Bloomy.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/FR@GMENT.WING.05.jpg`,
  },
  {
    id: 98,
    title: 'Love Addiction',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'FR@GMENT WING 05',
    releaseDate: '2019/8/21',
    type: '组合曲',
    lyrics: '家原正树 Jam9',
    audioUrl: `${AUDIO_BASE_GROUP}/Love.Addiction.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/FR@GMENT.WING.05.jpg`,
  },
  {
    id: 99,
    title: 'Ambitious Eve(アルストロメリア Ver.)',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'FR@GMENT WING 05',
    releaseDate: '2019/8/21',
    type: '组合曲',
    lyrics: '真崎エリカ',
    audioUrl: `${AUDIO_BASE_GROUP}/Ambitious.Eve.Alstroemeria.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/FR@GMENT.WING.05.jpg`,
  },
  {
    id: 100,
    title: 'ダブル·イフェクト',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'GR@DATE WING 05',
    releaseDate: '2020/12/9',
    type: '组合曲',
    lyrics: '鈴木静那',
    audioUrl: `${AUDIO_BASE_GROUP}/Double.Effect.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/GR@DATE.WING.05.jpg`,
  },
  {
    id: 101,
    title: 'Anniversary',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'GR@DATE WING 05',
    releaseDate: '2020/12/9',
    type: '组合曲',
    lyrics: '三好启太',
    audioUrl: `${AUDIO_BASE_GROUP}/Anniversary.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/GR@DATE.WING.05.jpg`,
  },
  {
    id: 102,
    title: 'シャイノグラフィ(アルストロメリア Ver.)',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'GR@DATE WING 05',
    releaseDate: '2020/12/9',
    type: '组合曲',
    lyrics: '古屋 真',
    audioUrl: `${AUDIO_BASE_GROUP}/Shainography.Alstroemeria.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/GR@DATE.WING.05.jpg`,
  },
  {
    id: 103,
    title: 'パステルカラー パスカラカラー',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'L@YERED WING 05',
    releaseDate: '2021/8/18',
    type: '组合曲',
    lyrics: '鈴木静那',
    audioUrl: `${AUDIO_BASE_GROUP}/Pastel.Color.Pasukara.Color.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.05.jpg`,
  },
  {
    id: 104,
    title: 'ラブ·ボナペティート',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'L@YERED WING 05',
    releaseDate: '2021/8/18',
    type: '组合曲',
    lyrics: '石井健太郎',
    audioUrl: `${AUDIO_BASE_GROUP}/Love.Buon.Appetito.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.05.jpg`,
  },
  {
    id: 105,
    title: 'Resonance+(アルストロメリア Ver.)',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'L@YERED WING 05',
    releaseDate: '2021/8/18',
    type: '组合曲',
    lyrics: '園田健太郎',
    audioUrl: `${AUDIO_BASE_GROUP}/Resonance.Plus.Alstroemeria.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.05.jpg`,
  },
  {
    id: 106,
    title: 'VERY BERRY LOVE',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'PANOR@MA WING 05',
    releaseDate: '2022/8/10',
    type: '组合曲',
    lyrics: '鈴木静那',
    audioUrl: `${AUDIO_BASE_GROUP}/VERY.BERRY.LOVE.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.05.jpg`,
  },
  {
    id: 107,
    title: 'Give me some more...',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'PANOR@MA WING 05',
    releaseDate: '2022/8/10',
    type: '组合曲',
    lyrics: '石黑剛、常楽寺澪',
    audioUrl: `${AUDIO_BASE_GROUP}/Give.me.some.more.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.05.jpg`,
  },
  {
    id: 108,
    title: '虹の行方(アルストロメリア Ver.)',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'PANOR@MA WING 05',
    releaseDate: '2022/8/10',
    type: '组合曲',
    lyrics: '古屋 真',
    audioUrl: `${AUDIO_BASE_GROUP}/Niji.no.Yukue.Alstroemeria.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.05.jpg`,
  },
  {
    id: 109,
    title: 'メッセージ',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'CANVAS 04',
    releaseDate: '2023/7/12',
    type: '组合曲',
    lyrics: '鈴木静那',
    audioUrl: `${AUDIO_BASE_GROUP}/Message.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.04.jpg`,
  },
  {
    id: 110,
    title: 'Love Letter',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'CANVAS 04',
    releaseDate: '2023/7/12',
    type: '组合曲',
    lyrics: '栁沼 廉',
    audioUrl: `${AUDIO_BASE_GROUP}/Love.Letter.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.04.jpg`,
  },
  {
    id: 111,
    title: 'グラデーション',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'CANVAS 04',
    releaseDate: '2023/7/12',
    type: '组合曲',
    lyrics: "YUU for YOU、Giz'Mo (from Jam9)",
    audioUrl: `${AUDIO_BASE_GROUP}/Gradation.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.04.jpg`,
  },
  {
    id: 112,
    title: '明日もBeautiful Day',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'Song for Prism 裸足じゃイラレナイ / 明日もBeautiful Day',
    releaseDate: '2024/1/24',
    type: '组合曲',
    lyrics: '鈴木静那',
    audioUrl: `${AUDIO_BASE_GROUP}/Ashita.mo.Beautiful.Day.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/Ashita.mo.Beautiful.Day.jpg`,
  },
  {
    id: 113,
    title: 'アスタラブビスタ',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'ECHOES 04',
    releaseDate: '2024/8/7',
    type: '组合曲',
    lyrics: '鈴木静那',
    audioUrl: `${AUDIO_BASE_GROUP}/Astalavvista.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/ECHOES.04.jpg`,
  },
  {
    id: 114,
    title: 'DAYDREAM LOVE',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'ECHOES 04',
    releaseDate: '2024/8/7',
    type: '组合曲',
    lyrics: '篠崎あやと、橘亮祐',
    audioUrl: `${AUDIO_BASE_GROUP}/DAYDREAM.LOVE.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/ECHOES.04.jpg`,
  },
  {
    id: 115,
    title: 'Migratory Echoes (アルストロメリアVer.)',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'ECHOES 04',
    releaseDate: '2024/8/7',
    type: '组合曲',
    lyrics: '松井洋平、鈴木静那',
    audioUrl: `${AUDIO_BASE_GROUP}/Migratory.Echoes.Alstroemeria.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/ECHOES.04.jpg`,
  },
  {
    id: 116,
    title: 'mellow mellow',
    artist: 'ALSTROEMERIA',
    unit: 'ALSTROEMERIA',
    album: 'Song for Prism After Run / mellow mellow',
    releaseDate: '2024/9/25',
    type: '组合曲',
    lyrics: '鈴木静那',
    audioUrl: `${AUDIO_BASE_GROUP}/mellow.mellow.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/mellow.mellow.jpg`,
  },
  {
    id: 117,
    title: 'Wandering Dream Chaser',
    artist: 'Straylight',
    unit: 'Straylight',
    album: 'FR@GMENT WING 06',
    releaseDate: '2019/9/11',
    type: '组合曲',
    lyrics: '下地悠',
    audioUrl: `${AUDIO_BASE_GROUP}/Wandering.Dream.Chaser.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/FR@GMENT.WING.06.jpg`,
  },
  {
    id: 118,
    title: 'Transcending The World',
    artist: 'Straylight',
    unit: 'Straylight',
    album: 'FR@GMENT WING 06',
    releaseDate: '2019/9/11',
    type: '组合曲',
    lyrics: 'R·O·N',
    audioUrl: `${AUDIO_BASE_GROUP}/Transcending.The.World.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/FR@GMENT.WING.06.jpg`,
  },
  {
    id: 119,
    title: 'Ambitious Eve(ストレイライト Ver.)',
    artist: 'Straylight',
    unit: 'Straylight',
    album: 'FR@GMENT WING 06',
    releaseDate: '2019/9/11',
    type: '组合曲',
    lyrics: '真崎エリカ',
    audioUrl: `${AUDIO_BASE_GROUP}/Ambitious.Eve.Straylight.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/FR@GMENT.WING.06.jpg`,
  },
  {
    id: 120,
    title: 'Hide & Attack',
    artist: 'Straylight',
    unit: 'Straylight',
    album: 'GR@DATE WING 06',
    releaseDate: '2020/8/19',
    type: '组合曲',
    lyrics: '下地悠',
    audioUrl: `${AUDIO_BASE_GROUP}/Hide.and.Attack.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/GR@DATE.WING.06.jpg`,
  },
  {
    id: 121,
    title: 'Destined Rival',
    artist: 'Straylight',
    unit: 'Straylight',
    album: 'GR@DATE WING 06',
    releaseDate: '2020/8/19',
    type: '组合曲',
    lyrics: '大西克巳',
    audioUrl: `${AUDIO_BASE_GROUP}/Destined.Rival.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/GR@DATE.WING.06.jpg`,
  },
  {
    id: 122,
    title: 'シャイノグラフィ(ストレイライト Ver.)',
    artist: 'Straylight',
    unit: 'Straylight',
    album: 'GR@DATE WING 06',
    releaseDate: '2020/8/19',
    type: '组合曲',
    lyrics: '古屋 真',
    audioUrl: `${AUDIO_BASE_GROUP}/Shainography.Straylight.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/GR@DATE.WING.06.jpg`,
  },
  {
    id: 123,
    title: 'Another Rampage',
    artist: 'Straylight',
    unit: 'Straylight',
    album: 'L@YERED WING 06',
    releaseDate: '2021/9/8',
    type: '组合曲',
    lyrics: '下地悠',
    audioUrl: `${AUDIO_BASE_GROUP}/Another.Rampage.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.06.jpg`,
  },
  {
    id: 124,
    title: 'Timeless Shooting Star',
    artist: 'Straylight',
    unit: 'Straylight',
    album: 'L@YERED WING 06',
    releaseDate: '2021/9/8',
    type: '组合曲',
    lyrics: '徳田光希',
    audioUrl: `${AUDIO_BASE_GROUP}/Timeless.Shooting.Star.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.06.jpg`,
  },
  {
    id: 125,
    title: 'Resonance+(ストレイライト Ver.)',
    artist: 'Straylight',
    unit: 'Straylight',
    album: 'L@YERED WING 06',
    releaseDate: '2021/9/8',
    type: '组合曲',
    lyrics: '園田健太郎',
    audioUrl: `${AUDIO_BASE_GROUP}/Resonance.Plus.Straylight.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.06.jpg`,
  },
  {
    id: 126,
    title: 'Tracing Defender',
    artist: 'Straylight',
    unit: 'Straylight',
    album: 'PANOR@MA WING 06',
    releaseDate: '2022/9/14',
    type: '组合曲',
    lyrics: '下地悠',
    audioUrl: `${AUDIO_BASE_GROUP}/Tracing.Defender.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.06.jpg`,
  },
  {
    id: 127,
    title: 'Overdrive Emotion',
    artist: 'Straylight',
    unit: 'Straylight',
    album: 'PANOR@MA WING 06',
    releaseDate: '2022/9/14',
    type: '组合曲',
    lyrics: '日比野裕史',
    audioUrl: `${AUDIO_BASE_GROUP}/Overdrive.Emotion.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.06.jpg`,
  },
  {
    id: 128,
    title: '虹の行方(ストレイライト Ver.)',
    artist: 'Straylight',
    unit: 'Straylight',
    album: 'PANOR@MA WING 06',
    releaseDate: '2022/9/14',
    type: '组合曲',
    lyrics: '古屋 真',
    audioUrl: `${AUDIO_BASE_GROUP}/Niji.no.Yukue.Straylight.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.06.jpg`,
  },
  {
    id: 129,
    title: 'Imitation Ghost',
    artist: 'Straylight',
    unit: 'Straylight',
    album: 'CANVAS 05',
    releaseDate: '2023/8/9',
    type: '组合曲',
    lyrics: '下地悠',
    audioUrl: `${AUDIO_BASE_GROUP}/Imitation.Ghost.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.05.jpg`,
  },
  {
    id: 130,
    title: 'Burn Burn',
    artist: 'Straylight',
    unit: 'Straylight',
    album: 'CANVAS 05',
    releaseDate: '2023/8/9',
    type: '组合曲',
    lyrics: 'YUU for You Ryosuke Matsuzaki',
    audioUrl: `${AUDIO_BASE_GROUP}/BURN.BURN.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.05.jpg`,
  },
  {
    id: 131,
    title: 'Start up Stand up',
    artist: 'Straylight',
    unit: 'Straylight',
    album: 'CANVAS 05',
    releaseDate: '2023/8/9',
    type: '组合曲',
    lyrics: 'amazuti',
    audioUrl: `${AUDIO_BASE_GROUP}/Start.up.Stand.up.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.05.jpg`,
  },
  {
    id: 132,
    title: 'LINKs',
    artist: 'Straylight',
    unit: 'Straylight',
    album: 'Song for Prism 時限式狂騒ワンダーランド / LINKs',
    releaseDate: '2024/7/24',
    type: '组合曲',
    lyrics: '下地悠',
    audioUrl: `${AUDIO_BASE_GROUP}/LINKs.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/LINKs.jpg`,
  },
  {
    id: 133,
    title: 'Cyber Parkour',
    artist: 'Straylight',
    unit: 'Straylight',
    album: 'ECHOES 05',
    releaseDate: '2024/9/11',
    type: '组合曲',
    lyrics: '下地悠',
    audioUrl: `${AUDIO_BASE_GROUP}/Cyber.Parkour.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/ECHOES.05.jpg`,
  },
  {
    id: 134,
    title: 'LIVE LIVE LIVE!',
    artist: 'Straylight',
    unit: 'Straylight',
    album: 'ECHOES 05',
    releaseDate: '2024/9/11',
    type: '组合曲',
    lyrics: '不详',
    audioUrl: `${AUDIO_BASE_GROUP}/LIVE.LIVE.LIVE.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/ECHOES.05.jpg`,
  },
  {
    id: 135,
    title: 'Migratory Echoes (ストレイライトVer.)',
    artist: 'Straylight',
    unit: 'Straylight',
    album: 'ECHOES 05',
    releaseDate: '2024/9/11',
    type: '组合曲',
    lyrics: '松井洋平、下地悠',
    audioUrl: `${AUDIO_BASE_GROUP}/Migratory.Echoes.Straylight.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/ECHOES.05.jpg`,
  },
  {
    id: 136,
    title: 'いつだって僕らは',
    artist: 'noctchill',
    unit: 'noctchill',
    album: 'GR@DATE WING 07',
    releaseDate: '2020/9/16',
    type: '组合曲',
    lyrics: '秋浦智裕(onetrap)',
    audioUrl: `${AUDIO_BASE_GROUP}/Itsudatte.Bokura.wa.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/GR@DATE.WING.07.jpg`,
  },
  {
    id: 137,
    title: 'あの花のように',
    artist: 'noctchill',
    unit: 'noctchill',
    album: 'GR@DATE WING 07',
    releaseDate: '2020/9/16',
    type: '组合曲',
    lyrics: 'きみコ',
    audioUrl: `${AUDIO_BASE_GROUP}/Ano.Hana.no.You.ni.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/GR@DATE.WING.07.jpg`,
  },
  {
    id: 138,
    title: 'シャイノグラフィ(ノクチル Ver.)',
    artist: 'noctchill',
    unit: 'noctchill',
    album: 'GR@DATE WING 07',
    releaseDate: '2020/9/16',
    type: '组合曲',
    lyrics: '古屋 真',
    audioUrl: `${AUDIO_BASE_GROUP}/Shainography.noctchill.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/GR@DATE.WING.07.jpg`,
  },
  {
    id: 139,
    title: '僕らだけの未来の空',
    artist: 'noctchill',
    unit: 'noctchill',
    album: 'L@YERED WING 07',
    releaseDate: '2021/10/13',
    type: '组合曲',
    lyrics: '秋浦智裕(onetrap)',
    audioUrl: `${AUDIO_BASE_GROUP}/Bokura.dake.no.Mirai.no.Sora.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.07.jpg`,
  },
  {
    id: 140,
    title: '今しかない瞬間を',
    artist: 'noctchill',
    unit: 'noctchill',
    album: 'L@YERED WING 07',
    releaseDate: '2021/10/13',
    type: '组合曲',
    lyrics: '本多友紀(Arte Refact)',
    audioUrl: `${AUDIO_BASE_GROUP}/Ima.shika.nai.Shunkan.wo.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.07.jpg`,
  },
  {
    id: 141,
    title: 'Resonance+(ノクチル Ver.)',
    artist: 'noctchill',
    unit: 'noctchill',
    album: 'L@YERED WING 07',
    releaseDate: '2021/10/13',
    type: '组合曲',
    lyrics: '園田健太郎',
    audioUrl: `${AUDIO_BASE_GROUP}/Resonance.Plus.noctchill.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.07.jpg`,
  },
  {
    id: 142,
    title: 'Catch the Breeze',
    artist: 'noctchill',
    unit: 'noctchill',
    album: 'PANOR@MA WING 07',
    releaseDate: '2022/10/12',
    type: '组合曲',
    lyrics: '秋浦智裕(onetrap)',
    audioUrl: `${AUDIO_BASE_GROUP}/Catch.the.Breeze.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.07.jpg`,
  },
  {
    id: 143,
    title: 'アスファルトを鳴らして',
    artist: 'noctchill',
    unit: 'noctchill',
    album: 'PANOR@MA WING 07',
    releaseDate: '2022/10/12',
    type: '组合曲',
    lyrics: '本多友紀(Arte Refact)',
    audioUrl: `${AUDIO_BASE_GROUP}/Asphalt.wo.Narashite.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.07.jpg`,
  },
  {
    id: 144,
    title: '虹の行方(ノクチル Ver.)',
    artist: 'noctchill',
    unit: 'noctchill',
    album: 'PANOR@MA WING 07',
    releaseDate: '2022/10/12',
    type: '组合曲',
    lyrics: '古屋 真',
    audioUrl: `${AUDIO_BASE_GROUP}/Niji.no.Yukue.noctchill.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.07.jpg`,
  },
  {
    id: 145,
    title: 'Reflection',
    artist: 'noctchill',
    unit: 'noctchill',
    album: 'CANVAS 06',
    releaseDate: '2023/9/13',
    type: '组合曲',
    lyrics: '秋浦智裕(onetrap)',
    audioUrl: `${AUDIO_BASE_GROUP}/Reflection.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.06.jpg`,
  },
  {
    id: 146,
    title: '夢が夢じゃなくなるその日まで',
    artist: 'noctchill',
    unit: 'noctchill',
    album: 'CANVAS 06',
    releaseDate: '2023/9/13',
    type: '组合曲',
    lyrics: '原田 篤(Arte Refact)',
    audioUrl: `${AUDIO_BASE_GROUP}/Yume.ga.Yume.janaku.naru.Sono.Hi.made.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.06.jpg`,
  },
  {
    id: 147,
    title: '青とオレンジ',
    artist: 'noctchill',
    unit: 'noctchill',
    album: 'CANVAS 06',
    releaseDate: '2023/9/13',
    type: '组合曲',
    lyrics: '涼木シンジ(KEYTONE)',
    audioUrl: `${AUDIO_BASE_GROUP}/Ao.to.Orange.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.06.jpg`,
  },
  {
    id: 148,
    title: '青空',
    artist: 'noctchill',
    unit: 'noctchill',
    album: 'Song for Prism ハナムケのハナタバ / 青空',
    releaseDate: '2024/4/3',
    type: '组合曲',
    lyrics: '秋浦智裕',
    audioUrl: `${AUDIO_BASE_GROUP}/Aozora.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/Aozora.jpg`,
  },
  {
    id: 149,
    title: 'いつかのキミへ',
    artist: 'noctchill',
    unit: 'noctchill',
    album: 'ECHOES 06',
    releaseDate: '2024/10/9',
    type: '组合曲',
    lyrics: '秋浦智裕',
    audioUrl: `${AUDIO_BASE_GROUP}/Itsuka.no.Kimi.e.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/ECHOES.06.jpg`,
  },
  {
    id: 150,
    title: '365日のストーリー',
    artist: 'noctchill',
    unit: 'noctchill',
    album: 'ECHOES 06',
    releaseDate: '2024/10/9',
    type: '组合曲',
    lyrics: '湯原聡史(KEYTONE)',
    audioUrl: `${AUDIO_BASE_GROUP}/365nichi.no.Story.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/ECHOES.06.jpg`,
  },
  {
    id: 151,
    title: 'Migratory Echoes (ノクチルVer.)',
    artist: 'noctchill',
    unit: 'noctchill',
    album: 'ECHOES 06',
    releaseDate: '2024/10/9',
    type: '组合曲',
    lyrics: '松井洋平、秋浦智裕',
    audioUrl: `${AUDIO_BASE_GROUP}/Migratory.Echoes.noctchill.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/ECHOES.06.jpg`,
  },
  {
    id: 152,
    title: 'グッバイ',
    artist: 'noctchill',
    unit: 'noctchill',
    album: 'Song for Prism Heads or Tails / グッバイ',
    releaseDate: '2024/11/27',
    type: '组合曲',
    lyrics: '秋浦智裕',
    audioUrl: `${AUDIO_BASE_GROUP}/Goodbye.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/Goodbye.jpg`,
  },
  {
    id: 153,
    title: 'OH MY GOD',
    artist: 'SHHis',
    unit: 'SHHis',
    album: 'L@YERED WING 08',
    releaseDate: '2021/11/10',
    type: '组合曲',
    lyrics: 'Co-sho',
    audioUrl: `${AUDIO_BASE_GROUP}/OH.MY.GOD.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.08.jpg`,
  },
  {
    id: 154,
    title: 'Fly and Fly',
    artist: 'SHHis',
    unit: 'SHHis',
    album: 'L@YERED WING 08',
    releaseDate: '2021/11/10',
    type: '组合曲',
    lyrics: 'Kohei Yokono、小久保祐希、JUNE',
    audioUrl: `${AUDIO_BASE_GROUP}/Fly.and.Fly.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.08.jpg`,
  },
  {
    id: 155,
    title: 'Resonance+(シーズ Ver.)',
    artist: 'SHHis',
    unit: 'SHHis',
    album: 'L@YERED WING 08',
    releaseDate: '2021/11/10',
    type: '组合曲',
    lyrics: '園田健太郎',
    audioUrl: `${AUDIO_BASE_GROUP}/Resonance.Plus.SHHis.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.08.jpg`,
  },
  {
    id: 156,
    title: 'Fashionable',
    artist: 'SHHis',
    unit: 'SHHis',
    album: 'PANOR@MA WING 08',
    releaseDate: '2022/11/16',
    type: '组合曲',
    lyrics: 'Co-sho',
    audioUrl: `${AUDIO_BASE_GROUP}/Fashionable.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.08.jpg`,
  },
  {
    id: 157,
    title: 'Bouncy Girl',
    artist: 'SHHis',
    unit: 'SHHis',
    album: 'PANOR@MA WING 08',
    releaseDate: '2022/11/16',
    type: '组合曲',
    lyrics: '石黑剛、常楽寺澪',
    audioUrl: `${AUDIO_BASE_GROUP}/Bouncy.Girl.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.08.jpg`,
  },
  {
    id: 158,
    title: '虹の行方(シーズ Ver.)',
    artist: 'SHHis',
    unit: 'SHHis',
    album: 'PANOR@MA WING 08',
    releaseDate: '2022/11/16',
    type: '组合曲',
    lyrics: '古屋 真',
    audioUrl: `${AUDIO_BASE_GROUP}/Niji.no.Yukue.SHHis.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.08.jpg`,
  },
  {
    id: 159,
    title: 'Forbidden Paradise',
    artist: 'SHHis',
    unit: 'SHHis',
    album: 'CANVAS 07',
    releaseDate: '2023/10/11',
    type: '组合曲',
    lyrics: 'Co-sho',
    audioUrl: `${AUDIO_BASE_GROUP}/Forbidden.Paradise.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.07.jpg`,
  },
  {
    id: 160,
    title: 'SWEETEST BITE',
    artist: 'SHHis',
    unit: 'SHHis',
    album: 'CANVAS 07',
    releaseDate: '2023/10/11',
    type: '组合曲',
    lyrics: '小久保祐希、YAGO',
    audioUrl: `${AUDIO_BASE_GROUP}/SWEETEST.BITE.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.07.jpg`,
  },
  {
    id: 161,
    title: 'White Story',
    artist: 'SHHis',
    unit: 'SHHis',
    album: 'CANVAS 07',
    releaseDate: '2023/10/11',
    type: '组合曲',
    lyrics: 'YUU for YOU、常楽寺澪',
    audioUrl: `${AUDIO_BASE_GROUP}/White.Story.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.07.jpg`,
  },
  {
    id: 162,
    title: 'Happier',
    artist: 'SHHis',
    unit: 'SHHis',
    album: 'Song for Prism Happier / 枕木の歌',
    releaseDate: '2024/5/22',
    type: '组合曲',
    lyrics: 'Co-sho',
    audioUrl: `${AUDIO_BASE_GROUP}/Happier.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/Happier.jpg`,
  },
  {
    id: 163,
    title: 'After Run',
    artist: 'SHHis',
    unit: 'SHHis',
    album: 'Song for Prism After Run / mellow mellow',
    releaseDate: '2024/9/25',
    type: '组合曲',
    lyrics: 'Co-sho',
    audioUrl: `${AUDIO_BASE_GROUP}/After.Run.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/After.Run.jpg`,
  },
  {
    id: 164,
    title: 'Monochromatic',
    artist: 'SHHis',
    unit: 'SHHis',
    album: 'ECHOES 07',
    releaseDate: '2024/11/13',
    type: '组合曲',
    lyrics: 'Co-sho',
    audioUrl: `${AUDIO_BASE_GROUP}/Monochromatic.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/ECHOES.07.jpg`,
  },
  {
    id: 165,
    title: 'Snowflake',
    artist: 'SHHis',
    unit: 'SHHis',
    album: 'ECHOES 07',
    releaseDate: '2024/11/13',
    type: '组合曲',
    lyrics: '小久保祐希、石黑剛、YHEL、YHEL',
    audioUrl: `${AUDIO_BASE_GROUP}/Snowflake.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/ECHOES.07.jpg`,
  },
  {
    id: 166,
    title: 'Migratory Echoes (シーズVer.)',
    artist: 'SHHis',
    unit: 'SHHis',
    album: 'ECHOES 07',
    releaseDate: '2024/11/13',
    type: '组合曲',
    lyrics: '松井洋平、Co-sho',
    audioUrl: `${AUDIO_BASE_GROUP}/Migratory.Echoes.SHHis.Ver.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/ECHOES.07.jpg`,
  },
  {
    id: 167,
    title: '無自覚アプリオリ',
    artist: 'CoMETIK',
    unit: 'CoMETIK',
    album: 'CANVAS 08',
    releaseDate: '2023/11/8',
    type: '组合曲',
    lyrics: '出口 遼(KEYTONE)',
    audioUrl: `${AUDIO_BASE_GROUP}/Mujikaku.A.Priori.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.08.jpg`,
  },
  {
    id: 168,
    title: 'くだらないや',
    artist: 'CoMETIK',
    unit: 'CoMETIK',
    album: 'CANVAS 08',
    releaseDate: '2023/11/8',
    type: '组合曲',
    lyrics: '篠崎あやと、橘 亮祐',
    audioUrl: `${AUDIO_BASE_GROUP}/Kudaranaiya.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.08.jpg`,
  },
  {
    id: 169,
    title: '平行線の美学',
    artist: 'CoMETIK',
    unit: 'CoMETIK',
    album: 'CANVAS 08',
    releaseDate: '2023/11/8',
    type: '组合曲',
    lyrics: '園田健太郎',
    audioUrl: `${AUDIO_BASE_GROUP}/Heikousen.no.Bigaku.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/CANVAS.08.jpg`,
  },
  {
    id: 170,
    title: 'ハナムケのハナタバ',
    artist: 'CoMETIK',
    unit: 'CoMETIK',
    album: 'Song for Prism ハナムケのハナタバ / 青空',
    releaseDate: '2024/4/3',
    type: '组合曲',
    lyrics: '園田健太郎',
    audioUrl: `${AUDIO_BASE_GROUP}/Hanamuke.no.Hanataba.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/Hanamuke.no.Hanataba.jpg`,
  },
  {
    id: 171,
    title: 'Heads or Tails？',
    artist: 'CoMETIK',
    unit: 'CoMETIK',
    album: 'Song for Prism Heads or Tails / グッバイ',
    releaseDate: '2024/11/27',
    type: '组合曲',
    lyrics: 'Soflan Daichi',
    audioUrl: `${AUDIO_BASE_GROUP}/Heads.or.Tails.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/Heads.or.Tails.jpg`,
  },

  // ==================== 全体曲 (23首) ====================
  {
    id: 233,
    title: 'Spread the Wings!!',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'BRILLI@NT WING 01 Spread the Wings!!',
    releaseDate: '2018/6/6',
    type: '全体曲',
    lyrics: 'こだまさおり',
    music: '山口朗彦',
    arrangement: '山口朗彦',
    audioUrl: `${AUDIO_BASE_ALL}/Spread.the.Wings.flac`,
    albumCover: `${ALBUM_COVER_BASE}/BRILLI@NT.WING.01.Spread.the.Wings.jpg`,
    notes: '第一年度16人全体曲',
  },
  {
    id: 234,
    title: 'Multicolored Sky',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'BRILLI@NT WING 01 Spread the Wings!!',
    releaseDate: '2018/6/6',
    type: '全体曲',
    lyrics: '松井洋平',
    music: '高田暁',
    audioUrl: `${AUDIO_BASE_ALL}/Multicolored.Sky.flac`,
    albumCover: `${ALBUM_COVER_BASE}/BRILLI@NT.WING.01.Spread.the.Wings.jpg`,
  },
  {
    id: 235,
    title: 'SNOW FLAKES MEMORIES',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'SE@SONAL WINTER',
    releaseDate: '2018/12/19',
    type: '全体曲',
    lyrics: '松井洋平',
    music: '中野領太',
    audioUrl: `${AUDIO_BASE_ALL}/SNOW.FLAKES.MEMORIES.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/SE@SONAL.WINTER.jpg`,
    notes: '18年圣诞节单曲',
  },
  {
    id: 236,
    title: "Let's get a chance",
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'SE@SONAL WINTER',
    releaseDate: '2018/12/19',
    type: '全体曲',
    lyrics: '渡辺拓也',
    music: '住谷翔平',
    audioUrl: `${AUDIO_BASE_ALL}/Lets.get.a.chance.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/SE@SONAL.WINTER.jpg`,
  },
  {
    id: 237,
    title: 'Ambitious Eve',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'FR@GMENT WING 01',
    releaseDate: '2019/4/10',
    type: '全体曲',
    lyrics: '真崎エリカ',
    music: '山田智和',
    arrangement: '住谷翔平',
    audioUrl: `${AUDIO_BASE_ALL}/Ambitious.Eve.flac`,
    albumCover: `${ALBUM_COVER_BASE}/FR@GMENT.WING.01.jpg`,
    notes: '第二年度19人全体曲 新组合Straylight加入',
  },
  {
    id: 238,
    title: 'いつか Shiny Days',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'FR@GMENT WING 01',
    releaseDate: '2019/4/10',
    type: '全体曲',
    lyrics: '鈴木静那',
    music: '長谷川智樹',
    audioUrl: `${AUDIO_BASE_ALL}/Shiny.Days.flac`,
    albumCover: `${ALBUM_COVER_BASE}/FR@GMENT.WING.01.jpg`,
  },
  {
    id: 239,
    title: 'FUTURITY SMILE',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'FUTURITY SMILE',
    releaseDate: '2019/12/18',
    type: '全体曲',
    lyrics: '前田甘露',
    music: "ArmySlick Giz'Mo",
    arrangement: 'ArmySlick',
    audioUrl: `${AUDIO_BASE_ALL}/FUTURITY.SMILE.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/FUTURITY.SMILE.jpg`,
    notes: '19年冬季单曲',
  },
  {
    id: 240,
    title: 'Spread the Wings!! -19 colors-',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'FUTURITY SMILE',
    releaseDate: '2019/12/18',
    type: '全体曲',
    lyrics: 'こだまさおり',
    music: '山口朗彦',
    audioUrl: `${AUDIO_BASE_ALL}/Spread.the.Wings.19.colors.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/FUTURITY.SMILE.jpg`,
  },
  {
    id: 241,
    title: 'SWEET♡STEP',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'SWEET♡STEP',
    releaseDate: '2020/2/12',
    type: '全体曲',
    lyrics: '深川琴美',
    music: 'NA.ZU.NA',
    audioUrl: `${AUDIO_BASE_ALL}/SWEET.STEP.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/SWEET♡STEP.jpg`,
    notes: '20年情人节单曲',
  },
  {
    id: 242,
    title: 'Multicolored Sky -19 colors-',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'SWEET♡STEP',
    releaseDate: '2020/2/12',
    type: '全体曲',
    lyrics: '松井洋平',
    music: '高田暁',
    audioUrl: `${AUDIO_BASE_ALL}/Multicolored.Sky.19.colors.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/SWEET♡STEP.jpg`,
  },
  {
    id: 243,
    title: 'シャイノグラフィ',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'GR@DATE WING 01',
    releaseDate: '2020/4/8',
    type: '全体曲',
    lyrics: '古屋真',
    music: 'ヒゲドライバー',
    audioUrl: `${AUDIO_BASE_ALL}/Shainography.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/GR@DATE.WING.01.jpg`,
    notes: '第三年度23人全体曲 新组合noctchill加入',
  },
  {
    id: 244,
    title: 'Dye the sky.',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'GR@DATE WING 01',
    releaseDate: '2020/4/8',
    type: '全体曲',
    lyrics: '乌屋茶房',
    music: 'ヒゲドライバー',
    audioUrl: `${AUDIO_BASE_ALL}/Dye.the.sky.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/GR@DATE.WING.01.jpg`,
  },
  {
    id: 245,
    title: 'Resonance⁺',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'L@YERED WING 01',
    releaseDate: '2021/4/14',
    type: '全体曲',
    lyrics: '園田健太郎',
    audioUrl: `${AUDIO_BASE_ALL}/Resonance.Plus.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.01.jpg`,
    notes: '第四年度25人全体曲 新组合SHHis加入',
  },
  {
    id: 246,
    title: 'Color Days',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'L@YERED WING 01',
    releaseDate: '2021/4/14',
    type: '全体曲',
    lyrics: 'Co-sho',
    music: '家原正樹、小久保祐希、YHANAEL',
    arrangement: 'YUU for YOU',
    audioUrl: `${AUDIO_BASE_ALL}/Color.Days.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/L@YERED.WING.01.jpg`,
  },
  {
    id: 247,
    title: '虹の行方',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'PANOR@MA WING 01',
    releaseDate: '2022/4/13',
    type: '全体曲',
    lyrics: '古屋真',
    music: '三好啓太',
    audioUrl: `${AUDIO_BASE_ALL}/Niji.no.Yukue.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.01.jpg`,
    notes: '第五年度25人全体曲',
  },
  {
    id: 248,
    title: 'Daybreak Age',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'PANOR@MA WING 01',
    releaseDate: '2022/4/13',
    type: '全体曲',
    lyrics: '真崎エリカ',
    music: '桑原佑介',
    audioUrl: `${AUDIO_BASE_ALL}/Daybreak.Age.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/PANOR@MA.WING.01.jpg`,
  },
  {
    id: 249,
    title: '星の声',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'Song for Prism 星の声',
    releaseDate: '2023/10/18',
    type: '全体曲',
    lyrics: '秋浦智裕',
    audioUrl: `${AUDIO_BASE_ALL}/Hoshi.no.Koe.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/Hoshi.no.Koe.jpg`,
    notes: '音游主题曲 新组合CoMETIK加入',
  },
  {
    id: 250,
    title: 'ツバサグラビティ',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'ツバサグラビティ',
    releaseDate: '2024/4/10',
    type: '全体曲',
    lyrics: 'こだまさおり',
    music: '山口朗彦',
    audioUrl: `${AUDIO_BASE_ALL}/Tsubasa.Gravity.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/Tsubasa.Gravity.jpg`,
    notes: '动画第一季片头曲 前4组合16人',
  },
  {
    id: 251,
    title: 'プリズムフレア',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'Powerless/プリズムフレア',
    releaseDate: '2024/10/9',
    type: '全体曲',
    lyrics: 'こだまさおり',
    music: 'ヒゲドライバー',
    audioUrl: `${AUDIO_BASE_ALL}/Prism.Flare.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/Prism.Flare.jpg`,
    notes: '动画第二季片头曲 前5组合19人',
  },
  {
    id: 252,
    title: 'Poison Berry Daughters',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'Happy Surprise Trick!',
    releaseDate: '2024/10/30',
    type: '全体曲',
    lyrics: '古屋 真',
    music: '小久保祐希、石黑剛',
    arrangement: '佐々倉有吾',
    audioUrl: `${AUDIO_BASE_ALL}/Poison.Berry.Daughters.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/Happy.Surprise.Trick.jpg`,
    notes: '动画第二季万圣夜全体曲',
  },
  {
    id: 253,
    title: "C'mon! Join Us",
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'Song for Prism',
    releaseDate: '2024/11/20',
    type: '全体曲',
    lyrics: '下地悠',
    music: '小久保祐希、YAGO、YHEL',
    arrangement: 'YUU for YOU、YAGO',
    audioUrl: `${AUDIO_BASE_ALL}/Cmon.Join.Us.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/Song.for.Prism.jpg`,
    notes: '音游一周年专辑',
  },
  {
    id: 254,
    title: '愛なView',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'Song for Prism',
    releaseDate: '2024/11/20',
    type: '全体曲',
    lyrics: '渡邊亜希子',
    music: '原田雄一、奥野 涼',
    arrangement: '原田雄一',
    audioUrl: `${AUDIO_BASE_ALL}/Ai.na.View.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/Song.for.Prism.jpg`,
  },
  {
    id: 255,
    title: 'サマーサマーオーシャンパーリィバケーション',
    artist: 'シャイニーカラーズ',
    unit: '全体曲',
    album: 'Song for Prism',
    releaseDate: '2024/11/20',
    type: '全体曲',
    lyrics: '古屋真',
    music: 'NA.ZU.NA',
    audioUrl: `${AUDIO_BASE_ALL}/Summer.Summer.Ocean.Party.Vacation.mp3`,
    albumCover: `${ALBUM_COVER_BASE}/Song.for.Prism.jpg`,
  },
];
