// 歌曲数据 - 自动生成于 2025-12-12
// 支持CDN降级机制：主链接超时后使用镜像加速

// ==================== CDN配置 ====================
// 镜像服务（用于中国大陆加速）
const CDN_MIRROR = 'https://gh.con.sh/'; // 备选: https://ghfast.top/ 或 https://gh-proxy.com/
// GitHub Release URL - 注意tag名已URL编码
const GITHUB_RELEASE_BASE =
  'https://github.com/2426269/shinycolors-assets-cdn/releases/download/%E6%AD%8C%E6%9B%B2%E5%92%8C%E6%AD%8C%E8%AF%8D';

// ==================== 类型定义 ====================
export interface Song {
  id: number;
  title: string;
  artist: string;
  character?: string; // 角色名（个人曲专用）
  voiceActor?: string; // 声优名
  type: '个人曲' | '组合曲' | '团体曲' | '全体曲';
  unit?: string; // 所属组合
  audioUrl: string; // 主音频URL
  audioUrlFallback?: string; // 备用镜像URL
  lyricsUrl?: string; // 歌词URL
  lyricsUrlFallback?: string; // 备用歌词URL
}

// ==================== 歌曲列表 ====================
export const songs: Song[] = [
  {
    id: 1,
    title: '1_3',
    artist: '川口莉奈',
    character: '斑鳩ルカ',
    voiceActor: '川口莉奈',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/1_3.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/1_3.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/1_3.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/1_3.lrc`,
  },
  {
    id: 2,
    title: 'Damascus Cocktail',
    artist: '涼本あきほ',
    character: '有栖川夏葉',
    voiceActor: '涼本あきほ',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Damascus.Cocktail.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Damascus.Cocktail.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Damascus.Cocktail.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Damascus.Cocktail.lrc`,
  },
  {
    id: 3,
    title: 'Darling you!',
    artist: '芝崎典子',
    character: '桑山千雪',
    voiceActor: '芝崎典子',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Darling.you.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Darling.you.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Darling.you!.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Darling.you!.lrc`,
  },
  {
    id: 4,
    title: 'Going my way',
    artist: '北原沙弥香',
    character: '和泉愛依',
    voiceActor: '北原沙弥香',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Going.my.way.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Going.my.way.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Going.my.way.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Going.my.way.lrc`,
  },
  {
    id: 5,
    title: 'HAREBARE!!',
    artist: '峯田茉優',
    character: '八宮めぐる',
    voiceActor: '峯田茉優',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/HAREBARE.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/HAREBARE.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/HAREBARE!!.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/HAREBARE!!.lrc`,
  },
  {
    id: 6,
    title: 'Look up to the sky',
    artist: '山根綺',
    character: '緋田美琴',
    voiceActor: '山根綺',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Look.up.to.the.sky.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Look.up.to.the.sky.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Look.up.to.the.sky.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Look.up.to.the.sky.lrc`,
  },
  {
    id: 7,
    title: 'SOS',
    artist: '幸村恵理',
    character: '黛冬優子',
    voiceActor: '幸村恵理',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/SOS.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/SOS.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/SOS.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/SOS.lrc`,
  },
  {
    id: 8,
    title: 'statice',
    artist: '和久井優',
    character: '浅倉透',
    voiceActor: '和久井優',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/statice.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/statice.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/statice.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/statice.lrc`,
  },
  {
    id: 9,
    title: 'Sweet Memories',
    artist: '黒木ほの香',
    character: '大崎甘奈',
    voiceActor: '黒木ほの香',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Sweet.Memories.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Sweet.Memories.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Sweet.Memories.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Sweet.Memories.lrc`,
  },
  {
    id: 10,
    title: 'あおぞらサイダー',
    artist: '岡咲美保',
    character: '市川雛菜',
    voiceActor: '岡咲美保',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/A.Ozo.Ra.Saida.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/A.Ozo.Ra.Saida.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/A.Ozo.Ra.Saidā.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/A.Ozo.Ra.Saidā.lrc`,
  },
  {
    id: 11,
    title: 'ありったけの輝きで',
    artist: '関根瞳',
    character: '櫻木真乃',
    voiceActor: '関根瞳',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Arittake.No.Kagayaki.De.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Arittake.No.Kagayaki.De.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Arittake.No.Kagayaki.De.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Arittake.No.Kagayaki.De.lrc`,
  },
  {
    id: 12,
    title: 'また明日',
    artist: '前川涼子',
    character: '大崎甜花',
    voiceActor: '前川涼子',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Mata.Ashita.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Mata.Ashita.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Mata.Ashita.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Mata.Ashita.lrc`,
  },
  {
    id: 13,
    title: 'わたしの主人公はわたしだから！',
    artist: '田嶌紗蘭',
    character: '福丸小糸',
    voiceActor: '田嶌紗蘭',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Watashi.No.Shujinko.Wa.Watashi.Da.Kara.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Watashi.No.Shujinko.Wa.Watashi.Da.Kara.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Watashi.No.Shujinkō.Wa.Watashi.Da.Kara.!.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Watashi.No.Shujinkō.Wa.Watashi.Da.Kara.!.lrc`,
  },
  {
    id: 14,
    title: 'アポイント・シグナル',
    artist: '礒部花凜',
    character: '月岡恋鐘',
    voiceActor: '礒部花凜',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Apointo.Shigunaru.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Apointo.Shigunaru.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Apointo.Shigunaru.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Apointo.Shigunaru.lrc`,
  },
  {
    id: 15,
    title: 'スローモーション',
    artist: '近藤玲奈',
    character: '風野灯織',
    voiceActor: '近藤玲奈',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Suromoshon.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Suromoshon.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Surōmōshon.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Surōmōshon.lrc`,
  },
  {
    id: 16,
    title: 'チョコデート・サンデー',
    artist: '白石晴香',
    character: '園田智代子',
    voiceActor: '白石晴香',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Choko.Deto.Sande.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Choko.Deto.Sande.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Choko.Dēto.Sandē.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Choko.Dēto.Sandē.lrc`,
  },
  {
    id: 17,
    title: 'デビ太郎のうた',
    artist: '前川涼子',
    character: '大崎甜花',
    voiceActor: '前川涼子',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Debi.Taro.No.Uta.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Debi.Taro.No.Uta.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Debi.Tarō.No.Uta.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Debi.Tarō.No.Uta.lrc`,
  },
  {
    id: 18,
    title: 'ハナマルバッジ',
    artist: '河野ひより',
    character: '小宮果穂',
    voiceActor: '河野ひより',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Hanamarubajji.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hanamarubajji.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Hanamarubajji.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hanamarubajji.lrc`,
  },
  {
    id: 19,
    title: 'フェアリー・ガール',
    artist: '紫月杏朱彩',
    character: '七草にちか',
    voiceActor: '紫月杏朱彩',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Feari.Garu.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Feari.Garu.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Fearī.Gāru.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Fearī.Gāru.lrc`,
  },
  {
    id: 20,
    title: 'プラスチック・アンブレラ (2022 Ver.)',
    artist: '希水しお',
    character: '三峰結華',
    voiceActor: '希水しお',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Purasuchikku.Amburera.2022.Ver.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Purasuchikku.Amburera.2022.Ver.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Purasuchikku.Amburera.2022.Ver.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Purasuchikku.Amburera.2022.Ver.lrc`,
  },
  {
    id: 21,
    title: '千夜アリア',
    artist: '八巻アンナ',
    character: '白瀬咲耶',
    voiceActor: '八巻アンナ',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Sen.Ya.Aria.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Sen.Ya.Aria.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Sen.Ya.Aria.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Sen.Ya.Aria.lrc`,
  },
  {
    id: 22,
    title: '夢模様キャンバス',
    artist: '小澤麗那',
    character: '郁田はるき',
    voiceActor: '小澤麗那',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Yume.Moyo.Kyambasu.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Yume.Moyo.Kyambasu.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Yume.Moyō.Kyambasu.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Yume.Moyō.Kyambasu.lrc`,
  },
  {
    id: 23,
    title: '夢見鳥',
    artist: '土屋李央',
    character: '樋口円香',
    voiceActor: '土屋李央',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Yumemi.Tori.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Yumemi.Tori.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Yumemi.Tori.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Yumemi.Tori.lrc`,
  },
  {
    id: 24,
    title: '常咲の庭',
    artist: '丸岡和佳奈',
    character: '杜野凛世',
    voiceActor: '丸岡和佳奈',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Tsune.Saki.No.Niwa.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Tsune.Saki.No.Niwa.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Tsune.Saki.No.Niwa.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Tsune.Saki.No.Niwa.lrc`,
  },
  {
    id: 25,
    title: '星をめざして',
    artist: '田中有紀',
    character: '芹沢あさひ',
    voiceActor: '田中有紀',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Hoshi.O.Mezashi.Te.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hoshi.O.Mezashi.Te.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Hoshi.O.Mezashi.Te.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hoshi.O.Mezashi.Te.lrc`,
  },
  {
    id: 26,
    title: '無垢',
    artist: '三川華月',
    character: '鈴木羽那',
    voiceActor: '三川華月',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Muku.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Muku.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Muku.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Muku.lrc`,
  },
  {
    id: 27,
    title: '神様は死んだ、って',
    artist: '川口莉奈',
    character: '斑鳩ルカ',
    voiceActor: '川口莉奈',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Kamisama.Wa.Shin.Da.Tte.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Kamisama.Wa.Shin.Da.Tte.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Kamisama.Wa.Shin.Da.,.Tte.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Kamisama.Wa.Shin.Da.,.Tte.lrc`,
  },
  {
    id: 28,
    title: '絶対正義 EVERY DAY',
    artist: '河野ひより',
    character: '小宮果穂',
    voiceActor: '河野ひより',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Zettai.Seigi.EVERY.DAY.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Zettai.Seigi.EVERY.DAY.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Zettai.Seigi.EVERY.DAY.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Zettai.Seigi.EVERY.DAY.lrc`,
  },
  {
    id: 29,
    title: '誰ソ彼アイデンティティー',
    artist: '菅沼千紗',
    character: '田中摩美々',
    voiceActor: '菅沼千紗',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Dare.So.Kare.Aidentiti.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Dare.So.Kare.Aidentiti.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Dare.So.Kare.Aidentitī.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Dare.So.Kare.Aidentitī.lrc`,
  },
  {
    id: 30,
    title: '過純性ブリーチ',
    artist: '永井真里子',
    character: '西城樹里',
    voiceActor: '永井真里子',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Ka.Jun.Sei.Burichi.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Ka.Jun.Sei.Burichi.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Ka.Jun.Sei.Burīchi.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Ka.Jun.Sei.Burīchi.lrc`,
  },
  {
    id: 31,
    title: '雪・月・風・花',
    artist: '結名美月',
    character: '幽谷霧子',
    voiceActor: '結名美月',
    type: '个人曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Yuki.Tsuki.Fu.Hana.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Yuki.Tsuki.Fu.Hana.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Yuki.Tsuki.Fū.Hana.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Yuki.Tsuki.Fū.Hana.lrc`,
  },
  {
    id: 32,
    title: 'Ambitious Eve -28 colors-',
    artist: 'Shiny Colors',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/Ambitious.Eve.-28.colors-.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Ambitious.Eve.-28.colors-.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Ambitious.Eve.-28.colors-.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Ambitious.Eve.-28.colors-.lrc`,
  },
  {
    id: 33,
    title: "C'mon! Join Us",
    artist: 'Shiny Colors',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/C.mon.Join.Us.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/C.mon.Join.Us.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/C'mon!.Join.Us.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/C'mon!.Join.Us.lrc`,
  },
  {
    id: 34,
    title: 'Color Days -28 colors-',
    artist: 'Shiny Colors',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/Color.Days.-28.colors-.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Color.Days.-28.colors-.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Color.Days.-28.colors-.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Color.Days.-28.colors-.lrc`,
  },
  {
    id: 35,
    title: 'Daybreak Age -28 colors-',
    artist: 'Shiny Colors',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/Daybreak.Age.-28.colors-.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Daybreak.Age.-28.colors-.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Daybreak.Age.-28.colors-.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Daybreak.Age.-28.colors-.lrc`,
  },
  {
    id: 36,
    title: 'Dye the sky. -28 colors-',
    artist: 'Shiny Colors',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/Dye.the.sky.-28.colors-.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Dye.the.sky.-28.colors-.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Dye.the.sky.-28.colors-.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Dye.the.sky.-28.colors-.lrc`,
  },
  {
    id: 37,
    title: 'FUTURITY SMILE -28 colors-',
    artist: 'Shiny Colors',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/FUTURITY.SMILE.-28.colors-.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/FUTURITY.SMILE.-28.colors-.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/FUTURITY.SMILE.-28.colors-.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/FUTURITY.SMILE.-28.colors-.lrc`,
  },
  {
    id: 38,
    title: "Let's get a chance -28 colors-",
    artist: 'Shiny Colors',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/Let.s.get.a.chance.-28.colors-.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Let.s.get.a.chance.-28.colors-.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Let's.get.a.chance.-28.colors-.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Let's.get.a.chance.-28.colors-.lrc`,
  },
  {
    id: 39,
    title: 'Migratory Echoes',
    artist: 'Shiny Colors',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/Migratory.Echoes.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Migratory.Echoes.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Migratory.Echoes.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Migratory.Echoes.lrc`,
  },
  {
    id: 40,
    title: 'Multicolored Sky -28 colors-',
    artist: 'Shiny Colors',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/Multicolored.Sky.-28.colors-.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Multicolored.Sky.-28.colors-.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Multicolored.Sky.-28.colors-.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Multicolored.Sky.-28.colors-.lrc`,
  },
  {
    id: 41,
    title: 'Resonance⁺ -28 colors-',
    artist: 'Shiny Colors',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/ResonancePlus.-28.colors-.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/ResonancePlus.-28.colors-.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/ResonancePlus.-28.colors-.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/ResonancePlus.-28.colors-.lrc`,
  },
  {
    id: 42,
    title: 'Shiny Stories',
    artist: 'Shiny Colors,関根瞳,紫月杏朱彩,川口莉奈',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/Shiny.Stories.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Shiny.Stories.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Shiny.Stories.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Shiny.Stories.lrc`,
  },
  {
    id: 43,
    title: 'SNOW FLAKES MEMORIES -28 colors-',
    artist: 'Shiny Colors',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/SNOW.FLAKES.MEMORIES.-28.colors-.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/SNOW.FLAKES.MEMORIES.-28.colors-.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/SNOW.FLAKES.MEMORIES.-28.colors-.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/SNOW.FLAKES.MEMORIES.-28.colors-.lrc`,
  },
  {
    id: 44,
    title: 'Spread the Wings!! -28 colors-',
    artist: 'Shiny Colors',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/Spread.the.Wings.-28.colors-.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Spread.the.Wings.-28.colors-.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Spread.the.Wings!!.-28.colors-.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Spread.the.Wings!!.-28.colors-.lrc`,
  },
  {
    id: 45,
    title: 'SWEET♡STEP -28 colors-',
    artist: 'Shiny Colors',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/SWEETSTEP.-28.colors-.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/SWEETSTEP.-28.colors-.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/SWEETSTEP.-28.colors-.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/SWEETSTEP.-28.colors-.lrc`,
  },
  {
    id: 46,
    title: 'いつか Shiny Days -28 colors-',
    artist: 'Shiny Colors',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/Itsuka.Shiny.Days.-.28.Colors.-.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Itsuka.Shiny.Days.-.28.Colors.-.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Itsuka.Shiny.Days.-.28.Colors.-.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Itsuka.Shiny.Days.-.28.Colors.-.lrc`,
  },
  {
    id: 47,
    title: 'シャイノグラフィ -28 colors-',
    artist: 'Shiny Colors',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/Shainogurafi.-.28.Colors.-.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Shainogurafi.-.28.Colors.-.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Shainogurafi.-.28.Colors.-.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Shainogurafi.-.28.Colors.-.lrc`,
  },
  {
    id: 48,
    title: 'ツバサグラビティ',
    artist: 'Shiny Colors',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/Tsubasagurabiti.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Tsubasagurabiti.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Tsubasagurabiti.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Tsubasagurabiti.lrc`,
  },
  {
    id: 49,
    title: 'プリズムフレア -25 colors-',
    artist: 'Shiny Colors',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/Purizumu.Furea.-.25.Colors.-.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Purizumu.Furea.-.25.Colors.-.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Purizumu.Furea.-.25.Colors.-.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Purizumu.Furea.-.25.Colors.-.lrc`,
  },
  {
    id: 50,
    title: '愛なView',
    artist: 'Shiny Colors',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/Ai.Na.View.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Ai.Na.View.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Ai.Na.View.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Ai.Na.View.lrc`,
  },
  {
    id: 51,
    title: '星の声',
    artist: 'Shiny Colors',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/Hoshi.No.Koe.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hoshi.No.Koe.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Hoshi.No.Koe.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hoshi.No.Koe.lrc`,
  },
  {
    id: 52,
    title: '虹の行方 -28 colors-',
    artist: 'Shiny Colors',
    type: '全体曲',
    unit: 'Shiny Colors',
    audioUrl: `${GITHUB_RELEASE_BASE}/Niji.No.Yukue.-.28.Colors.-.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Niji.No.Yukue.-.28.Colors.-.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Niji.No.Yukue.-.28.Colors.-.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Niji.No.Yukue.-.28.Colors.-.lrc`,
  },
  {
    id: 53,
    title: '283体操',
    artist: '峯田茉優,礒部花凜,永井真里子,芝崎典子,田中有紀,田嶌紗蘭,紫月杏朱彩,Shiny Colors',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/283.Taiso.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/283.Taiso.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/283.Taisō.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/283.Taisō.lrc`,
  },
  {
    id: 54,
    title: 'CANDY UNIVERSE',
    artist: '峯田茉優,希水しお,河野ひより,永井真里子,黒木ほの香',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/CANDY.UNIVERSE.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/CANDY.UNIVERSE.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/CANDY.UNIVERSE.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/CANDY.UNIVERSE.lrc`,
  },
  {
    id: 55,
    title: 'CRYST@LOUD',
    artist: 'THE IDOLM@STER',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/CRYST@LOUD.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/CRYST@LOUD.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/CRYST@LOUD.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/CRYST@LOUD.lrc`,
  },
  {
    id: 56,
    title: 'GOTCHA',
    artist: '田中有紀,峯田茉優,永井真里子',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/GOTCHA.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/GOTCHA.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/GOTCHA.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/GOTCHA.lrc`,
  },
  {
    id: 57,
    title: 'Killer×Mission',
    artist: "L'Antica,Straylight",
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Killer×Mission.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Killer×Mission.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Killer×Mission.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Killer×Mission.lrc`,
  },
  {
    id: 58,
    title: 'Midnight parade!',
    artist: '菅沼千紗,八巻アンナ,丸岡和佳奈,前川涼子,北原沙弥香',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Midnight.parade.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Midnight.parade.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Midnight.parade!.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Midnight.parade!.lrc`,
  },
  {
    id: 59,
    title: 'ONE STAR',
    artist: '河野ひより,幸村恵理,北原沙弥香',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/ONE.STAR.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/ONE.STAR.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/ONE.STAR.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/ONE.STAR.lrc`,
  },
  {
    id: 60,
    title: 'OPEN the New world',
    artist: '近藤玲奈,礒部花凜,涼本あきほ,田中有紀',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/OPEN.the.New.world.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/OPEN.the.New.world.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/OPEN.the.New.world.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/OPEN.the.New.world.lrc`,
  },
  {
    id: 61,
    title: 'Pioneer Impact',
    artist: "L'Antica,SHHis",
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Pioneer.Impact.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Pioneer.Impact.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Pioneer.Impact.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Pioneer.Impact.lrc`,
  },
  {
    id: 62,
    title: 'Poison Berry Daughters',
    artist: 'Shiny Colors',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Poison.Berry.Daughters.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Poison.Berry.Daughters.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Poison.Berry.Daughters.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Poison.Berry.Daughters.lrc`,
  },
  {
    id: 63,
    title: 'Secret utopIA',
    artist: 'illumination STARS,ALSTROEMERIA,SHHis',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Secret.utopIA.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Secret.utopIA.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Secret.utopIA.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Secret.utopIA.lrc`,
  },
  {
    id: 64,
    title: 'SOLAR WAY',
    artist: 'Team.Sol',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/SOLAR.WAY.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/SOLAR.WAY.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/SOLAR.WAY.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/SOLAR.WAY.lrc`,
  },
  {
    id: 65,
    title: 'Sparkle',
    artist: 'illumination STARS,noctchill',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Sparkle.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Sparkle.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Sparkle.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Sparkle.lrc`,
  },
  {
    id: 66,
    title: 'VOY@GER シャイニーカラーズVer.',
    artist: 'THE IDOLM@STER FIVE STARS!!!!!',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/VOY.@.GER.Shainikarazu.Ver.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/VOY.@.GER.Shainikarazu.Ver.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/VOY.@.GER.Shainīkarāzu.Ver.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/VOY.@.GER.Shainīkarāzu.Ver.lrc`,
  },
  {
    id: 67,
    title: 'ねぇ、ねぇ、ねぇ',
    artist: '幸村恵理,関根瞳,結名美月,白石晴香,芝崎典子',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Ne.Ne.Ne.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Ne.Ne.Ne.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Nē.,.Nē.,.Nē.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Nē.,.Nē.,.Nē.lrc`,
  },
  {
    id: 68,
    title: 'サマーサマーオーシャンパーリィバケーション',
    artist: '峯田茉優,幸村恵理,山根綺,希水しお,河野ひより,前川涼子,田嶌紗蘭,小澤麗那',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Samasamaoshampariibakeshon.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Samasamaoshampariibakeshon.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Samāsamāōshampāriibakēshon.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Samāsamāōshampāriibakēshon.lrc`,
  },
  {
    id: 69,
    title: 'シャイニーエクササイズ',
    artist: '峯田茉優,礒部花凜,永井真里子,芝崎典子,田中有紀,田嶌紗蘭,紫月杏朱彩,Shiny Colors',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Shainiekusasaizu.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Shainiekusasaizu.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Shainīekusasaizu.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Shainīekusasaizu.lrc`,
  },
  {
    id: 70,
    title: 'プラニスフィア ～planisphere～',
    artist: 'Team.Stella',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Puranisufia.Planisphere.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Puranisufia.Planisphere.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Puranisufia.Planisphere.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Puranisufia.Planisphere.lrc`,
  },
  {
    id: 71,
    title: 'ホムラインビテーション',
    artist: '田中有紀,幸村恵理,北原沙弥香,紫月杏朱彩,山根綺',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Homuraimbiteshon.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Homuraimbiteshon.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Homuraimbitēshon.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Homuraimbitēshon.lrc`,
  },
  {
    id: 72,
    title: 'リフレインブレイン',
    artist: 'ALSTROEMERIA,CoMETIK',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Rifureimburein.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Rifureimburein.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Rifureimburein.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Rifureimburein.lrc`,
  },
  {
    id: 73,
    title: 'リフレクトサイン (2022 Ver.)',
    artist: 'Team.Luna',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Rifurekutosain.2022.Ver.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Rifurekutosain.2022.Ver.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Rifurekutosain.2022.Ver.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Rifurekutosain.2022.Ver.lrc`,
  },
  {
    id: 74,
    title: '異次元★♥BIGBANG',
    artist: '大橋彩香,田所あずさ,礒部花凜,伊波杏樹,大西亜玖璃,伊達さゆり,楡井希実',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/I.Jigen.BIGBANG.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/I.Jigen.BIGBANG.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/I.Jigen.BIGBANG.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/I.Jigen.BIGBANG.lrc`,
  },
  {
    id: 75,
    title: '相合学舎',
    artist: 'noctchill,放学后CLIMAX GIRLS',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Sogo.Gakusha.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Sogo.Gakusha.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Sōgō.Gakusha.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Sōgō.Gakusha.lrc`,
  },
  {
    id: 76,
    title: '輝きにかわる',
    artist: '黒木ほの香,岡咲美保,菅沼千紗',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Kagayaki.Ni.Kawaru.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Kagayaki.Ni.Kawaru.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Kagayaki.Ni.Kawaru.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Kagayaki.Ni.Kawaru.lrc`,
  },
  {
    id: 77,
    title: '迅雷鉄火',
    artist: '放学后CLIMAX GIRLS,Straylight',
    type: '团体曲',
    audioUrl: `${GITHUB_RELEASE_BASE}/Jinrai.Tekka.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Jinrai.Tekka.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Jinrai.Tekka.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Jinrai.Tekka.lrc`,
  },
  {
    id: 78,
    title: 'Anniversary',
    artist: 'ALSTROEMERIA',
    type: '组合曲',
    unit: 'ALSTROEMERIA',
    audioUrl: `${GITHUB_RELEASE_BASE}/Anniversary.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Anniversary.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Anniversary.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Anniversary.lrc`,
  },
  {
    id: 79,
    title: 'Bloomy!',
    artist: 'ALSTROEMERIA',
    type: '组合曲',
    unit: 'ALSTROEMERIA',
    audioUrl: `${GITHUB_RELEASE_BASE}/Bloomy.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Bloomy.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Bloomy!.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Bloomy!.lrc`,
  },
  {
    id: 80,
    title: 'DAYDREAM LOVE',
    artist: 'ALSTROEMERIA',
    type: '组合曲',
    unit: 'ALSTROEMERIA',
    audioUrl: `${GITHUB_RELEASE_BASE}/DAYDREAM.LOVE.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/DAYDREAM.LOVE.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/DAYDREAM.LOVE.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/DAYDREAM.LOVE.lrc`,
  },
  {
    id: 81,
    title: 'Give me some more...',
    artist: 'ALSTROEMERIA',
    type: '组合曲',
    unit: 'ALSTROEMERIA',
    audioUrl: `${GITHUB_RELEASE_BASE}/Give.me.some.more.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Give.me.some.more.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Give.me.some.more.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Give.me.some.more.lrc`,
  },
  {
    id: 82,
    title: 'Love Addiction',
    artist: 'ALSTROEMERIA',
    type: '组合曲',
    unit: 'ALSTROEMERIA',
    audioUrl: `${GITHUB_RELEASE_BASE}/Love.Addiction.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Love.Addiction.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Love.Addiction.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Love.Addiction.lrc`,
  },
  {
    id: 83,
    title: 'Love Letter',
    artist: 'ALSTROEMERIA',
    type: '组合曲',
    unit: 'ALSTROEMERIA',
    audioUrl: `${GITHUB_RELEASE_BASE}/Love.Letter.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Love.Letter.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Love.Letter.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Love.Letter.lrc`,
  },
  {
    id: 84,
    title: 'mellow mellow',
    artist: 'ALSTROEMERIA',
    type: '组合曲',
    unit: 'ALSTROEMERIA',
    audioUrl: `${GITHUB_RELEASE_BASE}/mellow.mellow.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/mellow.mellow.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/mellow.mellow.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/mellow.mellow.lrc`,
  },
  {
    id: 85,
    title: 'Migratory Echoes (アルストロメリア Ver.)',
    artist: 'ALSTROEMERIA',
    type: '组合曲',
    unit: 'ALSTROEMERIA',
    audioUrl: `${GITHUB_RELEASE_BASE}/Migratory.Echoes.Arusutoromeria.Ver.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Migratory.Echoes.Arusutoromeria.Ver.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Migratory.Echoes.Arusutoromeria.Ver.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Migratory.Echoes.Arusutoromeria.Ver.lrc`,
  },
  {
    id: 86,
    title: 'VERY BERRY LOVE',
    artist: 'ALSTROEMERIA',
    type: '组合曲',
    unit: 'ALSTROEMERIA',
    audioUrl: `${GITHUB_RELEASE_BASE}/VERY.BERRY.LOVE.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/VERY.BERRY.LOVE.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/VERY.BERRY.LOVE.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/VERY.BERRY.LOVE.lrc`,
  },
  {
    id: 87,
    title: 'With you',
    artist: 'ALSTROEMERIA',
    type: '组合曲',
    unit: 'ALSTROEMERIA',
    audioUrl: `${GITHUB_RELEASE_BASE}/With.you.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/With.you.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/With.you.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/With.you.lrc`,
  },
  {
    id: 88,
    title: 'アスタラブビスタ',
    artist: 'ALSTROEMERIA',
    type: '组合曲',
    unit: 'ALSTROEMERIA',
    audioUrl: `${GITHUB_RELEASE_BASE}/Asutarabubisuta.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Asutarabubisuta.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Asutarabubisuta.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Asutarabubisuta.lrc`,
  },
  {
    id: 89,
    title: 'アルストロメリア',
    artist: 'ALSTROEMERIA',
    type: '组合曲',
    unit: 'ALSTROEMERIA',
    audioUrl: `${GITHUB_RELEASE_BASE}/Arusutoromeria.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Arusutoromeria.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Arusutoromeria.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Arusutoromeria.lrc`,
  },
  {
    id: 90,
    title: 'グラデーション',
    artist: 'ALSTROEMERIA',
    type: '组合曲',
    unit: 'ALSTROEMERIA',
    audioUrl: `${GITHUB_RELEASE_BASE}/Guradeshon.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Guradeshon.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Guradēshon.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Guradēshon.lrc`,
  },
  {
    id: 91,
    title: 'ダブル・イフェクト',
    artist: 'ALSTROEMERIA',
    type: '组合曲',
    unit: 'ALSTROEMERIA',
    audioUrl: `${GITHUB_RELEASE_BASE}/Daburu.Ifekuto.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Daburu.Ifekuto.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Daburu.Ifekuto.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Daburu.Ifekuto.lrc`,
  },
  {
    id: 92,
    title: 'ハピリリ',
    artist: 'ALSTROEMERIA',
    type: '组合曲',
    unit: 'ALSTROEMERIA',
    audioUrl: `${GITHUB_RELEASE_BASE}/Hapiriri.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hapiriri.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Hapiriri.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hapiriri.lrc`,
  },
  {
    id: 93,
    title: 'パステルカラー パスカラカラー',
    artist: 'ALSTROEMERIA',
    type: '组合曲',
    unit: 'ALSTROEMERIA',
    audioUrl: `${GITHUB_RELEASE_BASE}/Pasuterukara.Pasukarakara.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Pasuterukara.Pasukarakara.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Pasuterukarā.Pasukarakarā.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Pasuterukarā.Pasukarakarā.lrc`,
  },
  {
    id: 94,
    title: 'メッセージ',
    artist: 'ALSTROEMERIA',
    type: '组合曲',
    unit: 'ALSTROEMERIA',
    audioUrl: `${GITHUB_RELEASE_BASE}/Messeji.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Messeji.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Messēji.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Messēji.lrc`,
  },
  {
    id: 95,
    title: 'ラブ・ボナペティート',
    artist: 'ALSTROEMERIA',
    type: '组合曲',
    unit: 'ALSTROEMERIA',
    audioUrl: `${GITHUB_RELEASE_BASE}/Rabu.Bonapetito.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Rabu.Bonapetito.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Rabu.Bonapetīto.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Rabu.Bonapetīto.lrc`,
  },
  {
    id: 96,
    title: 'ルピラ',
    artist: 'ALSTROEMERIA',
    type: '组合曲',
    unit: 'ALSTROEMERIA',
    audioUrl: `${GITHUB_RELEASE_BASE}/Rupira.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Rupira.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Rupira.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Rupira.lrc`,
  },
  {
    id: 97,
    title: '明日もBeautiful Day',
    artist: 'ALSTROEMERIA',
    type: '组合曲',
    unit: 'ALSTROEMERIA',
    audioUrl: `${GITHUB_RELEASE_BASE}/Ashita.Mo.Beautiful.Day.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Ashita.Mo.Beautiful.Day.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Ashita.Mo.Beautiful.Day.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Ashita.Mo.Beautiful.Day.lrc`,
  },
  {
    id: 98,
    title: 'Clean.Clean up',
    artist: 'CoMETIK',
    type: '组合曲',
    unit: 'CoMETIK',
    audioUrl: `${GITHUB_RELEASE_BASE}/Clean.Clean.up.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Clean.Clean.up.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Clean.Clean.up.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Clean.Clean.up.lrc`,
  },
  {
    id: 99,
    title: 'Heads or Tails？',
    artist: 'CoMETIK',
    type: '组合曲',
    unit: 'CoMETIK',
    audioUrl: `${GITHUB_RELEASE_BASE}/Heads.or.Tails.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Heads.or.Tails.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Heads.or.Tails.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Heads.or.Tails.lrc`,
  },
  {
    id: 100,
    title: 'Migratory Echoes (コメティック Ver.)',
    artist: 'CoMETIK',
    type: '组合曲',
    unit: 'CoMETIK',
    audioUrl: `${GITHUB_RELEASE_BASE}/Migratory.Echoes.Kometikku.Ver.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Migratory.Echoes.Kometikku.Ver.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Migratory.Echoes.Kometikku.Ver.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Migratory.Echoes.Kometikku.Ver.lrc`,
  },
  {
    id: 101,
    title: 'くだらないや',
    artist: 'CoMETIK',
    type: '组合曲',
    unit: 'CoMETIK',
    audioUrl: `${GITHUB_RELEASE_BASE}/Kudaranai.Ya.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Kudaranai.Ya.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Kudaranai.Ya.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Kudaranai.Ya.lrc`,
  },
  {
    id: 102,
    title: 'ハナムケのハナタバ',
    artist: 'CoMETIK',
    type: '组合曲',
    unit: 'CoMETIK',
    audioUrl: `${GITHUB_RELEASE_BASE}/Hanamuke.No.Hana.Taba.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hanamuke.No.Hana.Taba.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Hanamuke.No.Hana.Taba.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hanamuke.No.Hana.Taba.lrc`,
  },
  {
    id: 103,
    title: '似セ者',
    artist: 'CoMETIK',
    type: '组合曲',
    unit: 'CoMETIK',
    audioUrl: `${GITHUB_RELEASE_BASE}/Ni.Se.Sha.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Ni.Se.Sha.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Ni.Se.Sha.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Ni.Se.Sha.lrc`,
  },
  {
    id: 104,
    title: '平行線の美学',
    artist: 'CoMETIK',
    type: '组合曲',
    unit: 'CoMETIK',
    audioUrl: `${GITHUB_RELEASE_BASE}/Heiko.Sen.No.Bigaku.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Heiko.Sen.No.Bigaku.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Heikō.Sen.No.Bigaku.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Heikō.Sen.No.Bigaku.lrc`,
  },
  {
    id: 105,
    title: '泥濘鳴鳴',
    artist: 'CoMETIK',
    type: '组合曲',
    unit: 'CoMETIK',
    audioUrl: `${GITHUB_RELEASE_BASE}/Deinei.Na.Na.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Deinei.Na.Na.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Deinei.Na.Na.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Deinei.Na.Na.lrc`,
  },
  {
    id: 106,
    title: '無自覚アプリオリ',
    artist: 'CoMETIK',
    type: '组合曲',
    unit: 'CoMETIK',
    audioUrl: `${GITHUB_RELEASE_BASE}/Mujikaku.Apuriori.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Mujikaku.Apuriori.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Mujikaku.Apuriori.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Mujikaku.Apuriori.lrc`,
  },
  {
    id: 107,
    title: 'BRIGHTEST WHITE',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/BRIGHTEST.WHITE.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/BRIGHTEST.WHITE.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/BRIGHTEST.WHITE.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/BRIGHTEST.WHITE.lrc`,
  },
  {
    id: 108,
    title: 'FELICE',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/FELICE.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/FELICE.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/FELICE.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/FELICE.lrc`,
  },
  {
    id: 109,
    title: 'Forward March！！！',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Forward.March.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Forward.March.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Forward.March!!!.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Forward.March!!!.lrc`,
  },
  {
    id: 110,
    title: 'Happy Funny Lucky',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Happy.Funny.Lucky.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Happy.Funny.Lucky.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Happy.Funny.Lucky.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Happy.Funny.Lucky.lrc`,
  },
  {
    id: 111,
    title: 'KoiKyun！',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/KoiKyun.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/KoiKyun.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/KoiKyun!.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/KoiKyun!.lrc`,
  },
  {
    id: 112,
    title: 'Migratory Echoes (イルミネーションスターズ Ver.)',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Migratory.Echoes.Irumineshonsutazu.Ver.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Migratory.Echoes.Irumineshonsutazu.Ver.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Migratory.Echoes.Iruminēshonsutāzu.Ver.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Migratory.Echoes.Iruminēshonsutāzu.Ver.lrc`,
  },
  {
    id: 113,
    title: 'PRISISM',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/PRISISM.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/PRISISM.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/PRISISM.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/PRISISM.lrc`,
  },
  {
    id: 114,
    title: 'REWRITING',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/REWRITING.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/REWRITING.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/REWRITING.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/REWRITING.lrc`,
  },
  {
    id: 115,
    title: 'Shower of light',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Shower.of.light.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Shower.of.light.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Shower.of.light.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Shower.of.light.lrc`,
  },
  {
    id: 116,
    title: 'STARRY PLACE',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/STARRY.PLACE.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/STARRY.PLACE.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/STARRY.PLACE.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/STARRY.PLACE.lrc`,
  },
  {
    id: 117,
    title: 'Twinkle way',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Twinkle.way.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Twinkle.way.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Twinkle.way.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Twinkle.way.lrc`,
  },
  {
    id: 118,
    title: 'We can go now!',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/We.can.go.now.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/We.can.go.now.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/We.can.go.now!.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/We.can.go.now!.lrc`,
  },
  {
    id: 119,
    title: 'イルミネイトコンサート',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Irumineitokonsato.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Irumineitokonsato.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Irumineitokonsāto.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Irumineitokonsāto.lrc`,
  },
  {
    id: 120,
    title: 'スマイルシンフォニア',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Sumairushinfonia.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Sumairushinfonia.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Sumairushinfonia.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Sumairushinfonia.lrc`,
  },
  {
    id: 121,
    title: 'トライアングル',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Toraianguru.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Toraianguru.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Toraianguru.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Toraianguru.lrc`,
  },
  {
    id: 122,
    title: 'ヒカリのdestination',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Hikari.No.Destination.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hikari.No.Destination.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Hikari.No.Destination.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hikari.No.Destination.lrc`,
  },
  {
    id: 123,
    title: '星が流れて',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Hoshi.Ga.Nagare.Te.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hoshi.Ga.Nagare.Te.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Hoshi.Ga.Nagare.Te.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hoshi.Ga.Nagare.Te.lrc`,
  },
  {
    id: 124,
    title: '星の数だけ',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Hoshi.No.Kazu.Dake.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hoshi.No.Kazu.Dake.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Hoshi.No.Kazu.Dake.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hoshi.No.Kazu.Dake.lrc`,
  },
  {
    id: 125,
    title: '晴れのちバルーン',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Hare.Nochi.Barun.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hare.Nochi.Barun.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Hare.Nochi.Barūn.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hare.Nochi.Barūn.lrc`,
  },
  {
    id: 126,
    title: '枕木の歌',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Makuragi.No.Uta.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Makuragi.No.Uta.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Makuragi.No.Uta.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Makuragi.No.Uta.lrc`,
  },
  {
    id: 127,
    title: '虹になれ',
    artist: 'illumination STARS',
    type: '组合曲',
    unit: 'illumination STARS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Niji.Ni.Nare.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Niji.Ni.Nare.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Niji.Ni.Nare.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Niji.Ni.Nare.lrc`,
  },
  {
    id: 128,
    title: 'abyss of conflict (2023 Ver.)',
    artist: "L'Antica",
    type: '组合曲',
    unit: "L'Antica",
    audioUrl: `${GITHUB_RELEASE_BASE}/abyss.of.conflict.2023.Ver.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/abyss.of.conflict.2023.Ver.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/abyss.of.conflict.2023.Ver.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/abyss.of.conflict.2023.Ver.lrc`,
  },
  {
    id: 129,
    title: 'Black Reverie (2023 Ver.)',
    artist: "L'Antica",
    type: '组合曲',
    unit: "L'Antica",
    audioUrl: `${GITHUB_RELEASE_BASE}/Black.Reverie.2023.Ver.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Black.Reverie.2023.Ver.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Black.Reverie.2023.Ver.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Black.Reverie.2023.Ver.lrc`,
  },
  {
    id: 130,
    title: 'Migratory Echoes (アンティーカ Ver.)',
    artist: "L'Antica",
    type: '组合曲',
    unit: "L'Antica",
    audioUrl: `${GITHUB_RELEASE_BASE}/Migratory.Echoes.Antika.Ver.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Migratory.Echoes.Antika.Ver.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Migratory.Echoes.Antīka.Ver.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Migratory.Echoes.Antīka.Ver.lrc`,
  },
  {
    id: 131,
    title: 'NEO THEORY FANTASY (2023 Ver.)',
    artist: "L'Antica",
    type: '组合曲',
    unit: "L'Antica",
    audioUrl: `${GITHUB_RELEASE_BASE}/NEO.THEORY.FANTASY.2023.Ver.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/NEO.THEORY.FANTASY.2023.Ver.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/NEO.THEORY.FANTASY.2023.Ver.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/NEO.THEORY.FANTASY.2023.Ver.lrc`,
  },
  {
    id: 132,
    title: 'THE LAST PRIDE',
    artist: "L'Antica",
    type: '组合曲',
    unit: "L'Antica",
    audioUrl: `${GITHUB_RELEASE_BASE}/THE.LAST.PRIDE.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/THE.LAST.PRIDE.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/THE.LAST.PRIDE.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/THE.LAST.PRIDE.lrc`,
  },
  {
    id: 133,
    title: 'Unsung Heroes',
    artist: "L'Antica",
    type: '组合曲',
    unit: "L'Antica",
    audioUrl: `${GITHUB_RELEASE_BASE}/Unsung.Heroes.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Unsung.Heroes.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Unsung.Heroes.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Unsung.Heroes.lrc`,
  },
  {
    id: 134,
    title: 'とある英雄たちの物語',
    artist: "L'Antica",
    type: '组合曲',
    unit: "L'Antica",
    audioUrl: `${GITHUB_RELEASE_BASE}/Toaru.Eiyu.Tachi.No.Monogatari.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Toaru.Eiyu.Tachi.No.Monogatari.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Toaru.Eiyū.Tachi.No.Monogatari.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Toaru.Eiyū.Tachi.No.Monogatari.lrc`,
  },
  {
    id: 135,
    title: 'バベルシティ・グレイス (2023 Ver.)',
    artist: "L'Antica",
    type: '组合曲',
    unit: "L'Antica",
    audioUrl: `${GITHUB_RELEASE_BASE}/Baberu.Shiti.Gure.Isu.2023.Ver.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Baberu.Shiti.Gure.Isu.2023.Ver.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Baberu.Shiti.Gure.Isu.2023.Ver.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Baberu.Shiti.Gure.Isu.2023.Ver.lrc`,
  },
  {
    id: 136,
    title: 'ブレイク・アウト・セレンディピティ',
    artist: "L'Antica",
    type: '组合曲',
    unit: "L'Antica",
    audioUrl: `${GITHUB_RELEASE_BASE}/Bureiku.Auto.Serendipiti.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Bureiku.Auto.Serendipiti.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Bureiku.Auto.Serendipiti.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Bureiku.Auto.Serendipiti.lrc`,
  },
  {
    id: 137,
    title: 'ラビリンス・レジスタンス (2023 Ver.)',
    artist: "L'Antica",
    type: '组合曲',
    unit: "L'Antica",
    audioUrl: `${GITHUB_RELEASE_BASE}/Rabirinsu.Rejisutansu.2023.Ver.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Rabirinsu.Rejisutansu.2023.Ver.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Rabirinsu.Rejisutansu.2023.Ver.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Rabirinsu.Rejisutansu.2023.Ver.lrc`,
  },
  {
    id: 138,
    title: '幻惑SILHOUETTE (2023 Ver.)',
    artist: "L'Antica",
    type: '组合曲',
    unit: "L'Antica",
    audioUrl: `${GITHUB_RELEASE_BASE}/Genwaku.SILHOUETTE.2023.Ver.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Genwaku.SILHOUETTE.2023.Ver.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Genwaku.SILHOUETTE.2023.Ver.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Genwaku.SILHOUETTE.2023.Ver.lrc`,
  },
  {
    id: 139,
    title: '愚者の独白',
    artist: "L'Antica",
    type: '组合曲',
    unit: "L'Antica",
    audioUrl: `${GITHUB_RELEASE_BASE}/Gusha.No.Dokuhaku.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Gusha.No.Dokuhaku.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Gusha.No.Dokuhaku.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Gusha.No.Dokuhaku.lrc`,
  },
  {
    id: 140,
    title: '文明開花輪舞 -シティ・ハレルヤ-',
    artist: "L'Antica",
    type: '组合曲',
    unit: "L'Antica",
    audioUrl: `${GITHUB_RELEASE_BASE}/Bummei.Kaika.Rimbu.-.Shiti.Hareruya.-.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Bummei.Kaika.Rimbu.-.Shiti.Hareruya.-.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Bummei.Kaika.Rimbu.-.Shiti.Hareruya.-.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Bummei.Kaika.Rimbu.-.Shiti.Hareruya.-.lrc`,
  },
  {
    id: 141,
    title: '時限式狂騒ワンダーランド',
    artist: "L'Antica",
    type: '组合曲',
    unit: "L'Antica",
    audioUrl: `${GITHUB_RELEASE_BASE}/Jigen.Shiki.Kyoso.Wandarando.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Jigen.Shiki.Kyoso.Wandarando.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Jigen.Shiki.Kyōsō.Wandārando.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Jigen.Shiki.Kyōsō.Wandārando.lrc`,
  },
  {
    id: 142,
    title: '有彩色ユリイカ',
    artist: "L'Antica",
    type: '组合曲',
    unit: "L'Antica",
    audioUrl: `${GITHUB_RELEASE_BASE}/Yu.Saishiki.Yuri.Ika.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Yu.Saishiki.Yuri.Ika.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Yū.Saishiki.Yuri.Ika.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Yū.Saishiki.Yuri.Ika.lrc`,
  },
  {
    id: 143,
    title: '橙より未来',
    artist: "L'Antica",
    type: '组合曲',
    unit: "L'Antica",
    audioUrl: `${GITHUB_RELEASE_BASE}/Daidai.Yori.Mirai.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Daidai.Yori.Mirai.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Daidai.Yori.Mirai.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Daidai.Yori.Mirai.lrc`,
  },
  {
    id: 144,
    title: '浮動性イノセンス',
    artist: "L'Antica",
    type: '组合曲',
    unit: "L'Antica",
    audioUrl: `${GITHUB_RELEASE_BASE}/Fudo.Sei.Inosensu.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Fudo.Sei.Inosensu.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Fudō.Sei.Inosensu.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Fudō.Sei.Inosensu.lrc`,
  },
  {
    id: 145,
    title: '秋の終わり、僕の記憶',
    artist: "L'Antica",
    type: '组合曲',
    unit: "L'Antica",
    audioUrl: `${GITHUB_RELEASE_BASE}/Aki.No.Owari.Boku.No.Kioku.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Aki.No.Owari.Boku.No.Kioku.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Aki.No.Owari.,.Boku.No.Kioku.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Aki.No.Owari.,.Boku.No.Kioku.lrc`,
  },
  {
    id: 146,
    title: '純白トロイメライ (2023 Ver.)',
    artist: "L'Antica",
    type: '组合曲',
    unit: "L'Antica",
    audioUrl: `${GITHUB_RELEASE_BASE}/Jumpaku.Toroimerai.2023.Ver.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Jumpaku.Toroimerai.2023.Ver.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Jumpaku.Toroimerai.2023.Ver.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Jumpaku.Toroimerai.2023.Ver.lrc`,
  },
  {
    id: 147,
    title: '革命進化論 (2023 Ver.)',
    artist: "L'Antica",
    type: '组合曲',
    unit: "L'Antica",
    audioUrl: `${GITHUB_RELEASE_BASE}/Kakumei.Shinka.Ron.2023.Ver.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Kakumei.Shinka.Ron.2023.Ver.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Kakumei.Shinka.Ron.2023.Ver.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Kakumei.Shinka.Ron.2023.Ver.lrc`,
  },
  {
    id: 148,
    title: '365日のストーリー',
    artist: 'noctchill',
    type: '组合曲',
    unit: 'noctchill',
    audioUrl: `${GITHUB_RELEASE_BASE}/365.Nichi.No.Sutori.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/365.Nichi.No.Sutori.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/365.Nichi.No.Sutōrī.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/365.Nichi.No.Sutōrī.lrc`,
  },
  {
    id: 149,
    title: 'Catch the Breeze',
    artist: 'noctchill',
    type: '组合曲',
    unit: 'noctchill',
    audioUrl: `${GITHUB_RELEASE_BASE}/Catch.the.Breeze.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Catch.the.Breeze.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Catch.the.Breeze.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Catch.the.Breeze.lrc`,
  },
  {
    id: 150,
    title: 'Migratory Echoes (ノクチル Ver.)',
    artist: 'noctchill',
    type: '组合曲',
    unit: 'noctchill',
    audioUrl: `${GITHUB_RELEASE_BASE}/Migratory.Echoes.Nokuchiru.Ver.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Migratory.Echoes.Nokuchiru.Ver.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Migratory.Echoes.Nokuchiru.Ver.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Migratory.Echoes.Nokuchiru.Ver.lrc`,
  },
  {
    id: 151,
    title: 'Reflection',
    artist: 'noctchill',
    type: '组合曲',
    unit: 'noctchill',
    audioUrl: `${GITHUB_RELEASE_BASE}/Reflection.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Reflection.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Reflection.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Reflection.lrc`,
  },
  {
    id: 152,
    title: 'Swing it!',
    artist: 'noctchill',
    type: '组合曲',
    unit: 'noctchill',
    audioUrl: `${GITHUB_RELEASE_BASE}/Swing.it.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Swing.it.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Swing.it!.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Swing.it!.lrc`,
  },
  {
    id: 153,
    title: 'あの花のように',
    artist: 'noctchill',
    type: '组合曲',
    unit: 'noctchill',
    audioUrl: `${GITHUB_RELEASE_BASE}/Ano.Hana.No.Yo.Ni.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Ano.Hana.No.Yo.Ni.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Ano.Hana.No.Yō.Ni.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Ano.Hana.No.Yō.Ni.lrc`,
  },
  {
    id: 154,
    title: 'いつかのキミへ',
    artist: 'noctchill',
    type: '组合曲',
    unit: 'noctchill',
    audioUrl: `${GITHUB_RELEASE_BASE}/Itsuka.No.Kimi.E.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Itsuka.No.Kimi.E.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Itsuka.No.Kimi.E.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Itsuka.No.Kimi.E.lrc`,
  },
  {
    id: 155,
    title: 'いつだって僕らは',
    artist: 'noctchill',
    type: '组合曲',
    unit: 'noctchill',
    audioUrl: `${GITHUB_RELEASE_BASE}/Itsu.Datte.Bokura.Wa.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Itsu.Datte.Bokura.Wa.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Itsu.Datte.Bokura.Wa.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Itsu.Datte.Bokura.Wa.lrc`,
  },
  {
    id: 156,
    title: 'アスファルトを鳴らして',
    artist: 'noctchill',
    type: '组合曲',
    unit: 'noctchill',
    audioUrl: `${GITHUB_RELEASE_BASE}/Asufaruto.O.Narashi.Te.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Asufaruto.O.Narashi.Te.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Asufaruto.O.Narashi.Te.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Asufaruto.O.Narashi.Te.lrc`,
  },
  {
    id: 157,
    title: 'グッバイ',
    artist: 'noctchill',
    type: '组合曲',
    unit: 'noctchill',
    audioUrl: `${GITHUB_RELEASE_BASE}/Gutsu.Bai.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Gutsu.Bai.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Gutsu.Bai.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Gutsu.Bai.lrc`,
  },
  {
    id: 158,
    title: '今しかない瞬間を',
    artist: 'noctchill',
    type: '组合曲',
    unit: 'noctchill',
    audioUrl: `${GITHUB_RELEASE_BASE}/Ima.Shika.Nai.Shunkan.O.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Ima.Shika.Nai.Shunkan.O.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Ima.Shika.Nai.Shunkan.O.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Ima.Shika.Nai.Shunkan.O.lrc`,
  },
  {
    id: 159,
    title: '僕らだけの未来の空',
    artist: 'noctchill',
    type: '组合曲',
    unit: 'noctchill',
    audioUrl: `${GITHUB_RELEASE_BASE}/Bokura.Dake.No.Mirai.No.Sora.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Bokura.Dake.No.Mirai.No.Sora.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Bokura.Dake.No.Mirai.No.Sora.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Bokura.Dake.No.Mirai.No.Sora.lrc`,
  },
  {
    id: 160,
    title: '夢が夢じゃなくなるその日まで',
    artist: 'noctchill',
    type: '组合曲',
    unit: 'noctchill',
    audioUrl: `${GITHUB_RELEASE_BASE}/Yume.Ga.Yume.Ja.Naku.Naru.Sono.Hi.Made.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Yume.Ga.Yume.Ja.Naku.Naru.Sono.Hi.Made.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Yume.Ga.Yume.Ja.Naku.Naru.Sono.Hi.Made.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Yume.Ga.Yume.Ja.Naku.Naru.Sono.Hi.Made.lrc`,
  },
  {
    id: 161,
    title: '愛しき日々',
    artist: 'noctchill',
    type: '组合曲',
    unit: 'noctchill',
    audioUrl: `${GITHUB_RELEASE_BASE}/Itoshiki.Hibi.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Itoshiki.Hibi.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Itoshiki.Hibi.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Itoshiki.Hibi.lrc`,
  },
  {
    id: 162,
    title: '未来へのSign',
    artist: 'noctchill',
    type: '组合曲',
    unit: 'noctchill',
    audioUrl: `${GITHUB_RELEASE_BASE}/Mirai.E.No.Sign.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Mirai.E.No.Sign.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Mirai.E.No.Sign.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Mirai.E.No.Sign.lrc`,
  },
  {
    id: 163,
    title: '青とオレンジ',
    artist: 'noctchill',
    type: '组合曲',
    unit: 'noctchill',
    audioUrl: `${GITHUB_RELEASE_BASE}/Ao.To.Orenji.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Ao.To.Orenji.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Ao.To.Orenji.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Ao.To.Orenji.lrc`,
  },
  {
    id: 164,
    title: '青空',
    artist: 'noctchill',
    type: '组合曲',
    unit: 'noctchill',
    audioUrl: `${GITHUB_RELEASE_BASE}/Aozora.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Aozora.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Aozora.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Aozora.lrc`,
  },
  {
    id: 165,
    title: 'After Run',
    artist: 'SHHis',
    type: '组合曲',
    unit: 'SHHis',
    audioUrl: `${GITHUB_RELEASE_BASE}/After.Run.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/After.Run.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/After.Run.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/After.Run.lrc`,
  },
  {
    id: 166,
    title: 'Bouncy Girl',
    artist: 'SHHis',
    type: '组合曲',
    unit: 'SHHis',
    audioUrl: `${GITHUB_RELEASE_BASE}/Bouncy.Girl.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Bouncy.Girl.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Bouncy.Girl.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Bouncy.Girl.lrc`,
  },
  {
    id: 167,
    title: 'Break Chain',
    artist: 'SHHis',
    type: '组合曲',
    unit: 'SHHis',
    audioUrl: `${GITHUB_RELEASE_BASE}/Break.Chain.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Break.Chain.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Break.Chain.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Break.Chain.lrc`,
  },
  {
    id: 168,
    title: 'Fading Stars',
    artist: 'SHHis',
    type: '组合曲',
    unit: 'SHHis',
    audioUrl: `${GITHUB_RELEASE_BASE}/Fading.Stars.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Fading.Stars.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Fading.Stars.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Fading.Stars.lrc`,
  },
  {
    id: 169,
    title: 'Fashionable',
    artist: 'SHHis',
    type: '组合曲',
    unit: 'SHHis',
    audioUrl: `${GITHUB_RELEASE_BASE}/Fashionable.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Fashionable.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Fashionable.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Fashionable.lrc`,
  },
  {
    id: 170,
    title: 'Fly and Fly',
    artist: 'SHHis',
    type: '组合曲',
    unit: 'SHHis',
    audioUrl: `${GITHUB_RELEASE_BASE}/Fly.and.Fly.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Fly.and.Fly.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Fly.and.Fly.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Fly.and.Fly.lrc`,
  },
  {
    id: 171,
    title: 'Forbidden Paradise',
    artist: 'SHHis',
    type: '组合曲',
    unit: 'SHHis',
    audioUrl: `${GITHUB_RELEASE_BASE}/Forbidden.Paradise.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Forbidden.Paradise.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Forbidden.Paradise.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Forbidden.Paradise.lrc`,
  },
  {
    id: 172,
    title: 'Happier',
    artist: 'SHHis',
    type: '组合曲',
    unit: 'SHHis',
    audioUrl: `${GITHUB_RELEASE_BASE}/Happier.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Happier.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Happier.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Happier.lrc`,
  },
  {
    id: 173,
    title: 'Migratory Echoes (シーズ Ver.)',
    artist: 'SHHis',
    type: '组合曲',
    unit: 'SHHis',
    audioUrl: `${GITHUB_RELEASE_BASE}/Migratory.Echoes.Shizu.Ver.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Migratory.Echoes.Shizu.Ver.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Migratory.Echoes.Shīzu.Ver.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Migratory.Echoes.Shīzu.Ver.lrc`,
  },
  {
    id: 174,
    title: 'Monochromatic',
    artist: 'SHHis',
    type: '组合曲',
    unit: 'SHHis',
    audioUrl: `${GITHUB_RELEASE_BASE}/Monochromatic.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Monochromatic.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Monochromatic.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Monochromatic.lrc`,
  },
  {
    id: 175,
    title: 'OH MY GOD',
    artist: 'SHHis',
    type: '组合曲',
    unit: 'SHHis',
    audioUrl: `${GITHUB_RELEASE_BASE}/OH.MY.GOD.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/OH.MY.GOD.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/OH.MY.GOD.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/OH.MY.GOD.lrc`,
  },
  {
    id: 176,
    title: 'Snowflake',
    artist: 'SHHis',
    type: '组合曲',
    unit: 'SHHis',
    audioUrl: `${GITHUB_RELEASE_BASE}/Snowflake.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Snowflake.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Snowflake.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Snowflake.lrc`,
  },
  {
    id: 177,
    title: 'SWEETEST BITE',
    artist: 'SHHis',
    type: '组合曲',
    unit: 'SHHis',
    audioUrl: `${GITHUB_RELEASE_BASE}/SWEETEST.BITE.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/SWEETEST.BITE.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/SWEETEST.BITE.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/SWEETEST.BITE.lrc`,
  },
  {
    id: 178,
    title: 'White Story',
    artist: 'SHHis',
    type: '组合曲',
    unit: 'SHHis',
    audioUrl: `${GITHUB_RELEASE_BASE}/White.Story.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/White.Story.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/White.Story.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/White.Story.lrc`,
  },
  {
    id: 179,
    title: 'Another Rampage',
    artist: 'Straylight',
    type: '组合曲',
    unit: 'Straylight',
    audioUrl: `${GITHUB_RELEASE_BASE}/Another.Rampage.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Another.Rampage.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Another.Rampage.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Another.Rampage.lrc`,
  },
  {
    id: 180,
    title: 'BURN BURN',
    artist: 'Straylight',
    type: '组合曲',
    unit: 'Straylight',
    audioUrl: `${GITHUB_RELEASE_BASE}/BURN.BURN.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/BURN.BURN.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/BURN.BURN.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/BURN.BURN.lrc`,
  },
  {
    id: 181,
    title: 'Cyber Parkour',
    artist: 'Straylight',
    type: '组合曲',
    unit: 'Straylight',
    audioUrl: `${GITHUB_RELEASE_BASE}/Cyber.Parkour.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Cyber.Parkour.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Cyber.Parkour.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Cyber.Parkour.lrc`,
  },
  {
    id: 182,
    title: 'Destined Rival',
    artist: 'Straylight',
    type: '组合曲',
    unit: 'Straylight',
    audioUrl: `${GITHUB_RELEASE_BASE}/Destined.Rival.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Destined.Rival.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Destined.Rival.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Destined.Rival.lrc`,
  },
  {
    id: 183,
    title: 'Future Designer',
    artist: 'Straylight',
    type: '组合曲',
    unit: 'Straylight',
    audioUrl: `${GITHUB_RELEASE_BASE}/Future.Designer.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Future.Designer.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Future.Designer.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Future.Designer.lrc`,
  },
  {
    id: 184,
    title: 'Future Transit',
    artist: 'Straylight',
    type: '组合曲',
    unit: 'Straylight',
    audioUrl: `${GITHUB_RELEASE_BASE}/Future.Transit.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Future.Transit.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Future.Transit.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Future.Transit.lrc`,
  },
  {
    id: 185,
    title: 'GET OVER',
    artist: 'Straylight',
    type: '组合曲',
    unit: 'Straylight',
    audioUrl: `${GITHUB_RELEASE_BASE}/GET.OVER.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/GET.OVER.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/GET.OVER.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/GET.OVER.lrc`,
  },
  {
    id: 186,
    title: 'Hide & Attack',
    artist: 'Straylight',
    type: '组合曲',
    unit: 'Straylight',
    audioUrl: `${GITHUB_RELEASE_BASE}/Hide.&.Attack.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hide.&.Attack.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Hide.&.Attack.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hide.&.Attack.lrc`,
  },
  {
    id: 187,
    title: 'Imitation Ghost',
    artist: 'Straylight',
    type: '组合曲',
    unit: 'Straylight',
    audioUrl: `${GITHUB_RELEASE_BASE}/Imitation.Ghost.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Imitation.Ghost.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Imitation.Ghost.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Imitation.Ghost.lrc`,
  },
  {
    id: 188,
    title: 'LINKs',
    artist: 'Straylight',
    type: '组合曲',
    unit: 'Straylight',
    audioUrl: `${GITHUB_RELEASE_BASE}/LINKs.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/LINKs.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/LINKs.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/LINKs.lrc`,
  },
  {
    id: 189,
    title: 'LIVE LIVE LIVE!',
    artist: 'Straylight',
    type: '组合曲',
    unit: 'Straylight',
    audioUrl: `${GITHUB_RELEASE_BASE}/LIVE.LIVE.LIVE.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/LIVE.LIVE.LIVE.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/LIVE.LIVE.LIVE!.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/LIVE.LIVE.LIVE!.lrc`,
  },
  {
    id: 190,
    title: 'Migratory Echoes (ストレイライト Ver.)',
    artist: 'Straylight',
    type: '组合曲',
    unit: 'Straylight',
    audioUrl: `${GITHUB_RELEASE_BASE}/Migratory.Echoes.Sutoreiraito.Ver.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Migratory.Echoes.Sutoreiraito.Ver.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Migratory.Echoes.Sutoreiraito.Ver.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Migratory.Echoes.Sutoreiraito.Ver.lrc`,
  },
  {
    id: 191,
    title: 'Overdrive Emotion',
    artist: 'Straylight',
    type: '组合曲',
    unit: 'Straylight',
    audioUrl: `${GITHUB_RELEASE_BASE}/Overdrive.Emotion.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Overdrive.Emotion.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Overdrive.Emotion.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Overdrive.Emotion.lrc`,
  },
  {
    id: 192,
    title: 'Real Mind Shakes',
    artist: 'Straylight',
    type: '组合曲',
    unit: 'Straylight',
    audioUrl: `${GITHUB_RELEASE_BASE}/Real.Mind.Shakes.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Real.Mind.Shakes.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Real.Mind.Shakes.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Real.Mind.Shakes.lrc`,
  },
  {
    id: 193,
    title: 'Start up Stand up',
    artist: 'Straylight',
    type: '组合曲',
    unit: 'Straylight',
    audioUrl: `${GITHUB_RELEASE_BASE}/Start.up.Stand.up.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Start.up.Stand.up.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Start.up.Stand.up.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Start.up.Stand.up.lrc`,
  },
  {
    id: 194,
    title: 'Timeless Shooting Star',
    artist: 'Straylight',
    type: '组合曲',
    unit: 'Straylight',
    audioUrl: `${GITHUB_RELEASE_BASE}/Timeless.Shooting.Star.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Timeless.Shooting.Star.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Timeless.Shooting.Star.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Timeless.Shooting.Star.lrc`,
  },
  {
    id: 195,
    title: 'Tracing Defender',
    artist: 'Straylight',
    type: '组合曲',
    unit: 'Straylight',
    audioUrl: `${GITHUB_RELEASE_BASE}/Tracing.Defender.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Tracing.Defender.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Tracing.Defender.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Tracing.Defender.lrc`,
  },
  {
    id: 196,
    title: 'Transcending The World',
    artist: 'Straylight',
    type: '组合曲',
    unit: 'Straylight',
    audioUrl: `${GITHUB_RELEASE_BASE}/Transcending.The.World.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Transcending.The.World.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Transcending.The.World.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Transcending.The.World.lrc`,
  },
  {
    id: 197,
    title: 'Wandering Dream Chaser',
    artist: 'Straylight',
    type: '组合曲',
    unit: 'Straylight',
    audioUrl: `${GITHUB_RELEASE_BASE}/Wandering.Dream.Chaser.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Wandering.Dream.Chaser.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Wandering.Dream.Chaser.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Wandering.Dream.Chaser.lrc`,
  },
  {
    id: 198,
    title: 'Migratory Echoes (放課後クライマックスガールズ Ver.)',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Migratory.Echoes.Hokago.Kuraimakkusugaruzu.Ver.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Migratory.Echoes.Hokago.Kuraimakkusugaruzu.Ver.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Migratory.Echoes.Hōkago.Kuraimakkusugāruzu.Ver.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Migratory.Echoes.Hōkago.Kuraimakkusugāruzu.Ver.lrc`,
  },
  {
    id: 199,
    title: 'さあ舞い上がれ',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Sa.Maiagare.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Sa.Maiagare.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Sā.Maiagare.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Sā.Maiagare.lrc`,
  },
  {
    id: 200,
    title: 'ひめくりモザイク',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Hime.Kuri.Mozaiku.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hime.Kuri.Mozaiku.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Hime.Kuri.Mozaiku.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hime.Kuri.Mozaiku.lrc`,
  },
  {
    id: 201,
    title: 'よりみちサンセット',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Yori.Michi.San.Setto.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Yori.Michi.San.Setto.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Yori.Michi.San.Setto.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Yori.Michi.San.Setto.lrc`,
  },
  {
    id: 202,
    title: 'キャットスクワッド',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Kyattosukuwaddo.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Kyattosukuwaddo.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Kyattosukuwaddo.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Kyattosukuwaddo.lrc`,
  },
  {
    id: 203,
    title: 'クライマックスアイランド',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Kuraimakkusuairando.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Kuraimakkusuairando.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Kuraimakkusuairando.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Kuraimakkusuairando.lrc`,
  },
  {
    id: 204,
    title: 'ハナサカサイサイ',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Hanasakasaisai.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hanasakasaisai.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Hanasakasaisai.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hanasakasaisai.lrc`,
  },
  {
    id: 205,
    title: 'パーティーマジックデザイナー',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Patimajikkudezaina.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Patimajikkudezaina.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Pātīmajikkudezainā.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Pātīmajikkudezainā.lrc`,
  },
  {
    id: 206,
    title: 'ビーチブレイバー',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Bichibureiba.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Bichibureiba.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Bīchibureibā.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Bīchibureibā.lrc`,
  },
  {
    id: 207,
    title: '一閃は君が導く',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Issen.Wa.Kimi.Ga.Michibiku.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Issen.Wa.Kimi.Ga.Michibiku.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Issen.Wa.Kimi.Ga.Michibiku.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Issen.Wa.Kimi.Ga.Michibiku.lrc`,
  },
  {
    id: 208,
    title: '乱舞る',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Rambu.Ru.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Rambu.Ru.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Rambu.Ru.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Rambu.Ru.lrc`,
  },
  {
    id: 209,
    title: '五ツ座流星群',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Go.Tsu.Za.Ryusei.Gun.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Go.Tsu.Za.Ryusei.Gun.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Go.Tsu.Za.Ryūsei.Gun.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Go.Tsu.Za.Ryūsei.Gun.lrc`,
  },
  {
    id: 210,
    title: '全力アンサー',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Zenryoku.Ansa.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Zenryoku.Ansa.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Zenryoku.Ansā.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Zenryoku.Ansā.lrc`,
  },
  {
    id: 211,
    title: '夢咲きAfter school',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Yume.Saki.After.School.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Yume.Saki.After.School.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Yume.Saki.After.School.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Yume.Saki.After.School.lrc`,
  },
  {
    id: 212,
    title: '太陽キッス',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Taiyo.Kissu.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Taiyo.Kissu.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Taiyō.Kissu.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Taiyō.Kissu.lrc`,
  },
  {
    id: 213,
    title: '学祭革命夜明け前',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Gaku.Sai.Kakumei.Yoake.Mae.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Gaku.Sai.Kakumei.Yoake.Mae.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Gaku.Sai.Kakumei.Yoake.Mae.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Gaku.Sai.Kakumei.Yoake.Mae.lrc`,
  },
  {
    id: 214,
    title: '快盗Vを見逃すな',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Kai.To.V.O.Minogasu.Na.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Kai.To.V.O.Minogasu.Na.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Kai.Tō.V.O.Minogasu.Na.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Kai.Tō.V.O.Minogasu.Na.lrc`,
  },
  {
    id: 215,
    title: '拝啓タイムカプセル',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Haikei.Taimu.Kapuseru.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Haikei.Taimu.Kapuseru.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Haikei.Taimu.Kapuseru.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Haikei.Taimu.Kapuseru.lrc`,
  },
  {
    id: 216,
    title: '放課後マギア',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Hokago.Magia.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hokago.Magia.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Hōkago.Magia.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hōkago.Magia.lrc`,
  },
  {
    id: 217,
    title: '裸足じゃイラレナイ',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Hadashi.Ja.Irarenai.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hadashi.Ja.Irarenai.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Hadashi.Ja.Irarenai.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Hadashi.Ja.Irarenai.lrc`,
  },
  {
    id: 218,
    title: '進路は超銀河',
    artist: '放学后CLIMAX GIRLS',
    type: '组合曲',
    unit: '放学后CLIMAX GIRLS',
    audioUrl: `${GITHUB_RELEASE_BASE}/Shinro.Wa.Cho.Ginga.mp3`,
    audioUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Shinro.Wa.Cho.Ginga.mp3`,
    lyricsUrl: `${GITHUB_RELEASE_BASE}/Shinro.Wa.Chō.Ginga.lrc`,
    lyricsUrlFallback: `${CDN_MIRROR}${GITHUB_RELEASE_BASE}/Shinro.Wa.Chō.Ginga.lrc`,
  },
];

// ==================== 导出工具 ====================
export const TOTAL_SONGS = songs.length;

// 按类型分组
export const songsByType = {
  个人曲: songs.filter(s => s.type === '个人曲'),
  组合曲: songs.filter(s => s.type === '组合曲'),
  团体曲: songs.filter(s => s.type === '团体曲'),
  全体曲: songs.filter(s => s.type === '全体曲'),
};

// 按组合分组
export const songsByUnit: Record<string, Song[]> = {};
songs.forEach(s => {
  if (s.unit) {
    if (!songsByUnit[s.unit]) songsByUnit[s.unit] = [];
    songsByUnit[s.unit].push(s);
  }
});
