/**
 * 偶像大师闪耀色彩 - 角色基础数据
 *
 * 包含28位偶像的基础情报
 * 详细人设存储在世界书中
 */

import type { Idol, UnitName } from '../类型/游戏数据类型';

/**
 * 所有偶像数据
 */
export const IDOLS: Idol[] = [
  // ==================== illumination STARS ====================
  {
    id: 'mano',
    name: '樱木真乃',
    unit: 'illumination STARS',
    age: 16,
    birthday: '4月25日',
    zodiac: '金牛座',
    height: 155,
    weight: 48,
    handedness: '右',
    threeSize: '86 58 88',
    bloodType: 'A型',
    shoeSize: '23.5cm',
    hometown: '东京都',
    hobbies: '外出、公园晒太阳',
    skills: '被鸟喜欢',
    cv: '关根瞳',
    color: '#ffa5d4',
    description: '和蔼可亲的治愈系女孩，心地善良，易于激发保护欲的类型，仅仅待在一起就令人产生幸福感。',
  },
  {
    id: 'hiori',
    name: '风野灯织',
    unit: 'illumination STARS',
    age: 15,
    birthday: '3月4日',
    zodiac: '双鱼座',
    height: 154,
    weight: 43,
    handedness: '右',
    threeSize: '75 55 78',
    bloodType: 'A型',
    shoeSize: '',
    hometown: '东京都',
    hobbies: '音乐鉴赏、探寻美景、占卜',
    skills: '料理、日程管理',
    cv: '近藤玲奈',
    color: '#6495cf',
    description: '扎在头后的黑发给人深刻印象的高冷系美少女，在得到自己认可之前不吝惜努力的克己的性格。',
  },
  {
    id: 'meguru',
    name: '八宫巡',
    unit: 'illumination STARS',
    age: 16,
    birthday: '7月22日',
    zodiac: '巨蟹座',
    height: 157,
    weight: 46,
    handedness: '右',
    threeSize: '90 59 89',
    bloodType: 'O型',
    shoeSize: '23.5cm',
    hometown: '美国 马萨诸塞州',
    hobbies: '与人交谈、活动身体',
    skills: '运动全能',
    cv: '峰田茉优',
    color: '#fff03c',
    description: '性格天真烂漫，无论对方是谁都会积极地搭话。富有活力、爱为朋友着想的女孩。',
  },

  // ==================== L'Antica ====================
  {
    id: 'kogane',
    name: '月冈恋钟',
    unit: "L'Antica",
    age: 19,
    birthday: '2月25日',
    zodiac: '双鱼座',
    height: 165,
    weight: 58,
    handedness: '左',
    threeSize: '93 60 91',
    bloodType: 'B型',
    shoeSize: '24.5cm',
    hometown: '长崎县',
    hobbies: '俺的料理，不管怎样都是超赞的啦！',
    skills: '有办法画出超像的肖像画的说！',
    cv: '𥐟部花凛',
    color: '#ff7f27',
    description:
      '长崎县佐世保市出身的19岁女孩，自信满满无论什么情况都积极乐观的性格，拥有引人注目的可爱程度与好身材，但也有着笨手笨脚的一面。',
  },
  {
    id: 'mamimi',
    name: '田中摩美美',
    unit: "L'Antica",
    age: 18,
    birthday: '5月24日',
    zodiac: '双子座',
    height: 161,
    weight: 49,
    handedness: '右',
    threeSize: '81 56 83',
    bloodType: 'B型',
    shoeSize: '23.5cm',
    hometown: '神奈川县',
    hobbies: '流浪、戏弄人',
    skills: '剪自己的头发',
    cv: '菅沼千纱',
    color: '#66cdaa',
    description:
      '讨厌麻烦事的消极系朋克女孩。虽然是论身材与颜值都算出类拔萃的美少女，但对自己感兴趣的事情以外都漫不经心。',
  },
  {
    id: 'sakuya',
    name: '白濑咲耶',
    unit: "L'Antica",
    age: 18,
    birthday: '6月27日',
    zodiac: '巨蟹座',
    height: 175,
    weight: 60,
    handedness: '右',
    threeSize: '91 58 87',
    bloodType: 'A型',
    shoeSize: '24.5cm',
    hometown: '高知县',
    hobbies: '去不同的地方',
    skills: '能摆出酷炫的姿势',
    cv: '八卷安奈',
    color: '#f8b62d',
    description:
      '在女校就读的高中3年生。男子气的外表与举止加上运动万能，学业优秀，面容秀丽的高配置，在女孩子之间很受欢迎。',
  },
  {
    id: 'yuika',
    name: '三峰结华',
    unit: "L'Antica",
    age: 19,
    birthday: '1月16日',
    zodiac: '摩羯座',
    height: 158,
    weight: 44,
    handedness: '右',
    threeSize: '73 52 81',
    bloodType: 'O型',
    shoeSize: '',
    hometown: '福岛县',
    hobbies: '观赏偶像表演、摄影、游戏、动画、读书',
    skills: '学习、很快地让喜欢的偶像认识自己',
    cv: '成海瑠奈→希水汐',
    color: '#ad72bf',
    description: '大学一年级生，性格自由奔放，言谈轻浮难以捉摸，拥有时尚、动漫、游戏、摄影等广泛爱好的亚文化眼镜女子。',
  },
  {
    id: 'kiriko',
    name: '幽谷雾子',
    unit: "L'Antica",
    age: 17,
    birthday: '9月23日',
    zodiac: '天秤座',
    height: 160,
    weight: 51,
    handedness: '左',
    threeSize: '79 55 81',
    bloodType: 'AB型',
    shoeSize: '24.0cm',
    hometown: '青森县',
    hobbies: '收集可爱的东西、手工艺、献血',
    skills: '漂亮地缠绷带、不发出脚步声、削苹果皮',
    cv: '结名美月',
    color: '#d3dde9',
    description: '散发出神秘气场的银发女孩。特征是梦幻的气质和一圈圈包在身上的绷带。虽然话语不多，但心地善良。',
  },

  // ==================== 放学后CLIMAX GIRLS ====================
  {
    id: 'kaho',
    name: '小宫果穗',
    unit: 'Houkago Climax Girls',
    age: 12,
    birthday: '7月29日',
    zodiac: '狮子座',
    height: 163,
    weight: 45,
    handedness: '右',
    threeSize: '80 57 83',
    bloodType: 'A型',
    shoeSize: '',
    hometown: '东京都',
    hobbies: '看星期天早上的儿童节目、收集周边商品',
    skills: '记住了很多喜欢的节目的经典台词',
    cv: '河野日和',
    color: '#ea5550',
    description: '有着早熟的外表与身高的女孩。对什么都兴致勃勃的纯真姿态就好像小狗一样。非常喜欢特摄对英雄充满憧憬。',
  },
  {
    id: 'chiyoko',
    name: '园田智代子',
    unit: 'Houkago Climax Girls',
    age: 17,
    birthday: '2月24日',
    zodiac: '双鱼座',
    height: 149,
    weight: 46,
    handedness: '右',
    threeSize: '85 56 82',
    bloodType: 'A型',
    shoeSize: '23.0cm',
    hometown: '千叶县',
    hobbies: '探访甜品店',
    skills: '能吃很多',
    cv: '白石晴香',
    color: '#8c5333',
    description:
      '哪个班上都会有一个的普通女孩。开朗易于亲近的性格，非常喜欢吃甜食。借着名字的谐音，把喜欢巧克力的偶像作为自己的卖点。',
  },
  {
    id: 'juri',
    name: '西城树里',
    unit: 'Houkago Climax Girls',
    age: 17,
    birthday: '11月26日',
    zodiac: '射手座',
    height: 160,
    weight: 48,
    handedness: '右',
    threeSize: '75 58 78',
    bloodType: 'O型',
    shoeSize: '',
    hometown: '神奈川',
    hobbies: '外国音乐、游戏',
    skills: '各类运动、（到初二为止）篮球',
    cv: '永井真里子',
    color: '#75c7c4',
    description: '酷酷的假小子女孩。常因说话语气粗暴遭人畏惧，但骨子里十分纯情，怕害羞而坦率不起来的类型。',
  },
  {
    id: 'rinze',
    name: '杜野凛世',
    unit: 'Houkago Climax Girls',
    age: 16,
    birthday: '10月19日',
    zodiac: '天秤座',
    height: 155,
    weight: 44,
    handedness: '左',
    threeSize: '70 54 78',
    bloodType: '',
    shoeSize: '',
    hometown: '鸟取县',
    hobbies: '少女漫画、全部艺道',
    skills: '折纸、百人一首',
    cv: '丸冈和佳奈',
    color: '#ee82ee',
    description: '伫立的身姿沉静优雅的大和抚子。彬彬有礼，甘居人后的性格。有着少女漫画这样意外的爱好。',
  },
  {
    id: 'natsuha',
    name: '有栖川夏叶',
    unit: 'Houkago Climax Girls',
    age: 20,
    birthday: '8月16日',
    zodiac: '狮子座',
    height: 168,
    weight: 49,
    handedness: '右',
    threeSize: '85 58 84',
    bloodType: 'B型',
    shoeSize: '',
    hometown: '爱知',
    hobbies: '健身、伸展',
    skills: '服饰搭配',
    cv: '凉本秋穗',
    color: '#ffe012',
    description: '生于富裕家庭的社长千金。以自己的家名为傲，同时也为了不坠家声时时勤于锻炼。身材挺拔紧致。',
  },

  // ==================== ALSTROEMERIA ====================
  {
    id: 'amana',
    name: '大崎甘奈',
    unit: 'Alstroemeria',
    age: 17,
    birthday: '12月25日',
    zodiac: '摩羯座',
    height: 159,
    weight: 43,
    handedness: '右',
    threeSize: '80 56 80',
    bloodType: 'A型',
    shoeSize: '',
    hometown: '富山县',
    hobbies: '购物、美甲、自拍',
    skills: '早起、勤俭节约',
    cv: '黑木穗乃香',
    color: '#ff7fb1',
    description:
      '大崎双子中的妹妹。无论对谁都能不加排斥对待的天真烂漫的辣妹。尽全力享受只有现在才能做的事的正当下女孩。',
  },
  {
    id: 'tenka',
    name: '大崎甜花',
    unit: 'Alstroemeria',
    age: 17,
    birthday: '12月25日',
    zodiac: '摩羯座',
    height: 159,
    weight: 44,
    handedness: '右',
    threeSize: '81 58 83',
    bloodType: 'A型',
    shoeSize: '',
    hometown: '富山县',
    hobbies: '睡午觉、浏览网络、动画、游戏',
    skills: '没什么特别的',
    cv: '前川凉子',
    color: '#6fb7d4',
    description: '大崎双子中的姐姐。从小就被甘奈照顾。不擅长和人说话，有很多看动画、打游戏这种室内派的爱好。',
  },
  {
    id: 'chiyuki',
    name: '桑山千雪',
    unit: 'Alstroemeria',
    age: 23,
    birthday: '4月18日',
    zodiac: '白羊座',
    height: 163,
    weight: 47,
    handedness: '右',
    threeSize: '89 58 92',
    bloodType: 'A型',
    shoeSize: '',
    hometown: '山口县',
    hobbies: '小饰品制作',
    skills: '裁缝、认路',
    cv: '芝崎典子',
    color: '#89c3eb',
    description:
      '温柔的笑容令人印象深刻， 的大姐姐般的存在。特征是富有母性的娴静气质。心灵手巧，兴趣是亲手制作可爱的小饰品。',
  },

  // ==================== Straylight ====================
  {
    id: 'asahi',
    name: '芹泽朝日',
    unit: 'Straylight',
    age: 14,
    birthday: '1月4日',
    zodiac: '摩羯座',
    height: 153,
    weight: 47,
    handedness: '两利',
    threeSize: '78 58 77',
    bloodType: 'AB型',
    shoeSize: '',
    hometown: '东京',
    hobbies: '人类观察、搭话',
    skills: '记忆力好',
    cv: '田中有纪',
    color: '#ffe539',
    description:
      '总是在寻找有趣的东西，怎么也静不下来的富有探究欲的女孩。对感兴趣的东西会一直线地猛冲，但也有着容易厌倦的一面的初中2年生。',
  },
  {
    id: 'fuyuko',
    name: '黛冬优子',
    unit: 'Straylight',
    age: 19,
    birthday: '12月4日',
    zodiac: '射手座',
    height: 163,
    weight: 55,
    handedness: '右',
    threeSize: '78 59 81',
    bloodType: 'A型',
    shoeSize: '',
    hometown: '茨城县',
    hobbies: '和朋友聊天♪',
    skills: '和大家友好相处♪',
    cv: '幸村惠理',
    color: '#5c68a5',
    description: '脸上常带含蓄的笑容，貌似十分清纯的女孩。非常喜欢可爱的东西，采取对周围体贴周到等易受人喜爱的举动。',
  },
  {
    id: 'mei',
    name: '和泉爱依',
    unit: 'Straylight',
    age: 18,
    birthday: '8月2日',
    zodiac: '狮子座',
    height: 162,
    weight: 51,
    handedness: '右',
    threeSize: '90 58 88',
    bloodType: 'O型',
    shoeSize: '',
    hometown: '埼玉',
    hobbies: '和朋友游玩，听时下的音乐',
    skills: '可以打几个小时电话',
    cv: '北原沙弥香',
    color: '#ff85b6',
    description: '活泼、乐天又有些粗枝大叶的女孩。不擅长思考复杂问题，但非常易于亲近的高中3年生。',
  },

  // ==================== noctchill ====================
  {
    id: 'toru',
    name: '浅仓透',
    unit: 'noctchill',
    age: 17,
    birthday: '5月4日',
    zodiac: '金牛座',
    height: 160,
    weight: 50,
    handedness: '右',
    threeSize: '82 57 78',
    bloodType: 'B型',
    shoeSize: '',
    hometown: '东京',
    hobbies: '观看电影电视剧',
    skills: '记住他人相貌',
    cv: '和久井优',
    color: '#a0d8ef',
    description:
      '不加修饰保持自然的性格。不怎么在意被周围的人怎么看，豁达又自由自在。然而拥有着让谁都会被吸引的满溢着透明感的独特气场。',
  },
  {
    id: 'madoka',
    name: '樋口圆香',
    unit: 'noctchill',
    age: 17,
    birthday: '10月27日',
    zodiac: '天蝎座',
    height: 159,
    weight: 47,
    handedness: '右',
    threeSize: '79 55 79',
    bloodType: 'B型',
    shoeSize: '',
    hometown: '东京',
    hobbies: '并没有',
    skills: '并没有',
    cv: '土屋李央',
    color: '#917347',
    description: '酷酷的爱讽刺的高中二年生。清爽的长眼角和泪痣是特征。对制作人态度冷淡。',
  },
  {
    id: 'koito',
    name: '福丸小糸',
    unit: 'noctchill',
    age: 16,
    birthday: '11月11日',
    zodiac: '天蝎座',
    height: 148,
    weight: 42,
    handedness: '右',
    threeSize: '71 54 73',
    bloodType: 'O型',
    shoeSize: '',
    hometown: '东京',
    hobbies: '读书',
    skills: '学习',
    cv: '田岛纱兰',
    color: '#ffb6c1',
    description: '认生又窝里横的小动物系女孩。认真勤勉，擅长学习。容易被骗，经常被青梅竹马捉弄。',
  },
  {
    id: 'hinana',
    name: '市川雏菜',
    unit: 'noctchill',
    age: 15,
    birthday: '3月17日',
    zodiac: '双鱼座',
    height: 165,
    weight: 56,
    handedness: '左',
    threeSize: '87 60 86',
    bloodType: 'A型',
    shoeSize: '',
    hometown: '神奈川',
    hobbies: '无论什么都挺喜欢～',
    skills: '无论什么都挺擅长～',
    cv: '冈咲美保',
    color: '#f7b977',
    description: '向着自己认定的"幸福"直冲的奔放女孩。喜欢青梅竹马的学姐透。',
  },

  // ==================== SHHis ====================
  {
    id: 'nichika',
    name: '七草日花',
    unit: 'SHHis',
    age: 16,
    birthday: '7月26日',
    zodiac: '狮子座',
    height: 158,
    weight: 48,
    handedness: '右',
    threeSize: '82 55 84',
    bloodType: 'O型',
    shoeSize: '',
    hometown: '埼玉',
    hobbies: '音乐鉴赏',
    skills: '家事',
    cv: '紫月杏朱彩',
    color: '#fa8072',
    description: '个性要强同时又很会撒娇的"大家的妹妹"。对偶像有强烈的憧憬，也能窥见其不愿妥协的执着和好胜的一面。',
  },
  {
    id: 'mikoto',
    name: '绯田美琴',
    unit: 'SHHis',
    age: 24,
    birthday: '9月8日',
    zodiac: '处女座',
    height: 170,
    weight: 54,
    handedness: '右',
    threeSize: '85 57 85',
    bloodType: 'B型',
    shoeSize: '',
    hometown: '北海道',
    hobbies: '作词作曲',
    skills: '舞蹈编排',
    cv: '山根绮',
    color: '#d4a5a5',
    description:
      '尽管是位专心致志的美人，但对于吃饭睡觉等身边琐事却很凑合。拥有从事偶像工作的经验，对于"偶像"的执着胜过任何人。',
  },

  // ==================== CoMETIK ====================
  {
    id: 'luca',
    name: '斑鸠路加',
    unit: 'CoMETIK',
    age: 20,
    birthday: '1月31日',
    zodiac: '水瓶座',
    height: 161,
    weight: 44,
    handedness: '左',
    threeSize: '76 54 78',
    bloodType: 'A型',
    shoeSize: '',
    hometown: '神奈川县',
    hobbies: '无',
    skills: '无',
    cv: '川口莉奈',
    color: '#8b4513',
    description: '受到部分身陷烦恼的现代女性视为"神"一般的狂热崇拜，尽管常以粗暴的言行威吓旁人，也具有内心脆弱的一面。',
  },
  {
    id: 'hana',
    name: '铃木羽那',
    unit: 'CoMETIK',
    age: 18,
    birthday: '10月2日',
    zodiac: '天秤座',
    height: 158,
    weight: 49,
    handedness: '右',
    threeSize: '84 58 82',
    bloodType: 'O型',
    shoeSize: '',
    hometown: '冈山县',
    hobbies: '散步',
    skills: '以很美味的感觉吃东西',
    cv: '三川华月',
    color: '#f7e7ce',
    description: '开朗文静，同时又率直的女孩，内在与外表都可称人见人爱，可谓是"天生的偶像"。',
  },
  {
    id: 'haruki',
    name: '郁田阳希',
    unit: 'CoMETIK',
    age: 17,
    birthday: '4月5日',
    zodiac: '白羊座',
    height: 156,
    weight: 47,
    handedness: '右',
    threeSize: '82 57 83',
    bloodType: 'AB型',
    shoeSize: '',
    hometown: '长野县',
    hobbies: '逛街，收拾整理',
    skills: '画插画',
    cv: '小泽丽那',
    color: '#ffe4b5',
    description:
      '甜美的笑容和蓬松的短发显得十分可爱的女孩。感性丰富非常喜欢发挥创意。 一旦灵光乍现就会果断地投身于其中，有着这样积极的一面的高中二年生。',
  },
];

/**
 * 根据ID获取偶像数据
 */
export function getIdolById(id: string): Idol | undefined {
  return IDOLS.find(idol => idol.id === id);
}

/**
 * 根据名字获取偶像数据
 */
export function getIdolByName(name: string): Idol | undefined {
  return IDOLS.find(idol => idol.name === name);
}

/**
 * 根据组合获取偶像列表
 */
export function getIdolsByUnit(unit: UnitName): Idol[] {
  return IDOLS.filter(idol => idol.unit === unit);
}

/**
 * 获取所有组合名称
 */
export function getAllUnits(): UnitName[] {
  return Array.from(new Set(IDOLS.map(idol => idol.unit)));
}
