/**
 * "星月夜を歩いて" 限定卡池
 * 
 * UP角色：【絵空靴】杜野凛世
 * 总卡片数：171 张
 * 
 * 稀有度分布：
 * - UR: 3 张 (1 UP + 2 常驻)
 * - SSR: 124 张
 * - SR: 44 张
 * 
 * @generated 此文件由脚本自动生成 (2025-11-01T12:35:51.190Z)
 */

import type { RealCard } from '../../types';

const CDN_BASE = 'https://raw.githubusercontent.com/2426269/shinycolors-assets-cdn/main';
const CARD_IMAGE_BASE = `${CDN_BASE}/角色卡面`;
const POOL_IMAGE_BASE = `${CDN_BASE}/卡池缩略图`;

/**
 * UP角色 (isPickup: true)
 */
export const PICKUP_CARD: RealCard = {
    fullName: '【絵空靴】杜野凛世',
    theme: '絵空靴',
    character: '杜野凛世',
    baseImage: '絵空靴 杜野凛世.webp',
    awakenedImage: '絵空靴 杜野凛世+.webp',
    rarity: 'UR' as const,
  isPickup: true,
  };

/**
 * 卡池内所有可抽取的卡片（不包括UP角色）
 * 包含: 2 张 UR + 124 张 SSR + 44 张 SR
 */
export const POOL_CARDS: RealCard[] = [
  // ========== UR 卡 (2 张) ==========
{
    fullName: '【誘爆ハートビート】黛冬優子',
    theme: '誘爆ハートビート',
    character: '黛冬優子',
    baseImage: '誘爆ハートビート 黛冬優子.webp',
    awakenedImage: '誘爆ハートビート 黛冬優子+.webp',
    rarity: 'UR' as const,
  },
  {
    fullName: '【アマテラス】樋口円香',
    theme: 'アマテラス',
    character: '樋口円香',
    baseImage: 'アマテラス 樋口円香.webp',
    awakenedImage: 'アマテラス 樋口円香+.webp',
    rarity: 'UR' as const,
  },

  // ========== SSR 卡 (124 张) ==========
{
    fullName: '【ほわっとスマイル】櫻木真乃',
    theme: 'ほわっとスマイル',
    character: '櫻木真乃',
    baseImage: 'ほわっとスマイル 櫻木真乃.webp',
    awakenedImage: 'ほわっとスマイル 櫻木真乃+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【はじけてスマイル】櫻木真乃',
    theme: 'はじけてスマイル',
    character: '櫻木真乃',
    baseImage: 'はじけてスマイル 櫻木真乃.webp',
    awakenedImage: 'はじけてスマイル 櫻木真乃+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【ソラを跳ね】櫻木真乃',
    theme: 'ソラを跳ね',
    character: '櫻木真乃',
    baseImage: 'ソラを跳ね 櫻木真乃.webp',
    awakenedImage: 'ソラを跳ね 櫻木真乃+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【ひとつ、 はたたく】櫻木真乃',
    theme: 'ひとつ、 はたたく',
    character: '櫻木真乃',
    baseImage: 'ひとつ、 はたたく 櫻木真乃.webp',
    awakenedImage: 'ひとつ、 はたたく 櫻木真乃+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【きみと巡り行く】櫻木真乃',
    theme: 'きみと巡り行く',
    character: '櫻木真乃',
    baseImage: 'きみと巡り行く 櫻木真乃.webp',
    awakenedImage: 'きみと巡り 行く 櫻木真乃+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【柔らかな微笑み】風野灯織',
    theme: '柔らかな微笑み',
    character: '風野灯織',
    baseImage: '柔らかな微笑み 風野灯織.webp',
    awakenedImage: '柔らかな微笑み 風野灯織+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【淡雪の戯れ】風野灯織',
    theme: '淡雪の戯れ',
    character: '風野灯織',
    baseImage: '淡雪の戯れ  風野灯織 .webp',
    awakenedImage: '淡雪の戯れ 風野灯織+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【清閑に息をひそめて】風野灯織',
    theme: '清閑に息をひそめて',
    character: '風野灯織',
    baseImage: '清閑に息をひそめて 風野灯織.webp',
    awakenedImage: '清閑に息をひそめて 風野灯織+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【黒百合前で待ち合わせ】風野灯織',
    theme: '黒百合前で待ち合わせ',
    character: '風野灯織',
    baseImage: '黒百合前で待ち合わせ 風野灯織.webp',
    awakenedImage: '黒百合前で待ち合わせ 風野灯織+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【洸】風野灯織',
    theme: '洸',
    character: '風野灯織',
    baseImage: '洸  風野灯織.webp',
    awakenedImage: '洸  風野灯織+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【キミと今旅立つ】風野灯織',
    theme: 'キミと今旅立つ',
    character: '風野灯織',
    baseImage: 'キミと今旅立つ 風野灯織.webp',
    awakenedImage: 'キミと今旅立つ 風野灯織+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【金色の元気いっぱいガール】八宮めぐる',
    theme: '金色の元気いっぱいガール',
    character: '八宮めぐる',
    baseImage: '金色の元気いっぱいガール 八宮めぐる.webp',
    awakenedImage: '金色の元気いっぱいガール 八宮めぐる+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【シュカのまにまに】八宮めぐる',
    theme: 'シュカのまにまに',
    character: '八宮めぐる',
    baseImage: 'シュカのまにまに 八宮めぐる.webp',
    awakenedImage: 'シュカのまにまに 八宮めぐる+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【日々を紡ぐインヴェルノ】八宮めぐる',
    theme: '日々を紡ぐインヴェルノ',
    character: '八宮めぐる',
    baseImage: '日々を紡ぐインヴェルノ 八宮めぐる.webp',
    awakenedImage: '日々を紡ぐインヴェルノ 八宮めぐる+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【たまゆらフレーミング】八宮めぐる',
    theme: 'たまゆらフレーミング',
    character: '八宮めぐる',
    baseImage: 'たまゆらフレーミング 八宮めぐる.webp',
    awakenedImage: 'たまゆらフレーミング 八宮めぐる+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【こころレイヤリング】八宮めぐる',
    theme: 'こころレイヤリング',
    character: '八宮めぐる',
    baseImage: 'こころレイヤリング 八宮めぐる.webp',
    awakenedImage: 'こころレイヤリング 八宮めぐる+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【ばりうまかブルース】月岡恋鐘',
    theme: 'ばりうまかブルース',
    character: '月岡恋鐘',
    baseImage: 'ばりうまかブルース 月岡恋鐘.webp',
    awakenedImage: 'ばりうまかブルース 月岡恋鐘+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【風吹く丘にはよ来んね】月岡恋鐘',
    theme: '風吹く丘にはよ来んね',
    character: '月岡恋鐘',
    baseImage: '風吹く丘にはよ来んね 月岡恋鐘.webp',
    awakenedImage: '風吹く丘にはよ来んね 月岡恋鐘+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【うちのリボンは恋結び】月岡恋鐘',
    theme: 'うちのリボンは恋結び',
    character: '月岡恋鐘',
    baseImage: 'うちのリボンは恋結び 月岡恋鐘.webp',
    awakenedImage: 'うちのリボンは恋結び 月岡恋鐘+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【あなたと、月の満ちる頃】月岡恋鐘',
    theme: 'あなたと、月の満ちる頃',
    character: '月岡恋鐘',
    baseImage: 'あなたと、月の満ちる頃 月岡恋鐘.webp',
    awakenedImage: 'あなたと、月の満ちる頃 月岡恋鐘+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【よか匂いのする陽気やけん】月岡恋鐘',
    theme: 'よか匂いのする陽気やけん',
    character: '月岡恋鐘',
    baseImage: 'よか匂いのする陽気やけん 月岡恋鐘.webp',
    awakenedImage: 'よか匂いのする陽気やけん 月岡恋鐘+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【純雪エモーショナル】月岡恋鐘',
    theme: '純雪エモーショナル',
    character: '月岡恋鐘',
    baseImage: '純雪エモーショナル 月岡恋鐘.webp',
    awakenedImage: '純雪エモーショナル 月岡恋鐘+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【トリッキーナイト】田中摩美々',
    theme: 'トリッキーナイト',
    character: '田中摩美々',
    baseImage: 'トリッキーナイト 田中摩美々.webp',
    awakenedImage: 'トリッキーナイト 田中摩美々+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【摩的・アンチテーゼ】田中摩美々',
    theme: '摩的・アンチテーゼ',
    character: '田中摩美々',
    baseImage: '摩的・アンチテーゼ 田中摩美々.webp',
    awakenedImage: '摩的・アンチテーゼ 田中摩美々+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【真・TRAVELER】田中摩美々',
    theme: '真・TRAVELER',
    character: '田中摩美々',
    baseImage: '真・TRAVELER 田中摩美々.webp',
    awakenedImage: '真・TRAVELER 田中摩美々+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【アバウト-ナイト-ライト】田中摩美々',
    theme: 'アバウト-ナイト-ライト',
    character: '田中摩美々',
    baseImage: 'アバウト-ナイト-ライト 田中摩美々.webp',
    awakenedImage: 'アバウト-ナイト-ライト 田中摩美々+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【リバーシブル・トースト】田中摩美々',
    theme: 'リバーシブル・トースト',
    character: '田中摩美々',
    baseImage: 'リバーシブル・トースト 田中摩美々.webp',
    awakenedImage: 'リバーシブル・トースト 田中摩美々+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【まみみスイッチ】田中摩美々',
    theme: 'まみみスイッチ',
    character: '田中摩美々',
    baseImage: 'まみみスイッチ 田中摩美々.webp',
    awakenedImage: 'まみみスイッチ 田中摩美々+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【紺碧のボーダーライン】白瀬咲耶',
    theme: '紺碧のボーダーライン',
    character: '白瀬咲耶',
    baseImage: '紺碧のボーダーライン 白瀬咲耶.webp',
    awakenedImage: '紺碧のボーダーライン 白瀬咲耶+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【幸福のリズム】白瀬咲耶',
    theme: '幸福のリズム',
    character: '白瀬咲耶',
    baseImage: '幸福のリズム 白瀬咲耶.webp',
    awakenedImage: '幸福のリズム 白瀬咲耶+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【乙女と交わすTrick】白瀬咲耶',
    theme: '乙女と交わすTrick',
    character: '白瀬咲耶',
    baseImage: '乙女と交わすTrick 白瀬咲耶.webp',
    awakenedImage: '乙女と交わすTrick 白瀬咲耶+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【渦と淵】白瀬咲耶',
    theme: '渦と淵',
    character: '白瀬咲耶',
    baseImage: '渦と淵 白瀬咲耶.webp',
    awakenedImage: '渦と淵 白瀬咲耶+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【私をときめかせて】白瀬咲耶',
    theme: '私をときめかせて',
    character: '白瀬咲耶',
    baseImage: '私をときめかせて 白瀬咲耶.webp',
    awakenedImage: '私をときめかせて 白瀬咲耶+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【落ちる音がする】白瀬咲耶',
    theme: '落ちる音がする',
    character: '白瀬咲耶',
    baseImage: '落ちる音がする 白瀬咲耶.webp',
    awakenedImage: '落ちる音がする 白瀬咲耶+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【お試し／みつゴコロ】三峰結華',
    theme: 'お試し／みつゴコロ',
    character: '三峰結華',
    baseImage: 'お試し／みつゴコロ 三峰結華.webp',
    awakenedImage: 'お試し／みつゴコロ 三峰結華+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【それなら目をつぶりましょう】三峰結華',
    theme: 'それなら目をつぶりましょう',
    character: '三峰結華',
    baseImage: 'それなら目をつぶりましょう 三峰結華.webp',
    awakenedImage: 'それなら目をつぶりましょう 三峰結華+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【雨に祝福】三峰結華',
    theme: '雨に祝福',
    character: '三峰結華',
    baseImage: '雨に祝福 三峰結華.webp',
    awakenedImage: '雨に祝福 三峰結華+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【♡コメディ】三峰結華',
    theme: '♡コメディ',
    character: '三峰結華',
    baseImage: '♡コメディ 三峰結華.webp',
    awakenedImage: '♡コメディ 三峰結華+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【kaleidoscope-pinball】三峰結華',
    theme: 'kaleidoscope-pinball',
    character: '三峰結華',
    baseImage: 'kaleidoscope-pinball 三峰結華.webp',
    awakenedImage: 'kaleidoscope-pinball 三峰結華+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【ノー・ライフ】三峰結華',
    theme: 'ノー・ライフ',
    character: '三峰結華',
    baseImage: 'ノー・ライフ 三峰結華.webp',
    awakenedImage: 'ノー・ライフ 三峰結華+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【霧・音・燦・燦】幽谷霧子',
    theme: '霧・音・燦・燦',
    character: '幽谷霧子',
    baseImage: '霧・音・燦・燦 幽谷霧子.webp',
    awakenedImage: '霧・音・燦・燦 幽谷霧子+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【夕・音・鳴・鳴】幽谷霧子',
    theme: '夕・音・鳴・鳴',
    character: '幽谷霧子',
    baseImage: '夕・音・鳴・鳴 幽谷霧子.webp',
    awakenedImage: '夕・音・鳴・鳴 幽谷霧子+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【菜・菜・輪・舞】幽谷霧子',
    theme: '菜・菜・輪・舞',
    character: '幽谷霧子',
    baseImage: '菜・菜・輪・舞 幽谷霧子.webp',
    awakenedImage: '菜・菜・輪・舞 幽谷霧子+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【かぜかんむりのこどもたち】幽谷霧子',
    theme: 'かぜかんむりのこどもたち',
    character: '幽谷霧子',
    baseImage: 'かぜかんむりのこどもたち 幽谷霧子.webp',
    awakenedImage: 'かぜかんむりのこどもたち 幽谷霧子+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【窓・送・巡・歌】幽谷霧子',
    theme: '窓・送・巡・歌',
    character: '幽谷霧子',
    baseImage: '窓・送・巡・歌 幽谷霧子.webp',
    awakenedImage: '窓・送・巡・歌 幽谷霧子+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【白・架・祝・幻】幽谷霧子',
    theme: '白・架・祝・幻',
    character: '幽谷霧子',
    baseImage: '白・架・祝・幻 幽谷霧子.webp',
    awakenedImage: '白・架・祝・幻 幽谷霧子+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【第2形態アーマードタイプ】小宮果穂',
    theme: '第2形態アーマードタイプ',
    character: '小宮果穂',
    baseImage: '第2形態アーマードタイプ 小宮果穂.webp',
    awakenedImage: '第2形態アーマードタイプ 小宮果穂+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【新装備・バブルバスター！】小宮果穂',
    theme: '新装備・バブルバスター！',
    character: '小宮果穂',
    baseImage: '新装備・バブルバスター！ 小宮果穂.webp',
    awakenedImage: '新装備・バブルバスター！ 小宮果穂+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【潮騒のシーショア】小宮果穂',
    theme: '潮騒のシーショア',
    character: '小宮果穂',
    baseImage: '潮騒のシーショア 小宮果穂.webp',
    awakenedImage: '潮騒のシーショア 小宮果穂+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【フルスロットルエイジ！】小宮果穂',
    theme: 'フルスロットルエイジ！',
    character: '小宮果穂',
    baseImage: 'フルスロットルエイジ！ 小宮果穂.webp',
    awakenedImage: 'フルスロットルエイジ！ 小宮果穂+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【スノードーム・シンドローム】小宮果穂',
    theme: 'スノードーム・シンドローム',
    character: '小宮果穂',
    baseImage: 'スノードーム・シンドローム 小宮果穂.webp',
    awakenedImage: 'スノードーム・シンドローム 小宮果穂+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【両手に兄！】小宮果穂',
    theme: '両手に兄！',
    character: '小宮果穂',
    baseImage: '両手に兄！ 小宮果穂.webp',
    awakenedImage: '両手に兄！ 小宮果穂+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【ちょこ色×きらきらロマン】園田智代子',
    theme: 'ちょこ色×きらきらロマン',
    character: '園田智代子',
    baseImage: 'ちょこ色×きらきらロマン 園田智代子.webp',
    awakenedImage: 'ちょこ色×きらきらロマン 園田智代子+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【あそ→と♥ちよこれいと】園田智代子',
    theme: 'あそ→と♥ちよこれいと',
    character: '園田智代子',
    baseImage: 'あそ→と♥ちよこれいと 園田智代子.webp',
    awakenedImage: 'あそ→と♥ちよこれいと 園田智代子+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【砂糖づけ・ビターエンド】園田智代子',
    theme: '砂糖づけ・ビターエンド',
    character: '園田智代子',
    baseImage: '砂糖づけ・ビターエンド 園田智代子.webp',
    awakenedImage: '砂糖づけ・ビターエンド 園田智代子+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【うつくしいあした】園田智代子',
    theme: 'うつくしいあした',
    character: '園田智代子',
    baseImage: 'うつくしいあした 園田智代子.webp',
    awakenedImage: 'うつくしいあした 園田智代子+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【Kn☆cking. Kn☆cking.】園田智代子',
    theme: 'Kn☆cking. Kn☆cking.',
    character: '園田智代子',
    baseImage: 'Kn☆cking. Kn☆cking. 園田智代子.webp',
    awakenedImage: 'Kn☆cking. Kn☆cking. 園田智代子+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【ラムネ色の覚悟】西城樹里',
    theme: 'ラムネ色の覚悟',
    character: '西城樹里',
    baseImage: 'ラムネ色の覚悟 西城樹里.webp',
    awakenedImage: 'ラムネ色の覚悟 西城樹里+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【曲がり角のランウェイ】西城樹里',
    theme: '曲がり角のランウェイ',
    character: '西城樹里',
    baseImage: '曲がり角のランウェイ 西城樹里.webp',
    awakenedImage: '曲がり角のランウェイ 西城樹里+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【秋陽のスケッチ】西城樹里',
    theme: '秋陽のスケッチ',
    character: '西城樹里',
    baseImage: '秋陽のスケッチ 西城樹里.webp',
    awakenedImage: '秋陽のスケッチ 西城樹里+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【I・OWE・U】西城樹里',
    theme: 'I・OWE・U',
    character: '西城樹里',
    baseImage: 'I・OWE・U 西城樹里.webp',
    awakenedImage: 'I・OWE・U 西城樹里+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【花染む街で、君と】西城樹里',
    theme: '花染む街で、君と',
    character: '西城樹里',
    baseImage: '花染む街で、君と 西城樹里.webp',
    awakenedImage: '花染む街で、君と 西城樹里+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【杜野凛世の印象派】杜野凛世',
    theme: '杜野凛世の印象派',
    character: '杜野凛世',
    baseImage: '杜野凛世の印象派 杜野凛世.webp',
    awakenedImage: '杜野凛世の印象派 杜野凛世+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【凛世花伝】杜野凛世',
    theme: '凛世花伝',
    character: '杜野凛世',
    baseImage: '凛世花伝 杜野凛世.webp',
    awakenedImage: '凛世花伝 杜野凛世+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【水色感情】杜野凛世',
    theme: '水色感情',
    character: '杜野凛世',
    baseImage: '水色感情 杜野凛世.webp',
    awakenedImage: '水色感情 杜野凛世+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【ロー・ポジション】杜野凛世',
    theme: 'ロー・ポジション',
    character: '杜野凛世',
    baseImage: 'ロー・ポジション 杜野凛世.webp',
    awakenedImage: 'ロー・ポジション 杜野凛世+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【硝子少女】杜野凛世',
    theme: '硝子少女',
    character: '杜野凛世',
    baseImage: '硝子少女 杜野凛世.webp',
    awakenedImage: '硝子少女 杜野凛世+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【片恋はあと】杜野凛世',
    theme: '片恋はあと',
    character: '杜野凛世',
    baseImage: '片恋はあと 杜野凛世.webp',
    awakenedImage: '片恋はあと 杜野凛世+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【アルティメットマーメイド】有栖川夏葉',
    theme: 'アルティメットマーメイド',
    character: '有栖川夏葉',
    baseImage: 'アルティメットマーメイド 有栖川夏葉.webp',
    awakenedImage: 'アルティメットマーメイド 有栖川夏葉+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【メイドインナツハ】有栖川夏葉',
    theme: 'メイドインナツハ',
    character: '有栖川夏葉',
    baseImage: 'メイドインナツハ 有栖川夏葉.webp',
    awakenedImage: 'メイドインナツハ 有栖川夏葉+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【♡AKQJ10】有栖川夏葉',
    theme: '♡AKQJ10',
    character: '有栖川夏葉',
    baseImage: '♡AKQJ10 有栖川夏葉.webp',
    awakenedImage: '♡AKQJ10 有栖川夏葉+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【Fall】有栖川夏葉',
    theme: 'Fall',
    character: '有栖川夏葉',
    baseImage: 'Fall 有栖川夏葉.webp',
    awakenedImage: 'Fall 有栖川夏葉+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【Birdy BUddy】有栖川夏葉',
    theme: 'Birdy BUddy',
    character: '有栖川夏葉',
    baseImage: 'Birdy BUddy 有栖川夏葉.webp',
    awakenedImage: 'Birdy BUddy 有栖川夏葉+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【スタンバイオッケー】大崎甘奈',
    theme: 'スタンバイオッケー',
    character: '大崎甘奈',
    baseImage: 'スタンバイオッケー 大崎甘奈.webp',
    awakenedImage: 'スタンバイオッケー 大崎甘奈+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【ゆらゆらアクアリウム】大崎甘奈',
    theme: 'ゆらゆらアクアリウム',
    character: '大崎甘奈',
    baseImage: 'ゆらゆらアクアリウム 大崎甘奈.webp',
    awakenedImage: 'ゆらゆらアクアリウム 大崎甘奈+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【叶えて☆ゴールドフィッシュ】大崎甘奈',
    theme: '叶えて☆ゴールドフィッシュ',
    character: '大崎甘奈',
    baseImage: '叶えて☆ゴールドフィッシュ 大崎甘奈.webp',
    awakenedImage: '叶えて☆ゴールドフィッシュ 大崎甘奈+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【longing】大崎甘奈',
    theme: 'longing',
    character: '大崎甘奈',
    baseImage: 'longing  大崎甘奈.webp',
    awakenedImage: 'longing  大崎甘奈+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【すれちがいシアター】大崎甘奈',
    theme: 'すれちがいシアター',
    character: '大崎甘奈',
    baseImage: 'すれちがいシアター 大崎甘奈.webp',
    awakenedImage: 'すれちがいシアター 大崎甘奈+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【事務所。静寂。大輪の華】大崎甜花',
    theme: '事務所。静寂。大輪の華',
    character: '大崎甜花',
    baseImage: '事務所。静寂。大輪の華 大崎甜花.webp',
    awakenedImage: '事務所。静寂。大輪の華 大崎甜花+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【I♡DOLL】大崎甜花',
    theme: 'I♡DOLL',
    character: '大崎甜花',
    baseImage: 'I♡DOLL 大崎甜花.webp',
    awakenedImage: 'I♡DOLL 大崎甜花+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【BON・BON・DAY！】大崎甜花',
    theme: 'BON・BON・DAY！',
    character: '大崎甜花',
    baseImage: 'BON・BON・DAY！ 大崎甜花.webp',
    awakenedImage: 'BON・BON・DAY！ 大崎甜花+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【バス・タイムの気分で】大崎甜花',
    theme: 'バス・タイムの気分で',
    character: '大崎甜花',
    baseImage: 'バス・タイムの気分で 大崎甜花.webp',
    awakenedImage: 'バス・タイムの気分で 大崎甜花+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【甜der Dream Show】大崎甜花',
    theme: '甜der Dream Show',
    character: '大崎甜花',
    baseImage: '甜der Dream Show 大崎甜花.webp',
    awakenedImage: '甜der Dream Show 大崎甜花+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【マイ・ピュア・ロマンス】桑山千雪',
    theme: 'マイ・ピュア・ロマンス',
    character: '桑山千雪',
    baseImage: 'マイ・ピュア・ロマンス 桑山千雪.webp',
    awakenedImage: 'マイ・ピュア・ロマンス 桑山千雪+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【シークレット・ヒロイン】桑山千雪',
    theme: 'シークレット・ヒロイン',
    character: '桑山千雪',
    baseImage: 'シークレット・ヒロイン 桑山千雪.webp',
    awakenedImage: 'シークレット・ヒロイン 桑山千雪+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【はるかぜまち、1番地】桑山千雪',
    theme: 'はるかぜまち、1番地',
    character: '桑山千雪',
    baseImage: 'はるかぜまち、1番地 桑山千雪.webp',
    awakenedImage: 'はるかぜまち、1番地 桑山千雪+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【つよがりのためのララバイ】桑山千雪',
    theme: 'つよがりのためのララバイ',
    character: '桑山千雪',
    baseImage: 'つよがりのためのララバイ 桑山千雪.webp',
    awakenedImage: 'つよがりのためのララバイ 桑山千雪+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【剥がされて、虚ろ】桑山千雪',
    theme: '剥がされて、虚ろ',
    character: '桑山千雪',
    baseImage: '剥がされて、虚ろ 桑山千雪.webp',
    awakenedImage: '剥がされて、虚ろ 桑山千雪+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【ジャンプ！スタッグ！！！】芹沢あさひ',
    theme: 'ジャンプ！スタッグ！！！',
    character: '芹沢あさひ',
    baseImage: 'ジャンプ！スタッグ！！！ 芹沢あさひ.webp',
    awakenedImage: 'ジャンプ！スタッグ！！！ 芹沢あさひ+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【不機嫌なテーマパーク】芹沢あさひ',
    theme: '不機嫌なテーマパーク',
    character: '芹沢あさひ',
    baseImage: '不機嫌なテーマパーク 芹沢あさひ.webp',
    awakenedImage: '不機嫌なテーマパーク 芹沢あさひ+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【光は光へ】芹沢あさひ',
    theme: '光は光へ',
    character: '芹沢あさひ',
    baseImage: '光は光へ 芹沢あさひ.webp',
    awakenedImage: '光は光へ 芹沢あさひ+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【ムーンライト・ガーデン】芹沢あさひ',
    theme: 'ムーンライト・ガーデン',
    character: '芹沢あさひ',
    baseImage: 'ムーンライト・ガーデン 芹沢あさひ.webp',
    awakenedImage: 'ムーンライト・ガーデン 芹沢あさひ+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【オ♡フ♡レ♡コ】黛冬優子',
    theme: 'オ♡フ♡レ♡コ',
    character: '黛冬優子',
    baseImage: 'オ♡フ♡レ♡コ 黛冬優子.webp',
    awakenedImage: 'オ♡フ♡レ♡コ 黛冬優子+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【starring F】黛冬優子',
    theme: 'starring F',
    character: '黛冬優子',
    baseImage: 'starring F 黛冬優子.webp',
    awakenedImage: 'starring F 黛冬優子+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【ノンセンス・プロンプ】黛冬優子',
    theme: 'ノンセンス・プロンプ',
    character: '黛冬優子',
    baseImage: 'ノンセンス・プロンプ 黛冬優子.webp',
    awakenedImage: 'ノンセンス・プロンプ 黛冬優子+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【ア・冬優子イズム】黛冬優子',
    theme: 'ア・冬優子イズム',
    character: '黛冬優子',
    baseImage: 'ア・冬優子イズム 黛冬優子.webp',
    awakenedImage: 'ア・冬優子イズム 黛冬優子+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【ちょっとあげる～】和泉愛依',
    theme: 'ちょっとあげる～',
    character: '和泉愛依',
    baseImage: 'ちょっとあげる～ 和泉愛依.webp',
    awakenedImage: 'ちょっとあげる～ 和泉愛依+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【メイ・ビー】和泉愛依',
    theme: 'メイ・ビー',
    character: '和泉愛依',
    baseImage: 'メイ・ビー 和泉愛依.webp',
    awakenedImage: 'メイ・ビー 和泉愛依+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【今のうちは走らない】和泉愛依',
    theme: '今のうちは走らない',
    character: '和泉愛依',
    baseImage: '今のうちは走らない 和泉愛依.webp',
    awakenedImage: '今のうちは走らない 和泉愛依+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【うちと幸せ】和泉愛依',
    theme: 'うちと幸せ',
    character: '和泉愛依',
    baseImage: 'うちと幸せ 和泉愛依.webp',
    awakenedImage: 'うちと幸せ 和泉愛依+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【あたし・マスト】和泉愛依',
    theme: 'あたし・マスト',
    character: '和泉愛依',
    baseImage: 'あたし・マスト 和泉愛依.webp',
    awakenedImage: 'あたし・マスト 和泉愛依+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【10個、光】浅倉透',
    theme: '10個、光',
    character: '浅倉透',
    baseImage: '10個、光 浅倉透.webp',
    awakenedImage: '10個、光 浅倉透+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【夜はなにいろ】浅倉透',
    theme: '夜はなにいろ',
    character: '浅倉透',
    baseImage: '夜はなにいろ 浅倉透.webp',
    awakenedImage: '夜はなにいろ 浅倉透+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【雪あたりの季節】浅倉透',
    theme: '雪あたりの季節',
    character: '浅倉透',
    baseImage: '雪あたりの季節 浅倉透.webp',
    awakenedImage: '雪あたりの季節 浅倉透+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【カラカラカラ】樋口円香',
    theme: 'カラカラカラ',
    character: '樋口円香',
    baseImage: 'カラカラカラ 樋口円香.webp',
    awakenedImage: 'カラカラカラ 樋口円香+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【オイサラバエル】樋口円香',
    theme: 'オイサラバエル',
    character: '樋口円香',
    baseImage: 'オイサラバエル 樋口円香.webp',
    awakenedImage: 'オイサラバエル 樋口円香+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【フリークス・アリー】樋口円香',
    theme: 'フリークス・アリー',
    character: '樋口円香',
    baseImage: 'フリークス・アリー 樋口円香.webp',
    awakenedImage: 'フリークス・アリー 樋口円香+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【ポシェットの中には】福丸小糸',
    theme: 'ポシェットの中には',
    character: '福丸小糸',
    baseImage: 'ポシェットの中には 福丸小糸.webp',
    awakenedImage: 'ポシェットの中には 福丸小糸+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【てのひらの答え】福丸小糸',
    theme: 'てのひらの答え',
    character: '福丸小糸',
    baseImage: 'てのひらの答え 福丸小糸 .webp',
    awakenedImage: 'ての ひらの答え 福丸小糸+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【なつ やすみ学校】福丸小糸',
    theme: 'なつ やすみ学校',
    character: '福丸小糸',
    baseImage: 'なつ やすみ学校 福丸小糸.webp',
    awakenedImage: 'なつや すみ学校 福丸小糸+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【窓をあけて】福丸小糸',
    theme: '窓をあけて',
    character: '福丸小糸',
    baseImage: '窓をあけて 福丸小糸.webp',
    awakenedImage: '窓をあけて 福丸小糸+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【HAPPY-!NG】市川雛菜',
    theme: 'HAPPY-!NG',
    character: '市川雛菜',
    baseImage: 'HAPPY-!NG 市川雛菜.webp',
    awakenedImage: 'HAPPY-!NG 市川雛菜+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【♡LOG】市川雛菜',
    theme: '♡LOG',
    character: '市川雛菜',
    baseImage: '♡LOG 市川雛菜.webp',
    awakenedImage: '♡LOG 市川雛菜+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【S!GNATURE】市川雛菜',
    theme: 'S!GNATURE',
    character: '市川雛菜',
    baseImage: 'S!GNATURE 市川雛菜.webp',
    awakenedImage: 'S!GNATURE 市川雛菜+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【Keep→it up♡】市川雛菜',
    theme: 'Keep→it up♡',
    character: '市川雛菜',
    baseImage: 'Keep→it up♡ 市川雛菜.webp',
    awakenedImage: 'Keep→it up♡ 市川雛菜+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【♡まっクろはムウサぎ♡】七草にちか',
    theme: '♡まっクろはムウサぎ♡',
    character: '七草にちか',
    baseImage: '♡まっクろはムウサぎ♡ 七草にちか.webp',
    awakenedImage: '♡まっクろはムウサぎ♡ 七草にちか+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【夜よこノ窓は塗らないデ】七草にちか',
    theme: '夜よこノ窓は塗らないデ',
    character: '七草にちか',
    baseImage: '夜よこノ窓は塗らないデ 七草にちか.webp',
    awakenedImage: '夜よこノ窓は塗らないデ 七草にちか+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【伝えテ niiid U】七草にちか',
    theme: '伝えテ niiid U',
    character: '七草にちか',
    baseImage: '伝えテ niiid U 七草にちか.webp',
    awakenedImage: '伝えテ niiid U 七草にちか+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【受けトル sun Q】七草にちか',
    theme: '受けトル sun Q',
    character: '七草にちか',
    baseImage: '受けトル sun Q 七草にちか.webp',
    awakenedImage: '受けトル sun Q 七草にちか+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【ROUNDLY】緋田美琴',
    theme: 'ROUNDLY',
    character: '緋田美琴',
    baseImage: 'ROUNDLY 緋田美琴.webp',
    awakenedImage: 'ROUNDLY 緋田美琴+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【CHILLY】緋田美琴',
    theme: 'CHILLY',
    character: '緋田美琴',
    baseImage: 'CHILLY 緋田美琴.webp',
    awakenedImage: 'CHILLY 緋田美琴+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【broken shout】斑鳩ルカ',
    theme: 'broken shout',
    character: '斑鳩ルカ',
    baseImage: 'broken shout 斑鳩ルカ.webp',
    awakenedImage: 'broken shout 斑鳩ルカ+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【Eyes On You】鈴木羽那',
    theme: 'Eyes On You',
    character: '鈴木羽那',
    baseImage: 'Eyes On You 鈴木羽那.webp',
    awakenedImage: 'Eyes On You 鈴木羽那+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【Hopeland】郁田はるき',
    theme: 'Hopeland',
    character: '郁田はるき',
    baseImage: 'Hopeland 郁田はるき.webp',
    awakenedImage: 'Hopeland 郁田はるき+.webp',
    rarity: 'SSR' as const,
  },

  // ========== SR 卡 (44 张) ==========
{
    fullName: '【ぐうぜんBOOKS】櫻木真乃',
    theme: 'ぐうぜんBOOKS',
    character: '櫻木真乃',
    baseImage: 'ぐうぜんBOOKS 櫻木真乃.webp',
    awakenedImage: 'ぐうぜんBOOKS 櫻木真乃+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【花結びゆくゆく】櫻木真乃',
    theme: '花結びゆくゆく',
    character: '櫻木真乃',
    baseImage: '花結びゆくゆく 櫻木真乃.webp',
    awakenedImage: '花結びゆくゆく 櫻木真乃+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【手作りの心遣い】風野灯織',
    theme: '手作りの心遣い',
    character: '風野灯織',
    baseImage: '手作りの心遣い 風野灯織.webp',
    awakenedImage: '手作りの心遣い 風野灯織+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【落下予測地点】風野灯織',
    theme: '落下予測地点',
    character: '風野灯織',
    baseImage: '落下予測地点 風野灯織.webp',
    awakenedImage: '落下予測地点 風野灯織+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【小さな夜のトロイメライ】八宮めぐる',
    theme: '小さな夜のトロイメライ',
    character: '八宮めぐる',
    baseImage: '小さな夜のトロイメライ 八宮めぐる.webp',
    awakenedImage: '小さな夜のトロイメライ 八宮めぐる+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【チエルアルコは流星の】八宮めぐる',
    theme: 'チエルアルコは流星の',
    character: '八宮めぐる',
    baseImage: 'チエルアルコは流星の 八宮めぐる.webp',
    awakenedImage: 'チエルアルコは流星の 八宮めぐる+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【ばってん長崎恋岬】月岡恋鐘',
    theme: 'ばってん長崎恋岬',
    character: '月岡恋鐘',
    baseImage: 'ばってん長崎恋岬 月岡恋鐘.webp',
    awakenedImage: 'ばってん長崎恋岬 月岡恋鐘+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【ビ～♡バップ海岸】月岡恋鐘',
    theme: 'ビ～♡バップ海岸',
    character: '月岡恋鐘',
    baseImage: 'ビ～♡バップ海岸 月岡恋鐘.webp',
    awakenedImage: 'ビ～♡バップ海岸 月岡恋鐘+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【裏腹あまのじゃく】田中摩美々',
    theme: '裏腹あまのじゃく',
    character: '田中摩美々',
    baseImage: '裏腹あまのじゃく 田中摩美々.webp',
    awakenedImage: '裏腹あまのじゃく 田中摩美々+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【そのまみみ無気力につき】田中摩美々',
    theme: 'そのまみみ無気力につき',
    character: '田中摩美々',
    baseImage: 'そのまみみ無気力につき 田中摩美々.webp',
    awakenedImage: 'そのまみみ無気力につき 田中摩美々+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【秘めやかファンサービス】白瀬咲耶',
    theme: '秘めやかファンサービス',
    character: '白瀬咲耶',
    baseImage: '秘めやかファンサービス 白瀬咲耶.webp',
    awakenedImage: '秘めやかファンサービス 白瀬咲耶+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【真紅一輪】白瀬咲耶',
    theme: '真紅一輪',
    character: '白瀬咲耶',
    baseImage: '真紅一輪 白瀬咲耶.webp',
    awakenedImage: '真紅一輪 白瀬咲耶+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【カラフルメタモルフォーゼ】三峰結華',
    theme: 'カラフルメタモルフォーゼ',
    character: '三峰結華',
    baseImage: 'カラフルメタモルフォーゼ 三峰結華.webp',
    awakenedImage: 'カラフルメタモルフォーゼ 三峰結華+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【雨色、上機嫌】三峰結華',
    theme: '雨色、上機嫌',
    character: '三峰結華',
    baseImage: '雨色、上機嫌 三峰結華.webp',
    awakenedImage: '雨色、上機嫌 三峰結華+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【包・帯・組・曲】幽谷霧子',
    theme: '包・帯・組・曲',
    character: '幽谷霧子',
    baseImage: '包・帯・組・曲 幽谷霧子.webp',
    awakenedImage: '包・帯・組・曲 幽谷霧子+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【伝・伝・心・音】幽谷霧子',
    theme: '伝・伝・心・音',
    character: '幽谷霧子',
    baseImage: '伝・伝・心・音 幽谷霧子.webp',
    awakenedImage: '伝・伝・心・音 幽谷霧子+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【白・白・白・祈】幽谷霧子',
    theme: '白・白・白・祈',
    character: '幽谷霧子',
    baseImage: '白・白・白・祈 幽谷霧子.webp',
    awakenedImage: '白・白・白・祈 幽谷霧子+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【マメ丸と一緒！】小宮果穂',
    theme: 'マメ丸と一緒！',
    character: '小宮果穂',
    baseImage: 'マメ丸と一緒！ 小宮果穂.webp',
    awakenedImage: 'マメ丸と一緒！ 小宮果穂+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【キャッチ・ザ・フォール！】小宮果穂',
    theme: 'キャッチ・ザ・フォール！',
    character: '小宮果穂',
    baseImage: 'キャッチ・ザ・フォール！ 小宮果穂.webp',
    awakenedImage: 'キャッチ・ザ・フォール！ 小宮果穂+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【純真チョコレート】園田智代子',
    theme: '純真チョコレート',
    character: '園田智代子',
    baseImage: '純真チョコレート 園田智代子.webp',
    awakenedImage: '純真チョコレート 園田智代子+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【バッドガールの羽ばたき】西城樹里',
    theme: 'バッドガールの羽ばたき',
    character: '西城樹里',
    baseImage: 'バッドガールの羽ばたき 西城樹里.webp',
    awakenedImage: 'バッドガールの羽ばたき 西城樹里+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【オフデーゲーム】西城樹里',
    theme: 'オフデーゲーム',
    character: '西城樹里',
    baseImage: 'オフデーゲーム 西城樹里.webp',
    awakenedImage: 'オフデーゲーム 西城樹里+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【想ひいろは】杜野凛世',
    theme: '想ひいろは',
    character: '杜野凛世',
    baseImage: '想ひいろは 杜野凛世.webp',
    awakenedImage: '想ひいろは 杜野凛世+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【微熱風鈴】杜野凛世',
    theme: '微熱風鈴',
    character: '杜野凛世',
    baseImage: '微熱風鈴 杜野凛世.webp',
    awakenedImage: '微熱風鈴 杜野凛世+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【ストイックトレーニング】有栖川夏葉',
    theme: 'ストイックトレーニング',
    character: '有栖川夏葉',
    baseImage: 'ストイックトレーニング 有栖川夏葉.webp',
    awakenedImage: 'ストイックトレーニング 有栖川夏葉+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【鳥籠をひらいて】有栖川夏葉',
    theme: '鳥籠をひらいて',
    character: '有栖川夏葉',
    baseImage: '鳥籠をひらいて 有栖川夏葉.webp',
    awakenedImage: '鳥籠をひらいて 有栖川夏葉+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【似合うかな？】大崎甘奈',
    theme: '似合うかな？',
    character: '大崎甘奈',
    baseImage: '似合うかな？ 大崎甘奈.webp',
    awakenedImage: '似合うかな？ 大崎甘奈+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【甜花ちゃんといっしょ☆】大崎甘奈',
    theme: '甜花ちゃんといっしょ☆',
    character: '大崎甘奈',
    baseImage: '甜花ちゃんといっしょ☆ 大崎甘奈.webp',
    awakenedImage: '甜花ちゃんといっしょ☆ 大崎甘奈+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【秘密のだらだらタイム】大崎甜花',
    theme: '秘密のだらだらタイム',
    character: '大崎甜花',
    baseImage: '秘密のだらだらタイム 大崎甜花.webp',
    awakenedImage: '秘密のだらだらタイム 大崎甜花+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【氷上バンビーナ】大崎甜花',
    theme: '氷上バンビーナ',
    character: '大崎甜花',
    baseImage: '氷上バンビーナ 大崎甜花.webp',
    awakenedImage: '氷上バンビーナ 大崎甜花+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【お日様染めのマリーナ】大崎甜花',
    theme: 'お日様染めのマリーナ',
    character: '大崎甜花',
    baseImage: 'お日様染めのマリーナ 大崎甜花.webp',
    awakenedImage: 'お日様染めのマリーナ 大崎甜花+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【マイフェイバリット】桑山千雪',
    theme: 'マイフェイバリット',
    character: '桑山千雪',
    baseImage: 'マイフェイバリット 桑山千雪.webp',
    awakenedImage: 'マイフェイバリット 桑山千雪+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【一夏一刻物語】桑山千雪',
    theme: '一夏一刻物語',
    character: '桑山千雪',
    baseImage: '一夏一刻物語 桑山千雪.webp',
    awakenedImage: '一夏一刻物語 桑山千雪+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【さかさま世界】芹沢あさひ',
    theme: 'さかさま世界',
    character: '芹沢あさひ',
    baseImage: 'さかさま世界 芹沢あさひ.webp',
    awakenedImage: 'さかさま世界 芹沢あさひ+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【ア・冬優子イズム】黛冬優子',
    theme: 'ア・冬優子イズム',
    character: '黛冬優子',
    baseImage: 'ア・冬優子イズム 黛冬優子.webp',
    awakenedImage: 'ア・冬優子イズム 黛冬優子+.webp',
    rarity: 'SSR' as const,
  },
  {
    fullName: '【気になる！？染めちゃう！？】和泉愛依',
    theme: '気になる！？染めちゃう！？',
    character: '和泉愛依',
    baseImage: '気になる！？染めちゃう！？ 和泉愛依.webp',
    awakenedImage: '気になる！？染めちゃう！？ 和泉愛依+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【おかえり、 ギター】浅倉透',
    theme: 'おかえり、 ギター',
    character: '浅倉透',
    baseImage: 'おかえり、 ギター 浅倉透.webp',
    awakenedImage: 'おかえり、 ギター 浅倉透+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【カラメル】樋口円香',
    theme: 'カラメル',
    character: '樋口円香',
    baseImage: 'カラメル 樋口円香.webp',
    awakenedImage: 'カラメル 樋口円香+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【Makeup♡Box】市川雛菜',
    theme: 'Makeup♡Box',
    character: '市川雛菜',
    baseImage: 'Makeup♡Box 市川雛菜.webp',
    awakenedImage: 'Makeup♡Box 市川雛菜+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【泣けよ洗濯機】七草にちか',
    theme: '泣けよ洗濯機',
    character: '七草にちか',
    baseImage: '泣けよ洗濯機 七草にちか.webp',
    awakenedImage: '泣けよ洗濯機 七草にちか+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【MANNEQUIN】緋田美琴',
    theme: 'MANNEQUIN',
    character: '緋田美琴',
    baseImage: 'MANNEQUIN 緋田美琴.webp',
    awakenedImage: 'MANNEQUIN 緋田美琴+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【Blind Driver】斑鳩ルカ',
    theme: 'Blind Driver',
    character: '斑鳩ルカ',
    baseImage: 'Blind Driver 斑鳩ルカ.webp',
    awakenedImage: 'Blind Driver 斑鳩ルカ+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【優You】鈴木羽那',
    theme: '優You',
    character: '鈴木羽那',
    baseImage: '優You 鈴木羽那.webp',
    awakenedImage: '優You 鈴木羽那+.webp',
    rarity: 'SR' as const,
  },
  {
    fullName: '【漂白花火】郁田はるき',
    theme: '漂白花火',
    character: '郁田はるき',
    baseImage: '漂白花火 郁田はるき.webp',
    awakenedImage: '漂白花火 郁田はるき+.webp',
    rarity: 'SR' as const,
  },
];

/**
 * 卡池配置
 */
export const STARRY_NIGHT_POOL = {
  id: 'starry-night',
  name: '星月夜を歩いて',
  description: '【絵空靴】杜野凛世 期间限定',
  pickupCard: PICKUP_CARD,
  cards: POOL_CARDS,
  thumbnailUrl: `${POOL_IMAGE_BASE}/星月夜を歩いて.webp`,
  backgroundUrl: `${CARD_IMAGE_BASE}/${encodeURIComponent(PICKUP_CARD.baseImage)}`,
  startDate: '2025-01-01',
  endDate: '2025-02-01',
  status: 'active' as const,
};

/**
 * 卡池统计信息
 */
export const POOL_STATS = {
  total: 171,
  ur: 3,
  ssr: 124,
  sr: 44,
  pickup: 1,
};
